### ISSUE TITLE
Posts Widget: a feature to add the title on the featured image

### ISSUE THREAD

**Issue by RodiKhalil** [pojome/elementor#5387] opened 2018-08-12 11:36 UTC
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This is a request about the "Posts Widget".
I would like to insert "_the title of the post_" directly on the featured image. Currently, the options I have in Posts Widget allows me to insert the title only on the left/right/below of the featured image, but not on the image itself.

**Describe the solution you'd like**
I would like to have an option in "Posts Widget" that enables me to have the title of the post on the featured image itself, _not out of the borders of the image_.

**Additional context**
Click [HERE ](https://ibb.co/cBTJJ9) to see a screenshot example.

**Comment by bainternet** [comment] 2018-08-12 12:45
Duplicate of #4440

**Closed by bainternet** 2018-08-12 12:45 UTC

**Comment by bainternet** [comment] 2018-08-12 17:34
Yep, same topic
