### ISSUE TITLE
Extending Design Capabilities with Cards Skin & Theme Builder

### ISSUE THREAD

**Issue by Bisso** [pojome/elementor#5584] opened 2018-08-28 17:35 UTC
Hey Folks,

I would like ElementorPro to offer more advanced options to extend the design capabilities.
I'm referring to the [Cards Skin](https://elementor.com/pro-v150-cards-skin/) & the dynamic [Theme Builder](https://elementor.com/theme-builder/).

Here're some ideas:
I have a custom post type that has some custom fields (using ACF for example) and some custom taxonomies, and I would like to have the below feature for a more dynamic website design.

**1. User Avatar (Author):** 
I would like to have an option to replace it with any other dynamic "image" custom field. 

**2. Featured Image:** 
I would like to have an option to replace it with any other dynamic "image" custom field. 

**3. Custom Fields:**
I would like to have an option to display my custom fields dynamically inside the card itself, with also an icon beside each custom field.
_e.g. to display more than a custom field after/before post meta or at the end of the card._
or the option to display any custom field as a badge.

**4. Custom Taxonomies:**
I would like to have an option to display my custom taxonomies dynamically inside the card itself, with also an icon beside each custom category/tag.
_( I know that it is possible to show any other taxonomy as a badge. but I would like to display more than one custom taxonomy as badges, OR after/before post meta OR at the end of the card._

**5. Post Last Modified Date:** 
Similar to the "Published Date" in the meta data, I want to display the last date of the "Post updated/modified on", with also an icon beside it. [WordPress function here](https://codex.wordpress.org/Function_Reference/get_the_modified_date)

I believe this might open a new door for limitless customizations in the future.

Thanks.

--

**Comment by bainternet** [comment] 2018-08-29 19:49
Duplicate of #4440

**Comment by bainternet** [comment] 2018-08-29 19:49
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Closed by bainternet** 2018-08-29 19:49 UTC

**Comment by Bisso** [comment] 2018-08-29 20:43
shall I post it there? #4440
