### ISSUE TITLE
Blog Archives: Include Categories in Meta Data

### ISSUE THREAD

**Issue by hubmacfan** [pojome/elementor#4878] opened 2018-06-26 12:35 UTC
When designing an Archive Page, currently, a user can choose between Author, Date, Time, and Comments. I would like the option to display categories as well. Many blog templates include this in their archive posts.

**Comment by bainternet** [comment] 2018-06-26 14:44
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

Duplicate of #4440

**Closed by bainternet** 2018-06-26 14:44 UTC
