### ISSUE TITLE
Global Widgets not updating across website

### ISSUE THREAD

**Issue by taropaa** [pojome/elementor#6856] opened 2019-01-23 22:08 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Global widgets do not act globally. IE if I create a global widget, add it on two pages, then update it, the update will not be reflected across both pages.

## Steps to reproduce
1. Create a new page
2. Create an element. 
3. Save it as a global widget.
4. Create another new page
5. Insert the global element created in step 3.
6. Edit the global element (using Edit NOT Unlink).
7. Visit the page you created in step 1.

The element will not have updated, despite it being a global element.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active. Happens with the Elementor Hello Theme
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by taropaa** [comment] 2019-01-23 22:18
I was unable to consistently produce the issue. It seems to happen if I include the same global widget into two different templates. Editing the global widget on the page it was created on seems to have updated it across the website. I am sure this process will be refined and made more stable in the future so I will close this request.

**Comment by Code711** [comment] 2019-02-04 14:14
Same problem here, I created a global slider-widget. When I edit this global widget, it ist okay for the page where I created it. But on all other sites across my website the edited widget-slides are just white (what makes this just unusable right now).

**Comment by shilo-ey** [comment] 2019-02-11 15:49
Hi @taropaa @Code711 

This has been fixed in Elementor Pro 2.4.4.

Feel free to update!

thanks.

**Closed by shilo-ey** 2019-02-11 15:49 UTC
Labels: bug, pro, status/merged

**Comment by Code711** [comment] 2019-02-11 15:59
Seems to work correct now, thanks!

**Comment by cohler** [comment] 2020-06-26 12:41
The problem is back!!

**Comment by Atomic-Education** [comment] 2021-03-27 21:35
Problem still exists.

**Comment by JDBem** [comment] 2021-07-28 10:37
Problem still exist, any news on when this will be fixed?

**Comment by JDBem** [comment] 2021-07-28 10:47
> The problem still exists, any news on when this will be fixed?

Found out the reason why it wasn't updating my global blocks. Will share it in case this is what you are doing as well. 

I had all my global blocks on a global block master page set as a draft page so I can edit them all in one place, but they weren't updating. I wanted it as a draft because I didn't want it to be crawled but having it as a draft was what was causing it to not update my global blocks. Now I have it as private and every time I edit the global blocks they update all instances.

Hope this helps.
