### ISSUE TITLE
Slider Widget Pro

### ISSUE THREAD

**Issue by studi778** [pojome/elementor#7017] opened 2019-02-08 18:49 UTC
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated when I use the slider widget pro as i cannot put content in boxes that overlay the slider. It is extremely basic.

**Describe the solution you'd like**
I would like you to add more features to the slider widget pro so that i can put content in boxes of any colour/transparency that overlay the slide images and also be positioned where I need them. The existing Slider Widget Pro is shockingly basic and it really needs the ability to have content placed in boxes that overlays the images and be positioned. Even the extremely slow team at Beaver Builder have this covered with their native slider features as seen here: https://kb.wpbeaverbuilder.com/article/186-content-slider-module-overview 

**Describe alternatives you've considered**
I have considered implementing 3rd party slider widgets but they dont play well with elementor.

**Additional context**

**Comment by shilo-ey** [comment] 2019-02-10 08:39
Duplicate of #219

**Closed by shilo-ey** 2019-02-10 08:39 UTC

**Comment by nicholaszein** [comment] 2023-06-19 15:53
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the new Nested Carousel was released with Elementor Pro v3.14.0! 🥳 

You can now create Carousels or Slides with custom nested widgets without needing to use shortcodes or other features! 💪 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
