### ISSUE TITLE
Add 500px to the Social Network Widget

### ISSUE THREAD

**Issue by konepartners** [pojome/elementor#3712] opened 2018-03-09 09:00 UTC
## Description
I was building a social network widget with elementor page buider, and I see there is not possibility to add a 500px.com reference. For a photographer website, it is really needed.

## Environment
500px.com is a social network quite the same as Instagram, but more oriented Photographers, we are said the pictures on 500px are better than Instagram. Anyway, people have to register to post their photos on the 500px.com site, and then can give a a rating on photos of other photographer. The pictures get a ranking, are getting popular.. or not... that is all the game of that site :-) making all a network of social interaction around beautiful photos, hopefully. 

Having 500px as part of the Social Network Widget would be wonderful.

**Comment by bainternet** [comment] 2018-03-10 15:23
Duplicate of #3636

**Closed by bainternet** 2018-03-10 15:23 UTC
