### ISSUE TITLE
Templates for Posts PRO

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#5881] opened 2018-10-09 10:38 UTC
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

The posts widget is not so flexible, you cannot control where you want to show the title, excerpt, feature image etc. 

**Describe the solution you'd like**

My solution is have the possibilitie of create templates or change templates, something like Oxygen does: https://prnt.sc/l3y0ri

**Additional context**

I think post widget is one of the most important widgets, because it makes your site dinamic, and this widget there's no updates for long time, you should take care of this and the old widgets too ;)

**Comment by bainternet** [comment] 2018-10-09 14:29
Duplicate of #4440

**Closed by bainternet** 2018-10-09 14:29 UTC

**Comment by nicholaszein** [comment] 2023-08-01 18:03
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
