### ISSUE TITLE
REQUEST: Easy way in PHP to re-init Elementor on Ajax loaded content.

### ISSUE THREAD

**Issue by justanotherco** [pojome/elementor#5998] opened 2018-10-26 12:28 UTC
If a user clicks a button to load more content via Ajax, and the theme uses:

`echo apply_filters( 'the_content', $post->post_content );`

The Elementor content is not rendered properly (as it does on a normal loading of the same content).

Visual Composer has a way to re-load itself by calling a Visual Composer function before you echo the_content.

Can Elementor also get a way to do this?

**Comment by bainternet** [comment] 2018-10-28 08:12
Duplicate of #5843

**Closed by bainternet** 2018-10-28 08:12 UTC
