### ISSUE TITLE
Problem with Shortcake (Shortcode UI)

### ISSUE THREAD

**Issue by soyket** [pojome/elementor#1580] opened 2017-04-03 05:46 UTC
Hello, I used the builder for first time today ! I loved it . Awesome work there.
But seems it has issue with : https://wordpress.org/plugins/shortcodes-ultimate/
(Shortcode Ultimate) and also shortcake : https://wordpress.org/plugins/shortcode-ui/
Both are very useful . I wonder why they don’t open up the tabs when using the page builder

Thanks

**Comment by arielk** [comment] 2017-04-03 16:03
We know this conflict (https://github.com/pojome/elementor/issues/1033), I think it’s something with the behavior of Shortcode Ultimate.

Unfortunately, we can not fix this issue, it’s something that does not depend on us.

Try to create a shortcode in a regular editing mode, take the shortcode and insert it inside the text editor, and see if it works.

**Comment by soyket** [comment] 2017-04-03 17:08
hmm but if it was only with shortcode ultimate I would think that it's their fault . But seems it doesn't work with shortcake as well! Maybe I will try another shortcode maker plguin and get back to you guys ! But do look inside what's causing it . And about that I know the shortcodes work . But basically no one wants to remember the shortcodes and needs a button to insert them right ? So shortcode ultimate  or shortcake these have those buttons to select shortcode and insert them .

**Comment by carasmo** [comment] 2017-04-25 16:14
Yes it doesn't work with Shortcake and Better Font Awesome icon picker. Since it's happening with two different plugins, not made by the same devs, it's probably elementor. The only thing I can see in the console is a variable named 'n' is undefined and it looks like it's coming from underscore. I can't figure it out.

**Comment by soyket** [comment] 2017-05-08 07:32
Someone from Elementor should look at this issue and fix it

**Comment by bainternet** [comment] 2018-05-23 08:04
Duplicate of #1033

**Closed by bainternet** 2018-05-23 08:04 UTC
Labels: compatibility
