### ISSUE TITLE
Stop making widgets with uncustomizable text

### ISSUE THREAD

**Issue by JoeDarko** [pojome/elementor#6406] opened 2018-12-12 02:04 UTC
I just wanted to point out something that i think should be considered as an important rule when developing new widgets.

The rule is: **No widget should EVER insert uncustomizable text into the website.**

If any PRO widget inserts English words into the actual website, then there has to be an option to customize the text. You can't just wait until somebody translates the PRO plugin into every language. No uncustomizable text should ever be inserted into the front-end.

In most cases the rule is followed, but sometimes it isn't.

Good example is the Menu Cart widget. Right now the widget uses words as "Subtotal", "Show Cart", "Checkout". These words can't be customized/translated. So this widget can only be used on English websites.

So imagine you buy the PRO version, you want to build an ecommerce website and... boom, you find out that you can't use the Menu Cart plugin because it inserts english words into your website. You can't build ecommerce website without a cart in the header so you are stuck.

Small details like this can totally ruin everything for non-english users. Non-english users pay the same price, so they should get the same value.

So please, can you fix the Menu Cart widget and relay the suggested rule to the developers? I think it's very fundamental and should be followed.

**No widget should EVER insert uncustomizable text into the website.**

**Comment by pr0pre** [comment] 2018-12-12 02:51
Word

**Comment by black-eye** [comment] 2018-12-13 12:12
+1

**Comment by bainternet** [comment] 2018-12-13 13:31
thanks for the feedback.

**Comment by bainternet** [comment] 2018-12-13 13:32
Duplicate of #5495

**Closed by bainternet** 2018-12-13 13:32 UTC
