### ISSUE TITLE
Resposive Devices

### ISSUE THREAD

**Issue by Sayeed1440** [pojome/elementor#6117] opened 2018-11-09 20:25 UTC
Alert: Do not mark it as duplicate feature request before reading completely.

I develop websites for my clients using Elementor & they love it.

But while handing the websites to my clients, they check it on Desktop, Laptop, Tablet & Mobile. 

Unfortunately, by default Elementor offers only 3 devices responsive option. This messes up the situation a lot as we can't escape it. We can either do it for a laptop or desktop (Is there a solution to this problem?). 

I would request you to add an extra option of a laptop in a responsive mode, if possible.

I would also like to add that some plugins such as Revolution slider are offering 4 device option & in fact, Bakery Builder is also offering the same.

I hope you will understand the situation of ours and add this feature in the future updates of Elementor.

Thank You
Sayeed Afzal
CMO at Cuion

**Comment by bainternet** [comment] 2018-11-11 07:50
Duplicate of #2043

**Comment by bainternet** [comment] 2018-11-11 07:50
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Closed by bainternet** 2018-11-11 07:50 UTC
