### ISSUE TITLE
Feature Request - Create Group selection for widgets panel

### ISSUE THREAD

**Issue by JRGWxRxZ** [pojome/elementor#3921] opened 2018-03-27 12:04 UTC

**Comment by arielk** [comment] 2018-03-27 12:13
Duplicate of #879

**Closed by arielk** 2018-03-27 12:13 UTC

**Comment by JRGWxRxZ** [comment] 2018-03-27 12:18
It was not related to this #879 request but rather to this one Feature Request: Better widget selector #3805, but whatever it was already addressed and closed.

**Comment by Giffordcl** [comment] 2018-03-28 09:43
I don't know if this is appropriate for this topic, or if it is already closed, but limit the ability of third party to include in the widget selector any widgets that are not included in your download, ie one that needs to be paid for that wasn't included, I had one package I purchased,  when I went to use it from the selector it gave me a message that was part of a pro package but never indicated it elsewhere.
