### ISSUE TITLE
[bug] Update to Elementor 2.1.7. breaks Posts widget

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#5442] opened 2018-08-15 22:28 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

1. The original layout for my archive pages uses the Posts widget and card style.

<img width="1187" alt="original-archive-layout" src="https://user-images.githubusercontent.com/974442/44176543-15c0c800-a09f-11e8-9fd5-8786ee93ac0b.png">

2. The dashboard indicates that there's an update for:
Elementor
You have version 2.1.6 installed. Update to 2.1.7.

After upgrading, instances of the Archive Posts widget in my Elementor archives template break. (see screenshot) Also instances of Post widget on my homepage. 

<img width="1229" alt="elementor-upgrade-2 1 7 -breaks" src="https://user-images.githubusercontent.com/974442/44176444-acd95000-a09e-11e8-8384-f2c2449eb10c.png">

3. Using Elementor > Tools to roll back to version 2.1.6 results in my archive pages being broken in a different way. (see screenshot)

<img width="1224" alt="after-rollback-to-2 1 6-still-broken" src="https://user-images.githubusercontent.com/974442/44176442-acd95000-a09e-11e8-80b8-625dd4dbcff7.png">

## Steps to reproduce

I went back and started with a fresh copy of the site and the results after updating Elementor are the same.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/4.1.0
	MySQL version: 5.6.32
	PHP Version: 7.1.18-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 4000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://staging.ucsflibrary.flywheelsites.com
	Home URL: http://staging.ucsflibrary.flywheelsites.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 128M
	Permalink Structure: /news/%postname%/
	Language: en-US
	Timezone: America/Los_Angeles
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 2.1.3
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

== Active Plugins ==
	Better Font Awesome
		Version: 1.7.1
		Author: Mickey Kay

	Central Color Palette
		Version: 1.12.5
		Author: Gáravo

	Code Snippets
		Version: 2.11.0
		Author: Shea Bunge

	Compress JPEG & PNG images
		Version: 3.0.1
		Author: TinyPNG

	Crazy Egg
		Version: 2.1
		Author: Crazy Egg

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Elementor
		Version: 2.1.6
		Author: Elementor.com

	Elementor Extras
		Version: 1.9.11
		Author: Namogo

	Elementor Pro
		Version: 2.0.18
		Author: Elementor.com

	Email Address Encoder
		Version: 1.0.7
		Author: Till Krüss

	Export All URLs
		Version: 3.5
		Author: Atlas Gondal

	Forget About Shortcode Buttons
		Version: 2.1.1
		Author: Designs & Code

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	GP Premium
		Version: 1.6.2
		Author: Tom Usborne

	Hooks Visualizer
		Version: 0.2
		Author: WebTechStreet

	Jetpack by WordPress.com
		Version: 6.4.2
		Author: Automattic

	LibCal Hours for WordPress
		Version: 1.1.1
		Author: Stefan Topfstedt

	Loginizer
		Version: 1.4.0
		Author: Raj Kothari

	Microthemer
		Version: 5.2.3.4
		Author: Themeover

	MomentoPress for Momento360
		Version: 1.0.1
		Author: Chris Yee

	Redirection
		Version: 3.4
		Author: John Godley

	Relevanssi
		Version: 4.0.11
		Author: Mikko Saari

	Simple CSS
		Version: 1.1
		Author: Tom Usborne

	SVG Support
		Version: 2.3.15
		Author: Benbodhi

	TablePress
		Version: 1.9
		Author: Tobias Bäthge

	TablePress Extension: Column filters
		Version: 1.0.0
		Author: Stefan Topfstedt

	TablePress Extension: Shortcode Attributes Plus
		Version: 1.0.0
		Author: Stefan Topfstedt

	The SEO Framework
		Version: 3.0.6
		Author: Sybre Waaijer

	User Role Editor
		Version: 4.44
		Author: Vladimir Garagulya

	WP-Optimize
		Version: 2.2.4
		Author: David Anderson, Ruhani Rabin, Team Updraft

	WPForms
		Version: 1.4.7.2
		Author: WPForms

	WPForms MailChimp
		Version: 1.2.0
		Author: WPForms

	WP User Avatar
		Version: 2.1.5
		Author: flippercode


== Must-Use Plugins ==
	Local by Flywheel Relative URL (for Live Links)
		Version: 1.0
		Author: Flywheel


== Debug ==
	Errors: 
		TypeError: jQuery(...).LibCalMySched is not a function
			at https://staging.ucsflibrary.flywheelsites.com/wp-admin/load-scripts.php?c=1&load%5B%5D=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8 line 8 > eval - 3:4
			2018-08-11 02:32 +00:00

		TypeError: this.search is undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:157916
			2018-08-11 02:24 +00:00

		TypeError: Cannot read property 'currentView' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:157928
			2018-08-10 14:50 +00:00
			x 2 times

		TypeError: jQuery(...).LibCalMySched is not a function
			at https://staging.ucsflibrary.flywheelsites.com/wp-admin/post.php?post=1874&action=elementor - 3:27
			2018-08-10 14:49 +00:00
			x 5 times

		TypeError: jQuery(...).LibCalMySched is not a function
			at https://staging.ucsflibrary.flywheelsites.com/wp-admin/post.php?post=1878&action=elementor - 3:27
			2018-08-10 14:45 +00:00

		TypeError: jQuery(...).LibCalMySched is not a function
			at https://staging.ucsflibrary.flywheelsites.com/wp-admin/post.php?post=1874&action=elementor - 3:27
			2018-08-10 02:00 +00:00

		TypeError: Cannot read property 'currentView' of undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:157928
			2018-08-08 23:02 +00:00
			x 2 times

		TypeError: jQuery(...).LibCalMySched is not a function
			at https://staging.ucsflibrary.flywheelsites.com/wp-admin/post.php?post=1878&action=elementor - 3:27
			2018-08-07 21:42 +00:00

		ReferenceError: summonWidget is not defined
			at https://staging.ucsflibrary.flywheelsites.com/wp-admin/post.php?post=632&action=elementor - 1:1
			2018-08-06 18:08 +00:00

		TypeError: this.search is undefined
			at https://staging.ucsflibrary.flywheelsites.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.6 - 2:157916
			2018-08-03 20:47 +00:00

				
```
</details>

**Comment by footslogger** [comment] 2018-08-16 06:31
I posted same experience under #5416 - 8+ hours ago, both emails have been deleted. 

2.1.7 broke the site and I have the same outcome as described above now after recovering. 

https://wordpress.org/support/topic/elementor-2-1-7-incompatibility/

**Please do not delete this message Elementor**

**Comment by divstudioweb** [comment] 2018-08-16 11:18
I have the same problem :(

**Comment by arielk** [comment] 2018-08-16 12:00
Can you share with us a link to the page with this issue?

**Comment by messina614** [comment] 2018-08-16 15:13
I had the exact same thing happen to me this morning. All of my client sites had the thumbnail issue on the post module, and I had to manually go in and fix each one of them. 

Is there a response from Elementor about this? I am now afraid to update the plugin in the future, as most of the sites that I manage utilize it.

**Comment by arielk** [comment] 2018-08-16 15:41
@mizejewski 
@messina614 
@divstudioweb  

Unfortunately, we can not reproduce this bug. Is your Elementor & Elementor Pro updated to the latest version?

If you have a link to the page with the problem please share with us, so we can check it out.

**Comment by arielk** [comment] 2018-08-16 16:39
@mizejewski It’s ok, just backup your site and update the pro version also and it will be fixed.

**Comment by mizejewski** [comment] 2018-08-16 16:46
@arielk just updated Pro to the latest and that fixed some things, but breaks others. Note on http://staging.ucsflibrary.flywheelsites.com/news/ that all spacing around the content is gone now. Single post spacing is also affected with the featured image now covering up the menu. 

![latest-pro](https://user-images.githubusercontent.com/974442/44222334-042bfe80-a139-11e8-89f2-554f2e027d2d.png)

![intended-archive-page](https://user-images.githubusercontent.com/974442/44222382-2d4c8f00-a139-11e8-9400-e2941d5d5541.png)

**Comment by arielk** [comment] 2018-08-16 17:07
Is this a native archive page or is it an archive that built with our Theme Builder?

**Comment by mizejewski** [comment] 2018-08-16 17:16
The archive page is built using Elementor theme builder. Same for the single post template.

**Comment by footslogger** [comment] 2018-08-16 17:30
I have Elementor theme builder page, with Post widget set at 3 columns ,  each post shows up as needle columns. The gap between each post 400% the width of the thumbnail. 

Elementor and Elementor pro both up to date.  

I was prompted to update to 2.1.7 pro was already upto date. 

Since yesterday the product cannot display a working post widget.

what is the fix please

thanks

**Comment by footslogger** [comment] 2018-08-16 17:38
What is the fix for the 2.1.7 release

the Post widget no longer works, all my versions are up to date, it broke when applying the 2.1.7 update yesterday

**Comment by arielk** [comment] 2018-08-16 22:09
@mizejewski I'll check it out.

@footslogger 
Please update to the latest version of Elementor Pro (v2.1.3) and this should work for you.

**Comment by blogsdna** [comment] 2018-08-17 11:12
Same exact issues as mizejewski pointed and after updating to Pro 2.1.3 version, it did fixed post widget up now spacing messed up around many places.

**Comment by blogsdna** [comment] 2018-08-17 11:29
Here are some screenshots for your reference, Before[2.0.16] & After [2.1.3]

Main Content
![before after main content](https://user-images.githubusercontent.com/42468192/44264039-ce713d80-a23e-11e8-9506-5e7d151e2f02.png)


Footer Section

![before after](https://user-images.githubusercontent.com/42468192/44264055-ddf08680-a23e-11e8-85fd-7d3192fa93e4.png)

**Comment by kkri** [comment] 2018-08-17 14:14
Since yesterday, when updating Elementor, I saw that the homepage site (where post wisgets i used both in the Progetti section and in Eventi section, is messy in Internet Explorer, they are displayed full width one under the other. Yes I know IE is old and everything, but here in Italy is still used, especially in public offices where they don't care too much to browsers and before yesterday I must say all was perfect. The worst is that I set correctly the Eventi section and the 3 posts were displayed nicely in all browsers, perfectly bottom aligned while now the last one has a gap near the author tag and it's higher than the other ones. No matter how columns i set, 2,3,4 but the last one is the one that has the gap. How to solve? Currently I use EFree 2.1.7 and EPro 2.1.3, all plugins and theme, and WP updated. Thank you
[see my site](http://www.virtualview.care/)

**Comment by midihead7** [comment] 2018-08-17 21:58
I'm seeing the same problem. I HAVE updated Elementor and Elementor Pro to their latest versions on a local test install. It fixed the display in the Elementor editor but the frontend display is still broken. I have cleared all caches and regenerated CSS but the issue remains.

I'm also seeing an issue where the Elementor 2.1.6 rollback version is not showing as available. Instead it is showing the old 2.0.16 Elementor version (which breaks when I rollback to it because it's too old). See screenshot below.

![posts widget backend](https://user-images.githubusercontent.com/28960642/44290134-25b9e280-a22c-11e8-9e63-dbcca12f04a4.png)

![posts widget frontend](https://user-images.githubusercontent.com/28960642/44290139-2d798700-a22c-11e8-895a-f505cde66ff1.png)

![elementor rollback issue](https://user-images.githubusercontent.com/28960642/44290447-97466080-a22d-11e8-881d-82a57475afbe.png)

**Comment by bainternet** [comment] 2018-08-19 08:25
Thanks everyone,

this should be fixed in next versions of Elementor and Elementor Pro.

**Comment by midihead7** [comment] 2018-08-19 21:27
I previously shared the link but here it is again:
[https://new.homewardpublishingministries.com/free-medical-missionary-resources/articles/](https://new.homewardpublishingministries.com/free-medical-missionary-resources/articles/)

For testing purposes, I also added the Archive Posts widget to this page so that you can see that it is affecting that widget also.

**Comment by arielk** [comment] 2018-08-19 21:42
It looks like the code that comes from your theme make the problem.
Try inserting the following code in your custom CSS and let me know if it worked for you:

```.elementor-grid .elementor-grid-item {
    padding: 0;
    margin: 0;
}```

**Comment by midihead7** [comment] 2018-08-19 21:51
I'm using the Astra theme. Adding your CSS code works to fix the issue so thank you. If this is an Astra problem, what code of theirs is specifically causing the issue so that I can report this to them?

**Comment by midihead7** [comment] 2018-08-20 04:02
Ian from Elementor Support has determined that the cause of the narrow columns is due to this Astra padding:

.ast-separate-container .ast-article-post, .ast-separate-container .ast-article-single {
background-color: #fff;
border-bottom: 1px solid #eee;
margin: 0;
padding: 5.34em 6.67em;

I have reported this to Astra Support.

**Comment by blogsdna** [comment] 2018-08-20 07:29
Elementor Pro 2.1.4 still didn't fix the spacing issue created by the previous update, as I had mentioned in my previous post.

**Comment by mizejewski** [comment] 2018-08-20 21:26
@arielk I just updated my staging site to Elementor Version 2.1.8 and Elementor Pro Version 2.1.4, but the problem noted at https://github.com/pojome/elementor/issues/5442#issuecomment-413611026 is still there.

**Comment by robvdbrand** [comment] 2018-08-21 09:00
Any indication when the updates to Elementor and Elementor Pro fixing this bug are due? I'm having the same problem:

![2018-08-21](https://user-images.githubusercontent.com/6704931/44391940-569e5e00-a531-11e8-8cb7-fba861187361.png)

**Comment by arielk** [comment] 2018-08-21 09:12
@robvdbrand Please update Elementor Pro to the latest version and it will be resolved

@mizejewski In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and we will look into it.

**Comment by robvdbrand** [comment] 2018-08-21 10:08
@arielk I believe I have the latest Pro version, see screenshot:

![2018-08-21 1](https://user-images.githubusercontent.com/6704931/44395654-d3820580-a53a-11e8-8668-0ec21398ec16.png)

**Comment by kochhase** [comment] 2018-08-21 10:45
Hi robvdbrand the latest Version of Elementor Pro is 2.1.4 not 2.014. your version is 6 month behind. ;)

**Comment by robvdbrand** [comment] 2018-08-21 16:12
@kochhase I updated the pro version yesterday and this is what I got...there is no update button.

**Comment by mizejewski** [comment] 2018-08-21 16:14
@arielk I did open a ticket for this problem with support@elementor.com on Aug. 15, but unfortunately, our site is configured so you can only log in from our network. Anything else I can share that will help troubleshoot? I have current versions of everything, but the problem remains.

**Comment by kochhase** [comment] 2018-08-21 16:18
Hi robvdbrand sometimes you have to go to https://my.elementor.com/
there you can download the pro version. now it is version 2.1.5. and overright the old version via ftp.

**Comment by midihead7** [comment] 2018-08-21 17:16
@arielk Even though it was determined that Astra was the cause of my narrow columns issue, updating to Elementor Pro 2.1.5 corrected the issue for me today. The Astra padding that was affecting the column layout now appears to be overridden by Elementor:

<img width="1335" alt="posts widget and archive posts widget fixed css" src="https://user-images.githubusercontent.com/28960642/44417099-7cc00000-a529-11e8-8237-9d4c6f4e74f9.png">

**Comment by bainternet** [comment] 2018-08-22 15:11
Thanks Everyone for the feedback.

@mizejewski We can't replicate this with generatePress after the last version, so its got to be something in your setup, Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Closed by bainternet** 2018-08-22 15:11 UTC

**Comment by mizejewski** [comment] 2018-08-29 20:53
Actually @bainternet I got an email reply from support explaining part of the problem:

> Apparently, this is a result of some change we made in the last update.
Until now, when setting the section to full-width in a single post, didn't override the theme's layout. 
Starting with the latest version, it does.

> In order to resolve this, please change the section's Content Width to Box:
http://i.imgur.com/jV2BfYJ.png

**Comment by garciacrew** [comment] 2018-09-13 01:13
I am using OceanWP and had to add the following to make it work.  Similar to what was noted above but with the added "width: auto"

`.elementor-grid .elementor-grid-item { padding: 0; margin: 0; }`

**Comment by RileyGB** [comment] 2018-10-02 04:32
> I am using Astra theme 1.4.40 on different sites and with different versions of Elementor Pro. Last week I had the same experience. This worked for me when I had choosed the 3 cards layout of de post widget.
> I added this to Custom CSS of the widget:
> 
> .elementor-grid-3 .elementor-grid-item {width: 100%;}

This worked perfectly for me. Thank you so much!

**Comment by cauebasantos** [comment] 2019-11-13 11:47
Hi, everyone. I just updated Elementor and now I'm having this issue, also I can't edit the page with Elementor.
The solutions you guys gave solve the layout problem, but still I can't edit the page.
I have the version 2.7.5 of Elementor free.
Thank you.

![image](https://user-images.githubusercontent.com/34218434/68761032-f68e4e80-05f1-11ea-8910-3d4a94ae4605.png)
