### ISSUE TITLE
Layer Navigation/Panel

### ISSUE THREAD

**Issue by joelbqz** [pojome/elementor#4456] opened 2018-05-15 05:15 UTC
Guys, just made a prototype of this feature we would love to see in Elementor.

https://jumpshare.com/v/GRRp6nrkOmAgLWEj7CWd

Feel free to use my design if you find it useful,
Cheers!

**Comment by bainternet** [comment] 2018-05-15 07:08
Duplicate of #1165

**Closed by bainternet** 2018-05-15 07:08 UTC
