### ISSUE TITLE
+1 for Pods integration

### ISSUE THREAD

**Issue by EdwardBurns** [pojome/elementor#4760] opened 2018-06-15 18:52 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EdwardBurns** [comment] 2018-06-15 18:53
+1 for Pods integration

**Comment by bainternet** [comment] 2018-06-17 06:57
Duplicate of #4129

**Closed by bainternet** 2018-06-17 06:57 UTC
