### ISSUE TITLE
Add Column Nesting, Flexbox Controls, a 12 Grid BootStrap Grid,

### ISSUE THREAD

**Issue by Flipback8** [pojome/elementor#7013] opened 2019-02-08 04:56 UTC
Add Column Nesting, Flexbox Controls, a 12 Grid BootStrap Grid,
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shilo-ey** [comment] 2019-02-10 08:23
Duplicate of #2587

**Closed by shilo-ey** 2019-02-10 08:23 UTC

**Comment by nicholaszein** [comment] 2023-01-11 17:11
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.6** and is now a stable experiment since v3.8 as the Flexbox Container! 🥳 

You can learn more about the Flexbox Container [here](https://elementor.com/help/what-is-a-container/).

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
