### ISSUE TITLE
Addition of Global Settings for typography in the Elementor Pane

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#5395] opened 2018-08-13 10:56 UTC
_Reasoning:_
With the introduction of the Elementor theme builder, the requirement of an underlying theme is reduced to just providing the ‘foundation’ on which to build the site design. The Elementor Hello theme provides the ‘bare bones’ for the development of a site theme but part of that minimal aspect is the lack of ability to set some theme wide styling. Experienced developers will be able to set default values for h1 through h6 styles (font, size, colour) using CSS but it is not as convenient as using “click and select” from within the WordPress and Elementor environments.
_Feature Request:_
Where Elementor>Settings “Disable Default Colours and Disable Default Fonts” are left ‘unchecked’ enable a section in Elementor Pane Hamberger Menu>Style: 
•	In default Colours Add selection for background colour
•	Under colour picker Add a new ‘bar item’ Typography.
•	In the new bar Typography Add the ability to set –
o	p – font size and colour
o	h1 thro h6 – font size, colour and ‘style’ (regular, italic etc.)
o	a link font size, colour and ‘style’ (regular, italic etc.) for ‘normal’, ‘hover’ and ‘visited’
Implementing this would enable the setting up of the site basics in one place without the need to customise the theme and a means of making global changes to the site theme from any page.

**Comment by bainternet** [comment] 2018-08-14 07:41
Duplicate of #3345

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Closed by bainternet** 2018-08-14 07:41 UTC

**Comment by nathan-gbd** [comment] 2019-09-04 09:35
Totally concur - not having any base font size settings with the default fonts is a bizarre omission!

**Comment by Tomhoneyman** [comment] 2019-10-18 02:31
What is with this? Considering the amount of noobs like myself who assume it will have essential features

**Comment by get8bit** [comment] 2019-12-27 02:22
Did they add this yet? The elementor website says they have...

> **Global Fonts** No need to worry about setting the right font. Set it once as a global font and it applies throughout the site.

https://elementor.com/editor/

**Comment by matthewa26** [comment] 2020-02-17 04:07
> Did they add this yet? The elementor website says they have...
> 
> > **Global Fonts** No need to worry about setting the right font. Set it once as a global font and it applies throughout the site.
> 
> https://elementor.com/editor/

They don't call it h1 thru h6.. They instead use Primary Headline, Secondary Headline, Body Text, and Accent Text. I'm hoping they implement this at some point so less custom CSS is required.

**Comment by get8bit** [comment] 2020-02-17 12:42
@matthewa26 They actually did ad h1-h6 global styling in version 2.9, which I think is in beta at the moment. It also allows for global styling of image borders, drop shadows, buttons, etc. https://www.youtube.com/watch?v=0d8c5DtA3kw

**Comment by Tomhoneyman** [comment] 2020-02-17 23:00
So ti pretty much does what Style Kits for Elementor does by the sounds of
it.


*Thomas Honeyman*
Director



This email and any attachments may contain personal information or
information that is otherwise confidential or the subject of copyright. Any
use, disclosure or copying of any part of it is prohibited. The Mycelium
Studios PTY LTD does not warrant that this email or any attachments are
free from viruses or defects. Please check any attachments for viruses and
defects before opening them. If this email is received in error please
delete it and notify us by return email.

**Comment by get8bit** [comment] 2020-02-17 23:22
Update: It's out of beta and now a standard free feature as of today.

I've used the Style Kits for Elementor plug-in and it works great, but this new feature seems to have more functionality such as global shadows, border radius, and even globally styled form fields and (I think) comment sections.

Also, with the update you do not have to check "disable default colors and fonts" like you do with Style Kits. In fact, it's important to keep it unchecked.

**Comment by Tomhoneyman** [comment] 2020-02-17 23:34
If I'm to disable style kits. Is the best way to deactivate the plugin and
then uncheck the "disable default colors and fonts" And then add my global
setting to see if it works? I just need to copy the style kit settings to
make sure the designs remain the same?

Does it allow different style kits? I have a different one for my blog atm.


*Thomas Honeyman*
Director



This email and any attachments may contain personal information or
information that is otherwise confidential or the subject of copyright. Any
use, disclosure or copying of any part of it is prohibited. The Mycelium
Studios PTY LTD does not warrant that this email or any attachments are
free from viruses or defects. Please check any attachments for viruses and
defects before opening them. If this email is received in error please
delete it and notify us by return email.

**Comment by get8bit** [comment] 2020-02-17 23:39
If you already have Style Kits installed and set up, personally, I believe best practice is to leave it installed. You do not want to take the chance of wrecking your production site. If you have a staging domain, or test site, you could try it there.

From what I can tell, the new Elementor Theme Style feature does not allow for unique styles for different pages. It is meant to replace theme styling where all h1s, h2s, paragraph, etc look the same throughout the entire site.
