### ISSUE TITLE
Disable entrance animations on Mobile toggle, or add device width options

### ISSUE THREAD

**Issue by d-marvin** [pojome/elementor#5374] opened 2018-08-10 14:03 UTC
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Many entrance animations work great on the desktop environment and poorly on smaller screens. For example, having fade in from left on a left column and fade in from right on a right column can look awkward when the columns become stacked on mobile. If an element is really tall on mobile, a user may not see the element at all until they scroll all the way to its bottom an the animation kicks in.

**Describe the solution you'd like**
Possible solutions:
![animation](https://user-images.githubusercontent.com/42273482/43961743-cc7a0e00-9c83-11e8-8ed8-ecc702de3565.jpg)
Allow us to disable animations by device or allow us to select alternative animation behavior and attributes based on device.

**Describe alternatives you've considered**
Alternative solution is to not use entrance animations, which in many cases has been the best option.

**Comment by bainternet** [comment] 2018-08-12 13:57
Duplicate of #1639

**Closed by bainternet** 2018-08-12 13:57 UTC
