### ISSUE TITLE
Add the ability to adjust the margins by dragging and dropping so as to allow placing the element anywhere on the page without manually adjusting the margin or padding numbers

### ISSUE THREAD

**Issue by jazir5** [pojome/elementor#5302] opened 2018-08-05 02:38 UTC
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to be able to adjust the margins/padding of an element to adjust it's position to anywhere on the page by dragging and dropping. This is the type of interface i'm describing: http://www.youtube.com/watch?v=Sr5KAxpRhxU&t=0m20s. This would make adjusting elements position on the page much easier.

**Describe the solution you'd like**
Simplified padding and margin adjusting similar to the video linked above

**Describe alternatives you've considered**
There doesn't seem to be an elementor plugin which adds this functionality.

**Comment by bainternet** [comment] 2018-08-08 08:12
Duplicate of #5018

**Closed by bainternet** 2018-08-08 08:12 UTC
