### ISSUE TITLE
Price Table icon and text alignment

### ISSUE THREAD

**Issue by shimsa** [pojome/elementor#3730] opened 2018-03-11 22:50 UTC
Hello,

in the Price Table widget (I am not sure now, maybe in another widget) in the Features section, when I set the alignment to the left, the text on the second line starts under the icon. I think it would be better if it started under the text of the first line.

![price-table](https://user-images.githubusercontent.com/7617350/37259460-e498cc2a-2586-11e8-9b79-c80cbd0e04ef.png)

Thanks for consideration.

Tom

**Comment by bainternet** [comment] 2018-03-15 10:39
Duplicate of #822

**Closed by bainternet** 2018-03-15 10:39 UTC
