### ISSUE TITLE
Elementor Forms: redirection with GET data from the form field

### ISSUE THREAD

**Issue by ramiy** [pojome/elementor#6131] opened 2018-11-12 10:31 UTC
We can deffine a redirection link after submitting the form data, it would be nice if we could add custom data from the form inside our URL.

For example, redirect to:

 https://example.com/thanks?email=[field id="email"]

**Comment by bainternet** [comment] 2018-11-12 11:44
Duplicate of #2564

**Closed by bainternet** 2018-11-12 11:44 UTC
