### ISSUE TITLE
Image Carousel should have a maximum height property

### ISSUE THREAD

**Issue by DJviolin** [pojome/elementor#5704] opened 2018-09-10 10:28 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

I try to achieve the following Image Carousel for my photography portfolio:

![vagolap01](https://user-images.githubusercontent.com/5021728/45291347-34757b80-b4f2-11e8-8856-9d92f40c9f77.jpg)

Few things to note here:

- Portrait and landscape oriented images has the same height (right now, Elementor doesn't respect that, portrait images overflowing to the bottom).
- Instead of how many images should appear on the screen (for example, default is 3), we force to always center a portrait or landscape image with a common max-height value. For photography portfolio, this is good. [Flothemes](https://demo.flothemes.com/crowd-neo/gallery/editorial-wedding-photoshoot/) does the same thing with Slick Slider.

To achieve this, I hade to monkey patch `elementor/includes/frontend.php` to call the unminified version of `js/frontend` file, then in `elementor/assets/js/frontend.js` I edited:

```js
var slickOptions = {
    centerMode: true,
    variableWidth: true,
    // ...
```

Plus I added the following CSS in my child theme:

```css
.elementor-slick-slider .slick-slide img {
  max-height: 50vh !important;
}
```

Which is not really a proper solution.

**Describe the solution you'd like**

- I'm not asking to break the actual implementation, just offer a button to turn on this feature, with the ability to set the maximum height for the slider (with px or vh).
- My upper example probably breaks on mobile and tablet, so needs some testing.

**Describe alternatives you've considered**

- As far is I know there's no alternatives right now. I tried to re-style the default Wordpress gallery with slick, but this is just another way of monkey patching, not portable solution.

**Additional context**

Without the monkey patch (out of the box), this is how it looks:

- no unified height for portrait/landscape images
- no maximum height for the entire slider
- instead only respecting the "Slides to show" property

![vagolap02](https://user-images.githubusercontent.com/5021728/45292174-a6e75b00-b4f4-11e8-819c-0697601c2343.jpg)

Thank You!

**Comment by bainternet** [comment] 2018-09-12 09:16
I merged this issue with  #5476, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by bainternet** 2018-09-12 09:16 UTC

**Comment by 3fku5** [comment] 2018-11-25 10:49
Thank You!

**Comment by mechaphone** [comment] 2019-03-27 10:11
Is there a fix for this?

**Comment by mjflower** [comment] 2019-04-18 15:19
any word on this?

**Comment by dameer** [comment] 2019-07-11 14:50
Still not fixed. Carousel looks awful...

**Comment by TukuToi** [comment] 2020-06-22 16:55
This problem seems not resolved even if the follow-up ticket states the actual request to be invalid due to Elementor 2.7 being meanwhile released

Does Elementor still expect us to use all same sized images in the carousel?
It makes sense because you can't stretch an image to fullwidth, while resizing it in height, without destroying the aspect ratio.

But it should outline that in the UI, right now you can without being stopped, add a stretch property, which will not allow for min-height. And opposed to that, using min-height, you won't' be able to use the full width, obviously

I think this needs improvements or at least a clarification for users to not run into issues.

Thanks!

**Comment by DJviolin** [comment] 2020-07-31 11:09
Any update on this? I almost opened this issue 2 years ago. This is a deal breaker for photography portfolios.

**Comment by kuldeepkumarhp50** [comment] 2020-11-16 16:08
It's such a shame that this feature is still missing and there is no workaround for this in elementor. This feature would have been a great hit though for photography portfolios. I would not have paid for the plugin if I knew it earlier.

**Comment by marcookem** [comment] 2021-05-10 01:58
It's 2021 and the issue is still here. Feature killer. I just need an image gallery that show one image at a time, correctly resizing the vertical images to the same height of the horizontal ones...

**Comment by johanneskopf** [comment] 2021-06-18 14:51
Same as @marcookem . This would solve the problem for me that my images in portrait format are displayed larger in height than images in landscape format.

**Comment by Samg381** [comment] 2023-10-22 17:59
.

**Comment by pmochine** [comment] 2024-11-11 11:30
.

**Comment by DJviolin** [comment] 2024-11-11 11:35
Beauty of the free+premium open source projects: stuff never gets implemented, which solving a niche problem.

**Comment by plantoeat** [comment] 2025-02-11 22:52
🤷‍♂

**Comment by DJviolin** [comment] 2025-02-12 08:17
I know, right? Simple thing, but this is one of those reasons why portfolios as a service still has market share for photographers. Plus, lot of other things, but this is just +1 reason.

"You don't have permissions to re-open this issue"

We are a joke to them.
