### ISSUE TITLE
Accordions auto-toggle when switching between browser tabs or windows

### ISSUE THREAD

**Issue by ShariqKhan2012** [pojome/elementor#5605] opened 2018-08-29 16:30 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description

The issue title pretty much says it all.
If you have an accordion control and it is the focussed widget, then the accordion automatically toggles (collapses or expands) its state when you switch between browser tabs and windows.

[Here ](http://prntscr.com/kobhb8) is a gif that demonstarates the issue.

## Steps to reproduce
If you have an accordion control and it is the focussed widget, then the accordion automatically toggles (collapses or expands) its state when you switch between browser tabs and windows.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment] 2018-08-29 19:35
Duplicate of #3511

**Closed by bainternet** 2018-08-29 19:35 UTC
