### ISSUE TITLE
Option to insert all the Single Post Widgets to create a Post Archive Page

### ISSUE THREAD

**Issue by haemeulrich** [pojome/elementor#4722] opened 2018-06-11 15:48 UTC
Would be very helpful if we had more options to design the Post Archive Page. Would love to have all the Single Post Widgets also for creating the Archive Page. Something as you have with: http://www.elementoraddons.com/anywhere-elementor-pro/

**Comment by bainternet** [comment] 2018-06-12 10:11
Duplicate of #4440

**Closed by bainternet** 2018-06-12 10:11 UTC
