### ISSUE TITLE
Font Awesome 5 Bug (And Workaround)

### ISSUE THREAD

**Issue by AlanCW** [pojome/elementor#5990] opened 2018-10-25 18:26 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest stable version of Elementor.

## Description
Support for Font Awesome 5 isn't working as expected. The Elementor Social Widget worked fine on my local production copy. However, when uploaded to the client's server, the icons break down to the usual gibberish squares. This could quite possibly be attributed to a conflicting plugin that also uses Font Awesome.

## Steps to reproduce
Setup a new Elementor template with a new section. Drag and drop the Social Icons widget inside and fill set the icon and link. Generic icons such as stars or anchors work fine and are displayed normally, but branded icons, such as Facebook, Twitter, etc., are broken.

However, if you change the <i> tag's class attribute in the html code, the icons come back!

`<i class="fa fa-facebook"></i>`
to
`<i class="fab fa-facebook-f">` 

So in my case I copied the entire html div for the Social Icons widget, corrected the class attributes, and pasted it in a HTML Widget.

## Isolating the problem

- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v5.5.59-MariaDB-38.11
	PHP Version: 7.0.32
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: https://www.caddmicrosystems.com/community
	Home URL: https://www.caddmicrosystems.com/community
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: CADD Microsystems GP
	Version: 0.1
	Author: Donnie Gladfelter
	Child Theme: Yes
	Parent Theme Name: GeneratePress
	Parent Theme Version: 2.1.4
	Parent Theme Author: Tom Usborne

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0

== Active Plugins ==
	AceIDE
		Version: 2.6.2
		Author: AceIDE

	Add From Server
		Version: 3.3.3
		Author: Dion Hulse

	Advanced Custom Fields PRO
		Version: 5.7.7
		Author: Elliot Condon

	Advanced Database Cleaner
		Version: 2.0.0
		Author: Younes JFR.

	Akismet Anti-Spam
		Version: 4.0.8
		Author: Automattic

	CADD Community
		Version: 1.0
		Author: Donnie Gladfelter

	Code Snippets
		Version: 2.12.0
		Author: Shea Bunge

	Display All Image Sizes
		Version: 1.1.6
		Author: Press Up

	Divi Builder
		Version: 2.0.54
		Author: Elegant Themes

	Duplicate Post
		Version: 3.2.2
		Author: Enrico Battocchi

	Easy Theme and Plugin Upgrades
		Version: 2.0.1
		Author: Chris Jean

	Elementor
		Version: 2.2.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.0.13
		Author: Elementor.com

	Enhanced Media Library
		Version: 2.7.2
		Author: wpUXsolutions

	Enhanced Text Widget
		Version: 1.4.6
		Author: Boston Dell-Vandenberg

	Google Analytics Dashboard for WP (GADWP)
		Version: 5.3.5
		Author: ExactMetrics

	GP Premium
		Version: 1.7.2
		Author: Tom Usborne

	Imagify
		Version: 1.8.3
		Author: WP Media

	Jetpack by WordPress.com
		Version: 6.6.1
		Author: Automattic

	Lightweight Grid Columns
		Version: 1.0
		Author: Tom Usborne

	Post Type Switcher
		Version: 3.1.0
		Author: John James Jacoby

	Redirection
		Version: 3.5
		Author: John Godley

	Server Status
		Version: 1.3.2
		Author: LittleBizzy

	SiteOrigin CSS
		Version: 1.2.3
		Author: SiteOrigin

	Social Icons Widget by WPZOOM
		Version: 3.0.11
		Author: WPZOOM

	VaultPress
		Version: 1.9.6
		Author: Automattic

	WooCommerce
		Version: 3.4.6
		Author: Automattic

	WP All Export Pro
		Version: 1.5.3
		Author: Soflyy

	WP Rocket
		Version: 3.1.4
		Author: WP Media

	WP Rocket | No Cache for Admins
		Version: 
		Author: WP Rocket Support Team

	WP Rocket | Redirect HTTP to HTTPS
		Version: 
		Author: WP Rocket Support Team

	Yoast SEO
		Version: 8.4
		Author: Team Yoast


== Debug ==
	Errors: 
		TypeError: setting getter-only property "type"
			at https://www.caddmicrosystems.com/community/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.7 - 2:86630
			2018-10-25 18:22 +00:00

		TypeError: this.ui.select is undefined
			at https://www.caddmicrosystems.com/community/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.5 - 2:76855
			2018-07-27 15:45 +00:00

		TypeError: this.ui.select is undefined
			at https://www.caddmicrosystems.com/community/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.1 - 2:76762
			2018-07-05 04:19 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at https://www.caddmicrosystems.com/community/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.8 - 2:132926
			2018-05-02 02:32 +00:00
			x 7 times

		TypeError: this._parent is undefined
			at https://www.caddmicrosystems.com/community/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.8.11 - 2:114375
			2018-01-02 20:02 +00:00
			x 2 times

		TypeError: Cannot read property 'errors' of undefined
			at https://www.caddmicrosystems.com/community/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.11 - 2:110752
			2017-10-16 16:14 +00:00
			x 2 times

		TypeError: elementor.getPanelView(...).getCurrentPageView(...).showView is not a function
			at https://www.caddmicrosystems.com/community/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=1.9.3 - 2:16540
			2017-10-16 16:03 +00:00

				
```
</details>

**Comment by bainternet** [comment] 2018-11-01 08:39
Duplicate of #4430

**Closed by bainternet** 2018-11-01 08:39 UTC
