### ISSUE TITLE
[Feature Request] Default settings within Elementor.

### ISSUE THREAD

**Issue by nickdgreen** [pojome/elementor#4321] opened 2018-05-02 09:45 UTC
With the implementation of Elementor Header and Footer much of a theme's functionality is not required and there is the potential to used Elementor's minimal Hello Theme. This is, however, a bit too 'thin' as there is then no ability (other than using CSS) to set defaut settings for:

- body default font, size and colour
- headings (h1, h2, etc.) default font, size and colour
- default link setting normal, hover and visited
On the Elementor Settings if the Disable Default Colours and Disable Default Fonts are not 'checked' then the options shown above should be available for configuration.

**Comment by bainternet** [comment] 2018-05-02 10:45
Duplicate of #3345

**Closed by bainternet** 2018-05-02 10:45 UTC
Labels: request/feature
