### ISSUE TITLE
Feature Request: Slideshow background / Carousel background / Zoom In/Out background

### ISSUE THREAD

**Issue by Thotti79** [pojome/elementor#4022] opened 2018-04-07 22:23 UTC
In the Visual Composer Website Builder they do offer the features Slideshow background / Carousel background / Zoom In/Out background. It would be nice, if you could add these options in Elementor (Pro) too, because right now i have a Client, who needs exactly these feature(s).
Thanks

**Comment by bainternet** [comment] 2018-04-08 06:25
Duplicate of #2898

**Closed by bainternet** 2018-04-08 06:25 UTC
