### ISSUE TITLE
How to remove the white bar in the header?

### ISSUE THREAD

**Issue by oto-xara** [pojome/elementor#792] opened 2016-11-02 20:59 UTC
How to remove the white bar in the header?
http://prnt.sc/d2b8r3

**Comment by agusmu** [comment] 2016-11-03 05:42
It is only for editing purpose. The white bar is visible to give some space to edit the top section. 

Check this screenshot, http://prntscr.com/d2ftl9

If you check the final result, the white bar will disappear.

**Comment by oto-xara** [comment] 2016-11-03 09:33
Aha, after installing the update this bug is gone!)

**Comment by oto-xara** [comment] 2016-11-03 10:12
it looks like this
http://prntscr.com/d2i8qh
http://prntscr.com/d2i9s3
this band is in the header and bottom also
http://prntscr.com/d2ia2i

before
http://prntscr.com/d2ib1d
after disabling  height: 21px; it's OK. Why?
http://prntscr.com/d2ibpu

**Comment by WPDevHQ** [comment] 2016-11-04 08:21
That looks like its coming from your theme and not Elementor

**Comment by oto-xara** [comment] 2016-11-04 10:35
I use default theme Twenty Sixteen, and what better to use?

**Comment by WPDevHQ** [comment] 2016-11-04 13:55
Try the helper plugin [Elementor Templater](https://wordpress.org/plugins/elementor-templater/)

Or you can switch to the [GeneratePress](https://wordpress.org/themes/generatepress/) theme - probably one of the best themes out there.

**Comment by oto-xara** [comment] 2016-11-04 15:05
I use plugin Elementor Templater, it does not remove the white bar.

changed theme to the  GeneratePress, appeared a white stripe with the page title

http://prntscr.com/d310rn
http://prntscr.com/d312bi

**Comment by dasigna** [comment] 2016-11-04 16:40
... just out of interest: is this also appearing when viewing the site in frontend??
empty white space may be just an elementor-preview thing...

but agree to WPDevHQ - this likely seems to be a theme thing. title appears as long as not disabled somewhere. but its strange anyway, as from your screens it seems you're building up a page without header (or header content) and menu created in elementor? so only to guess if that white space might be som persisting 'div' or else from the header ... ??? only guessing while not seeing whats going on around.
but anyway - quite shure no elementor-issue.

**Comment by WPDevHQ** [comment] 2016-11-04 17:54
With GeneratePress you can disable the title on per page basis

**Comment by oto-xara** [comment] 2016-11-05 08:41
@dasigna Yes, this also appears when viewing the site in a web interface.

when I install the plugin Elementor on the default any template, this band is in the header and footer

**Comment by dasigna** [comment] 2016-11-05 14:50
hmm...

if using generatepress and already deactivated header and page title i dont have any other clue, because i cant replicate this on local test enviroment. in my case everything behaves as intended.

so i fear the only possibility to solve this might be a closer look on your website or even better to your backend.
any chance for a link to staging version at least?

**Comment by spatialy** [comment] 2016-11-06 02:11
same issue here ... any theme I try.

**Comment by WPDevHQ** [comment] 2016-11-06 13:42
Can we please have links so that we can see what is causing the issue and be able to offer the best solutions?

**Comment by oto-xara** [comment] 2016-11-06 17:29
Sorry it took so long..

View it

http://www.law-craft.com/elementortest/

I use theme Twenty Sixteen, plugin Elementor and Elementor Templater

**Comment by oto-xara** [comment] 2016-11-06 17:31
I can give access to the admin

**Comment by WPDevHQ** [comment] 2016-11-07 00:25
Please update the Elementor Templater plugin to the latest version which should resolve the issue.

Don't forget to post back here if resolved and close this ticket.

**Comment by oto-xara** [comment] 2016-11-07 08:22
This helped! Thank you very much!)

**Closed** 2016-11-07 08:22 UTC
