### ISSUE TITLE
[Feature Request] Related Posts by Tags or by Categories in Themer

### ISSUE THREAD

**Issue by popsantiago** [pojome/elementor#4589] opened 2018-05-29 12:58 UTC
Hello,

Maybe it can be a good thing to have a Related Posts Widgets in Themer to let us use the current query for Relation like "by Tags" or "by Categories" and cross.
I know i can achieve this with Posts widget and Portfolio widget but i need to select each category or tag and assign the conditionals templates > Boring if we have many cats or tags.

What do you think about that ?

If i can achieve this without new widget, let me know.

Thx

**Comment by bainternet** [comment] 2018-05-29 13:52
Duplicate of #4349

**Closed by bainternet** 2018-05-29 13:52 UTC
