### ISSUE TITLE
Native Table of content feature

### ISSUE THREAD

**Issue by daniboy92** [pojome/elementor#5215] opened 2018-07-25 18:56 UTC
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The problem is TOC+ is not compatible with Elementor, but is compatible with WP native builder. The only way to get a working table of content with this plugin is deactivating the Elementor builder in posts, so the posts have a ugly face.

**Describe the solution you'd like**
Implement a native table of content feature.

**Describe alternatives you've considered**

**Additional context**

**Comment by daniboy92** [comment] 2018-07-25 19:34
Is very frustrating... **NONE of the table of content's plugins that exist right now aren't compatible with Elementor** builder so **there is a clear problem with Elementor...** Tested all kind of plugins for this and NONE of them worked.

**Comment by bainternet** [comment] 2018-07-26 09:41
Duplicate of #5171

**Closed by bainternet** 2018-07-26 09:41 UTC
