### ISSUE TITLE
Hide / display widgets based on page URL queries

### ISSUE THREAD

**Issue by besweeet** [pojome/elementor#6447] opened 2018-12-14 14:54 UTC
For example, a page can have three widgets. If the page URL is examplesite.com/page#video1, only one of those widgets would display while the others would be hidden. If the page URL is examplesite.com/page#video2, a different widget will display while the others would be hidden.

**Comment by bainternet** [comment] 2018-12-16 12:48
Duplicate of #4246

**Closed by bainternet** 2018-12-16 12:48 UTC

**Comment by nicholaszein** [comment] 2024-04-12 06:24
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
