### ISSUE TITLE
Compatibility with WP User Avatar

### ISSUE THREAD

**Issue by arnab0207** [pojome/elementor#4222] opened 2018-04-24 10:00 UTC
Hey!
It will be really nice to have an option to serve "Author Image" in author box option in EPro2 from own server instead of Gravatars. 
Usually, I use a plugin called "WP User Avatar" to achieve this. 
However, Epro2.0 doesn't support it :( 
Any other workaround?

**Comment by bainternet** [comment] 2018-04-24 14:30
Duplicate of #3757

this: https://github.com/pojome/elementor/issues/3757#issuecomment-373319396
still applies

**Closed by bainternet** 2018-04-24 14:30 UTC
