### ISSUE TITLE
Parallax background

### ISSUE THREAD

**Issue by Agam6130Haim6130** [pojome/elementor#5050] opened 2018-07-13 16:03 UTC
Hi!

Is it possible to add a 'Parallax Background Scroll' option for Sections & Columns, other than the basic "scroll" and "fixed"?

Many of my clients wants that feature and neither 3rd party addon make it right (I'm working with JetParallax & Element Pack by BDThemes).
It will be wonderful... Parallax is so popular and beautiful and I'm sure you can do it

If you can't add this feature, maybe you can tell your users how it can be achieved with JS or CSS or something?

Thanks a lot!
--

**Comment by bainternet** [comment] 2018-07-15 07:51
Duplicate of #72

**Closed by bainternet** 2018-07-15 07:51 UTC
