### ISSUE TITLE
Table of contents plus not working

### ISSUE THREAD

**Issue by cedri7c** [pojome/elementor#2344] opened 2017-09-07 19:38 UTC
The plugin is still not working with Elementor, 
if you add a shortcode and type [toc] (the comment for displaying a table of content) it doesn't show anything.
If you use the Toc+ widget it displays on Elementor but it doesn't display the table of content on the live site.

**Comment by arielk** [comment] 2017-09-08 08:17
Duplicate of #2248 

Please let's continue the conversation there.

Thanks.

**Closed by arielk** 2017-09-08 08:17 UTC
