### ISSUE TITLE
STILL NOT FIXED - Background images in sections set to Cover

### ISSUE THREAD

**Issue by kadoogan55** [pojome/elementor#1128] opened 2017-01-07 19:18 UTC
This has been requested by myself and others to be fixed several times but continues to be ignored:

Images in sections that are set to COVER mode wind up zooming in a tremendous amount instead. Not sure if it works on other phones or tablets but does not work on iOS devices properly.

Should I try a different section background type other than Cover? I have tried all those and they do not work properly either - in fact they have issues of their own including unwanted duplication of the background image (another issue that needs looking at).

It is not particular to just my sites - others have been complaining about the same issue both on Github and on the Elementor Facebook page.

So, it is not a problem I am causing due to themes or other plugins conflicting, but rather a problem with Elementor. Again, I do not have the issue with Beaver Builder or Live Composer, so it again leads to Elementor being the issue.

It will happen with any test you create yourself. Or on any existing site you have created with that section background setting. You don't need any further outside input to recreate the problem and fix it.

So please fix it for God's sake. This has been going on for weeks.

**Comment by drawcard** [comment] 2017-01-08 04:58
You should be mindful that there are 127 open issues at the moment, not to mention the devs have been working all through the holiday season to get stuff fixed in Elementor. Showing a little patience and courtesy will go a long way.

Maybe posting (or referencing) a proper issue report, showing us your exact setup and enabled themes / plugins is a start. Then we can see if there's some correlation among all the cases to help eliminate the cause. 

If there's still not enough action on it, you can always investigate the problem yourself in the source code and publish a pull request too. It is open source software after all.

**Comment by arielk** [comment] 2017-01-08 09:29
The problem is with the definition of `background-attachment: fixed;` that not working perfectly on mobile.

Anyway, we're working on this issue, you can follow here: #890

**Closed by arielk** 2017-01-08 09:29 UTC
