### ISSUE TITLE
Custom Fields in Posts/Archive Widget

### ISSUE THREAD

**Issue by kristiangl** [pojome/elementor#5846] opened 2018-10-04 00:11 UTC
This was previously outlined in Issue #1071 (https://github.com/pojome/elementor/issues/1071) however that issue was closed without implementation or explanation. 

We would like to be able to add custom field data to the Posts and Archive widget. 

Ideas about implementation have been outlined in the original issue by multiple people.

**Comment by bainternet** [comment] 2018-10-04 07:33
Duplicate of #4440

**Closed by bainternet** 2018-10-04 07:33 UTC
