### ISSUE TITLE
Background Function Improvement: Blur slider

### ISSUE THREAD

**Issue by steveamazing** [pojome/elementor#4298] opened 2018-04-29 18:38 UTC
## For all hoeverover, column/section backround & background overlay Images, shading, gradient, can you add the CSS sliders you have for the Call to Action?   These are create tools that could be used everywhere for background images and colors

EXAMPLES OF BLURR BACKGROUNDS https://designmodo.com/blur-backgrounds-websites/

BLUR ON HOVER OVER: https://www.youtube.com/watch?v=W0ubfqwd4G4

**Comment by bainternet** [comment] 2018-04-30 16:04
Duplicate of #2896

**Closed by bainternet** 2018-04-30 16:04 UTC
