### ISSUE TITLE
Media carousel starting position

### ISSUE THREAD

**Issue by boostercb** [pojome/elementor#4446] opened 2018-05-14 15:11 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Is there an option to get the Media Carousel widget to start from the first item on the page vs. the center of the array? We have a page that loads a Netflix-like series of episodic videos and we want the row to always start with the first episode, not the middle of the total number of items in the carousel.

**Describe the solution you'd like**
Ability to choose the build order as it renders on the page.

**Describe alternatives you've considered**
Would have to rebuild our page without this widget if it is not possible with Elementor's native capabilities.

**Comment by bainternet** [comment] 2018-05-15 09:49
Duplicate of ##3187

**Closed by bainternet** 2018-05-15 09:49 UTC
