### ISSUE TITLE
Sticky Header - Page Jumps/ Internal Anchor Links - Header Overlaps

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#2944] opened 2017-12-13 13:03 UTC
This issue was flagged but closed, however support has confirmed on checking that its an valid issue, so reopening the original issue here.
https://github.com/pojome/elementor/issues/2928

Demo can be seen here for the problem:
https://www.dentalicious.com.au/dummy-page-jumps/

This is what support says:
"Elementor plugin doesn't provide any sticky elements, so it's unexpected a bit that the sticky menu will hide the anchor title. I think once we will add the sticky menu option in Elementor we will have to deal and fix this thing with the anchors as well. "

The issue:
Page-Jumps(or Internal Anchor Links) with sticky headers on scroll are currently not doable, as page jumps to the middle of the section and the headers overlap, a custom css has got to be used, all the other elements to create page jumps are there, just a section where negative height can be put is missing and would be awesome to have and would save a ton of time.

For a non coder like me, I struggled 03 days to find this simple custom css,
h2::before {
display: block;
content: " ";
margin-top: -150px;
height: 150px;
visibility: hidden;
pointer-events: none;
}

It still messes up with sections below and above and editing becomes a pain.
If spacers or padding are used with anchor menu widget then blank spaces on front end get created.

Kindly consider it as a feature enhancement if possible, many people like me would be well served and love working with elementor more without worrying about codes.

**Comment by bainternet** [comment] 2017-12-13 14:15
@Dentalicious 

First of Sticky header is already considered as a valid feature request #2412.

Now that we got that out of the way the reason for the sections overlapping is known to you and it is the use of custom CSS (margin-top: negative-value).

So you may "FIX" one problem but creates a different one (when editing as you can see). 

Another thing to know is that an anchor is something native to HTML and browser behavior, and not something controlled or defined by Elementor.

Closing this as a duplicate of #2412, which is now referenced in the original request and next time, please feel free to reopen any issue you submit here (reopen not a new one).

Thanks for your feedback and suggestion.

**Closed by bainternet** 2017-12-13 14:15 UTC
