### ISSUE TITLE
Internet Explorer Border Separator shows as mirrored

### ISSUE THREAD

**Issue by stickypages** [pojome/elementor#3484] opened 2018-02-14 21:56 UTC
I have a screenshot here that shows the same site, but it appears reversed in "EDGE" browser. Not sure the best way to debug that. 

![2018-02-14 13_52_51-microsoft edge](https://user-images.githubusercontent.com/658488/36230283-ca608976-118e-11e8-8198-a4fed8fba27a.png)

**Comment by bainternet** [comment] 2018-02-15 07:55
Duplicate of #2683 
https://github.com/pojome/elementor/issues/2683#issuecomment-342076015

**Closed by bainternet** 2018-02-15 07:55 UTC

**Comment by stickypages** [comment] 2018-02-15 16:52
Didn't see, thanks!
