### ISSUE TITLE
[FEATURE REQ] Different frontend sections for loggend in and logged out users

### ISSUE THREAD

**Issue by teolaz** [pojome/elementor#5971] opened 2018-10-23 10:07 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

## Request

After inspecting a while, it seems the plugin https://wordpress.org/plugins/woorocks-magic-content/ break new versions of Elementor.
Is it possible to have the same feature integrated in Elementor? Can be also a good marketing strategy, as your login widget is available only on Pro version.
Please tell me if this could be interesting, i can check if i can develop and PR, but only if you're sure to merge it.

**Comment by bainternet** [comment] 2018-10-23 14:18
Duplicate of #4246

**Closed by bainternet** 2018-10-23 14:18 UTC

**Comment by teolaz** [comment] 2018-10-25 15:47
Gonna leave this here:
https://github.com/teolaz/elementor-login-protected-sections

**Comment by nicholaszein** [comment] 2024-04-12 06:14
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
