### ISSUE TITLE
Background Image Attachment Fixed on Chrome 67+

### ISSUE THREAD

**Issue by anggaerlsa** [pojome/elementor#4719] opened 2018-06-11 09:12 UTC
Hi,

I found an issue with Elementor 2.0.15. The background image attachment fixed is not work properly. The images not shown (except I add z-index to the section). But z-index not help much, the image seems to be broken at the start of section padding.

Hope you will provide an update for this issue.

Cheers :)

**Comment by bainternet** [comment] 2018-06-11 12:17
Duplicate of #4692

**Closed by bainternet** 2018-06-11 12:17 UTC
