### ISSUE TITLE
[Bug] Image Box - Image Spacing on mobile

### ISSUE THREAD

**Issue by kaelmawn** [pojome/elementor#2549] opened 2017-10-04 15:46 UTC
On the Image Box Widget, the Image Spacing on mobile is not working with Image Position to Left or Right. 

The bug is happening because the Image Position is always showing as "top" on mobile, which doesn't apply the margin on the right side on mobile.

**Comment by lamiastartup** [comment] 2017-10-13 20:23
Same here :(

**Comment by arielk** [comment] 2017-11-07 19:58
Duplicate of #2586

**Closed by arielk** 2017-11-07 19:58 UTC
