### ISSUE TITLE
svg with link 

### ISSUE THREAD

**Issue by avioctavo** [pojome/elementor#6882] opened 2019-01-25 12:16 UTC
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by avioctavo** [comment] 2019-01-25 12:19
svg placed in image widget make it smaller when i define URL link for it.
why dos it happens?

**Comment by JoeDarko** [comment] 2019-01-26 06:32
#6136

They were trying to solve some edge case by applying width to SVG with link. It's ridiculous, they may've solved some edge case, but caused global problem.

**Comment by shilo-ey** [comment] 2019-01-27 14:57
I merged this issue with  #6136, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by shilo-ey** [comment] 2019-01-27 14:57
Duplicate of #6136

**Closed by shilo-ey** 2019-01-27 14:57 UTC
