### ISSUE TITLE
Nested inner section

### ISSUE THREAD

**Issue by manektechmayank** [pojome/elementor#6917] opened 2019-01-30 10:09 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It will solve the complex layout like below.
if you allow nesting "inner section" then it will solve the complex layout like below. Which currently, we can't do.
![image](https://user-images.githubusercontent.com/31854318/51973842-95ebb600-24a4-11e9-91b5-eaa6efeb9dd9.png)

**Describe the solution you'd like**
I want the ability of adding nesting "inner section" into the same column.

**Describe alternatives you've considered**
I have added a "text editor" widget and created two column by inserting inner style.

**Additional context**
This is what I want to do.

![image](https://user-images.githubusercontent.com/31854318/51973979-e3682300-24a4-11e9-9e10-c45128d4cc88.png)

**Comment by bainternet** [comment] 2019-01-30 13:40
Duplicate of #2587

**Closed by bainternet** 2019-01-30 13:40 UTC

**Comment by nicholaszein** [comment] 2023-01-11 17:07
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.6** and is now a stable experiment since v3.8 as the Flexbox Container! 🥳 

By default, the Container tag is a Div, but you can also change the tag to many other values, including anchor `<a>` tags.

You can learn more about the Flexbox Container [here](https://elementor.com/help/what-is-a-container/).

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
