### ISSUE TITLE
Folder categorization and organization for templates

### ISSUE THREAD

**Issue by jazir5** [pojome/elementor#5796] opened 2018-09-25 03:34 UTC
It would be nice to be able to group templates inside folders to both make them easier to find as well as reduce the number of pages and clutter in my template library.

**Comment by mylimoproject** [comment] 2018-09-25 04:29
+100
This is a must for many of us until Elementor implements the overdue "Widget within Widget" function.
In my example,  I do have to create a "content page template" so I am able to insert shortcode into the TABS Widget. Therefore, if widget has 5 tab, I do have to create 5 templates (if needed for 120 pages = 600).  
**TABS Widget live example** => https://airportspickup.com/ctlimorentals-carserviceavonct-taxi-bdl-ewr-lga-jfk-airportshuttle/

![template folder](https://user-images.githubusercontent.com/29313121/45992874-f16ee880-c059-11e8-901d-17d3cae004ea.JPG)

**Comment by jazir5** [comment] 2018-09-25 04:39
![my templates](https://user-images.githubusercontent.com/31750063/45993158-4bfc4a80-c042-11e8-955e-26d9b7a0548f.png)

I am referring to the my templates section

**Comment by mylimoproject** [comment] 2018-09-25 04:59
@jazir5 
Exactly.. and I am offering a live example of why the organization tree is needed. 
For instance, I will need to create 600 templates (5 per city). In this example, will be doing 25 cities located in Connecticut State USA.
_**My Templates/UberCompare/State/Cities**_
But honestly, I am holding off and hiding the TABS block hoping for an easier and faster solution (widget within widget would be great if ever added to Elementor).

![template folder2](https://user-images.githubusercontent.com/29313121/45993645-d9996380-c05d-11e8-941e-29e628f50640.JPG)

**Comment by jazir5** [comment] 2018-09-25 05:01
This would really be a nice QOL change.

**Comment by bainternet** [comment] 2018-09-25 06:49
Duplicate of #886

for now you can use https://wordpress.org/plugins/builder-template-categories/

**Closed by bainternet** 2018-09-25 06:49 UTC

**Comment by jazir5** [comment] 2018-09-25 11:50
That was a ticket submitted two years ago, this seems like incredibly basic
functionality. Why isn't this being added?
