### ISSUE TITLE
[PRO filter request] - Ability to override the post widgets wp_query to select multiple CPTs

### ISSUE THREAD

**Issue by jokr0815** [pojome/elementor#4063] opened 2018-04-11 10:23 UTC
Hi,

thanks for implementing #2109  

Unluckiliy it seems we can select only a single CPT. 
I would like to select multiple CPTs and see it in the Output.

Additionally I do not see the Event post_type in the Dropdown.
But when I add a filter to modify the query on the static post page (is_home) e.g., I can see it.

`$query->set( 'post_type', array( 'post', 'bericht' , 'event') );`

Thanks and kind regards
Jo

**Comment by arielk** [comment] 2018-04-29 17:50
Duplicate of https://github.com/pojome/elementor/issues/1748

**Closed by arielk** 2018-04-29 17:50 UTC
