### ISSUE TITLE
[BUG] No Screen Options on Pages and Post after last update of E Pro

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3659] opened 2018-03-05 04:18 UTC
After some of the last updates of Elementor Pro there is no Screen Options button on Pages, Posts and CPTs admin pages. Not sure when this happened, byt it's OK on version 1.13.2 on one of my old dev installs.

See the screenshot below - on the top there is Posts admin page with E Pro activated, below with E Pro deactivated (sorry for the localization, but I think it's clear enough even in Czech):

![obrazek](https://user-images.githubusercontent.com/5634870/36957248-63d0406c-2033-11e8-9278-22b90622fe20.png)

**Comment by bainternet** [comment] 2018-03-05 07:23
Duplicate of #3622

**Closed by bainternet** 2018-03-05 07:23 UTC
