### ISSUE TITLE
SearchReplaceDB doesn't work on images URLs because of domain stored in JSON

### ISSUE THREAD

**Issue by laurentvergnaud** [pojome/elementor#740] opened 2016-10-18 09:34 UTC
Hello there! 

I am the co-founder of Themecloud.io and we use more and more Elementor to offer easy to use templates to our users. So first of all,  huge thanks for the great work :-)

## Description

We are facing a huge issue since the last update. It seems that you store the complete URLs of the images in JSON
So when we duplicate or migrate a website the URLs of the images are not modified with the new domain.
This problem is critical for Themecloud but also for anyone using migration plugins or stuff like that. 
## Steps to reproduce
1. Create a website using images added through Elementor.
2. Migrate the website on an other domain using SearchReplaceDB script or a plugin like MigrateDB Pro.
3. Check the URLs of the images, they haven't been migrated.

## Environment

== Server Environment ==
    Operating System: Linux
    Software: nginx/1.8.1
    MySQL version: 5.5.5
    PHP Version: 5.6.24-0+deb8u1
    PHP Max Input Vars: 1000
    PHP Max Post Size: 100M
    GD Installed: Yes
    Elementor Library: connected

== WordPress Environment ==
    Version: 4.6.1
    Site URL: http://testgalery.mythemecloud.io
    Home URL: http://testgalery.mythemecloud.io
    WP Multisite: No
    Max Upload Size: 100 MB
    Memory limit: 40M
    Permalink Structure: /%postname%/
    Language: en-US
    Timezone: 0
    Admin Email: laurent@noadmin.io
    Debug Mode: Inactive

== Theme ==
    Name: West
    Version: 1.11
    Author: aThemes
    Child Theme: No

== User ==
    Role: administrator
    WP Profile lang: en_US
    User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

== Active Plugins ==
    Caldera Forms
        Name: Caldera Forms
        Version: 1.4.3.1
        Author: CalderaWP

```
Contact Form 7
    Name: Contact Form 7
    Version: 4.5.1
    Author: Takayuki Miyoshi

Contact Form DB
    Name: Contact Form DB
    Version: 2.10.24
    Author: Michael Simpson

Easy HTTPS (SSL) Redirection
    Name: Easy HTTPS (SSL) Redirection
    Version: 1.5
    Author: Tips and Tricks HQ

Elementor
    Name: Elementor
    Version: 0.10.2
    Author: Elementor.com

Elementor Addon Widgets
    Name: Elementor Addon Widgets
    Version: 1.0.2
    Author: WPDevHQ

Force Regenerate Thumbnails
    Name: Force Regenerate Thumbnails
    Version: 2.0.6
    Author: Pedro Elsner

Jetpack by WordPress.com
    Name: Jetpack by WordPress.com
    Version: 4.3.1
    Author: Automattic

Nimble Portfolio
    Name: Nimble Portfolio
    Version: 2.1.6
    Author: Nimble3

Regenerate Thumbnails
    Name: Regenerate Thumbnails
    Version: 2.2.6
    Author: Alex Mills (Viper007Bond)

Unplug Jetpack
    Name: Unplug Jetpack
    Version: 0.1.1
    Author: Tanner Moushey

Widget Content Blocks
    Name: Widget Content Blocks
    Version: 2.3.6
    Author: Danny van Kooten

WordPress Database Reset
    Name: WordPress Database Reset
    Version: 3.0.2
    Author: Chris Berthe

WordPress Importer
    Name: WordPress Importer
    Version: 0.6.3
    Author: wordpressdotorg
```

== Must-Use Plugins ==
    themecloud.php
        Name: themecloud.php
        Version: 
        Author:

**Comment by KingYes** [comment] 2016-10-20 07:11
Hi @laurentvergnaud 

You right. But if you want to replace in JSON format, please find your domain in Elementor Data, and copy the domain (with slashes), and replace this with the new one (with slashes too).

**Comment by asiragusa** [comment] 2016-10-20 07:58
Hi @KingYes this feature potentially adds a BC with many domain migration plugins.

I think that the best solution would be to strip the domain name from the JSON and leave just the absolute path.

Btw this would reduce the page size too.

**Comment by BoweFrankema** [comment] 2016-10-26 09:14
This is a big issue and I hope it gets fixed. Having hard coded domains URLs outside of the database is a big issue for doing migrations or when deploying containers (as brought up by @laurentvergnaud). Ideally you'd use get_site_url(); after parsing the JSON file to append the proper domain name instead of hardcoding it :-)

**Comment by asiragusa** [comment] 2016-10-26 14:54
@BoweFrankema using get_site_url() is not even useful, as browsers do understand absolute paths. Hardcoding URLs in the database, or returning urls with scheme and domain, is a bad practice and should be fixed sooner or later in WP...

**Comment by BoweFrankema** [comment] 2016-10-26 15:23
@asiragusa absolute paths should also not be added to files generated by Elementor. The problem is not related to browser or url formatting. The problem is that the JSON files can not be modified via a Search and Replace plugin because they are saved as actual files outside of reach of any Search and Replace plugin/script. This breaks images on site migrations.

So the file/image path should be relative to the /uploads or any other sensible WordPress directory url. 

So in the exported JSON file by elementor the path would be:

````
  "url": "/2015/13/image.jpg",
````

Then when that JSON is imported/exported the import script used by Elementor would take the wordpress upload path to prefix that.

**Comment by asiragusa** [comment] 2016-10-26 15:40
@BoweFrankema yep I have read the source code, and I know that the problem is the JSON serialization in the DB. Returning scheme and domain in HTML can be avoided and should be done whenever possible.

**Comment by mikegriffinn** [comment] 2016-11-04 14:20
Is there any update on this? I'm running into this issue on client site mgrations.

**Comment by talesg** [comment] 2016-12-06 05:10
Ops, just run into this problem. Very unpractical to replace one by one.

**Comment by JoelEadeDesign** [comment] 2016-12-15 02:20
Following. This is a major issue for me as well.

**Comment by pingram3541** [comment] 2017-01-05 19:06
I also agree the paths should be stored with relative paths, not absolute.

**Comment by jeffreybetts** [comment] 2017-01-12 03:28
Agreed as well. I just ran into this issue when using BackupBuddy or Duplicator for site migrations and noticed that images on my pages/posts had broken links that were referencing the local environment.

**Comment by JoelEadeDesign** [comment] 2017-01-12 03:54
This issue is resolved (somewhat) by the release v1.1.0, which has a Replace URL feature – https://elementor.com/v110-revision-history/. I'm yet to test it though.

**Closed** 2017-01-12 06:03 UTC
Labels: enhancement

**Comment by torndownunit** [comment] 2018-02-10 04:46
I just ran into this issue migrating a site, and found this thread.  I fail to see how the link posted https://elementor.com/v110-revision-history/ explains any sort of fix for this.  Am I missing something?

**Comment by JoelEadeDesign** [comment] 2018-02-10 04:54
Hi,

Refer to the "Replace URL” section of the article. Enter your old URL (e.g. http://localhost/website) and the new URL in the respective fields. Be sure to add forward-slashes to the end of both URLs. I forgot to add it to one and not the other in the past and it was a pain to fix. To be safe, back up your database first.

Hope that helps.

**Comment by DanielMesteru** [comment] 2018-03-01 15:50
Hello,

I still have this problem. "Replace URL" section from Elementor settings doesn't work, it returns 0 results (tried with forward-slashes ofc). 
For me the problem is with images, they don't show. If I go to the Elementor section and I click update, it works. 

Migrating form XAMPP + Elementor latest version/WOO latest/WP latest/OceanWP latest to a new server. All other elements works. 

Any ideas? One by one isn't a solution...

**Comment by mikegriffinn** [comment] 2018-03-01 16:06
Yes. I've recently started having the same problem with images. I saw it yesterday migrating a client from http to https.

**Comment by Artneo7** [comment] 2018-07-19 12:30
Hello! I also have the same problem when migrating to another domain. I keep manually selecting the images again with the correct URL. Any solution to this?
