### ISSUE TITLE
Responsive Devices

### ISSUE THREAD

**Issue by Boffice** [pojome/elementor#5890] opened 2018-10-10 10:09 UTC
- Please create GitHub issues only for bugs and feature requests. GitHub issues ARE NOT FOR SUPPORT!

- If you have questions or need general support,  Please use:  https://wordpress.org/support/plugin/elementor 

- For help and support from the Elementor community, see: https://www.facebook.com/groups/Elementors/

- To read more about Elementor, check out our documentation: https://docs.elementor.com

- Developers docs are located at: https://developers.elementor.com/

**Comment by Boffice** [comment] 2018-10-10 10:14
Hello, 

Currently by default elementor responsive options supports PC , Tablet and Mobile phone devices. 
Wonder how to add custom devices to the list like Notebook screen. 

Also wonder if there is any setting to shrink or expand the page on full size and avoid the scroll bar.

**Comment by bainternet** [comment] 2018-10-10 10:27
Duplicate of #2043

**Closed by bainternet** 2018-10-10 10:27 UTC

**Comment by Boffice** [comment] 2018-10-10 10:39
> Duplicate of #2043

Above topic is linked to orientation, what i need is just simple different screen size.
