### ISSUE TITLE
I can not apply a tag <!--nextpage--> to divide the post into pages by html-code widget

### ISSUE THREAD

**Issue by mitus66** [pojome/elementor#5003] opened 2018-07-09 08:39 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mitus66** [comment] 2018-07-09 08:41
Hi, I can not apply a tag  to divide the post into pages by html-code widget. Elementor created a pagination but has been duplicating the content before and after this tag.
I think the work of these tags ( <!- -more- ->, <!- -noteaser- -> and <!- -nextpage- -> ) is as natural as breathing.

**Comment by bainternet** [comment] 2018-07-09 09:09
Duplicate of #462

**Closed by bainternet** 2018-07-09 09:09 UTC
