### ISSUE TITLE
override css files path

### ISSUE THREAD

**Issue by sandromattei** [pojome/elementor#4271] opened 2018-04-27 13:21 UTC
Hallo and sorry for my english.
i use Elementor on multisite with 2 websites who share same uploads folder.
every Elementor css file is named like post-29.css, post-43.css etc. etc.
Is possible to add website id on name of css file (example post-1-43.css or post-2-29.css)?
This because multisite posts  could have the same ID.
Thank's a lot

**Comment by bainternet** [comment] 2018-04-29 11:47
Duplicate of #3553

**Closed by bainternet** 2018-04-29 11:47 UTC
