### ISSUE TITLE
Image carousel multiple custom URLs

### ISSUE THREAD

**Issue by brianroach** [pojome/elementor#216] opened 2016-07-06 17:22 UTC
I'm building a carousel with multiple event fliers that each should link to a specific event page, but can't seem to add custom links for each image. Is this possible already and I'm just missing something? I didn't see anything in the docs.

**Comment by yehudah** [comment] 2016-07-10 08:39
Hi,

Hope to add in in future release.

**Comment by lunacroft** [comment] 2016-07-16 22:52
Me too! But mine is partner carousel with images and individual partner url. Carousel and Gallery could have separate url per image.

**Comment by brianroach** [comment] 2016-07-28 16:30
@lunacroft pretty much exactly what I'm thinking. 😄  👍

**Comment by heddesheimer** [comment] 2016-09-18 16:20
+1 from me too.

**Comment by hansnolte** [comment] 2016-10-26 14:55
As lunacroft has already said...
"Carousel and Gallery could have separate url per image."

**Comment by mediaworksmt** [comment] 2016-10-27 20:20
I'm also hoping to see this feature in the future! :-) 

For now, here's an extremely quick & dirty work-around:

1. Open **/wp-content/plugins/elementor/includes/widgets/image-carousel.php** and replace the code inside with [the code from this attached .TXT file.](https://github.com/pojome/elementor/files/556920/image-carousel.txt)

2. When adding/editing the **Image Carousel** element in Elementor, set **Link to** to Custom URL. Then in the field that appears, enter each of your URLs, separated by a commas. (NO SPACES.)

PLEASE NOTE that if you update Elementor, these code changes will get overwritten, so you'll need to once again replace the **image-carousel.php** file.

I hope to contribute a more elegant solution in the near future.

**Comment by LDX1** [comment] 2017-02-13 18:51
Should we continue to do this with the @mediaworksmt work around or is there a chance to see it in a future release?
thanks

**Comment by subrato312** [comment] 2017-02-25 16:39
Sorry I am new to this but there is no elementor/includes/widgets/image-carousel.php

**Comment by JoelEadeDesign** [comment] 2017-03-08 02:17
+1 

This feature/issue has just come up on a client project. My client wants their staff shown in an image carousel on the home page, with each image linking to their own URL i.e. an anchor tag on the staff page.

**Comment by uchsarath** [comment] 2017-03-23 09:47
I am totally need this, look like the request made since July last year. 👍  likely help to work on this.
Thanks,

**Comment by salvimateus** [comment] 2017-03-23 18:20
Please do this functionality, it is very much needed. The plugins that do this, have ugly design. Even if it is a "pro" feature.

**Comment by JoelEadeDesign** [comment] 2017-03-23 23:32
I have a jQuery work-around if anyone wants it.

**Comment by WPDevHQ** [comment] 2017-03-24 07:02
@JoelEadeDesign - Please share :)

**Comment by JoelEadeDesign** [comment] 2017-03-30 02:23
Hello! Apologies for the delay. Here's a walk-through of how I'm creating individual URLs for the Image Carousel: https://www.useloom.com/share/6c6f4746c1f24b9bae849a2b5a1ec428

In my example, I've linked to anchor tags on the same page but you could link to different URLs with some minor tweaks. 

Below is the code referenced in the video:

`<script>
jQuery("#carousel-team").find(".slick-slide").each(function() {
       var div = jQuery(this); 
       var name = div.find('figcaption');
       var hashtag = name.text().toLowerCase().split(/\s+/).slice(0,2).join("-");
       hashtag = hashtag.replace(/[^a-z0-9\s]/g, '').replace(/[_\s]/g, '-');
       var a = div.find('a');
       var url = a.attr('href');
       a.attr('href', url + hashtag);
       name.wrap('<a href="' + url + hashtag + '"></a>');

    });
</script>`

**Comment by peterrath** [comment] 2017-04-09 21:08
+1

**Comment by BradMK** [comment] 2017-06-04 01:04
Was very surprised that this was not the option from the very begining.

**Comment by MaliBacek** [comment] 2017-06-08 17:42
@mediaworksmt, if I change the php all it does is puting just an image one unnder the other inmstead of the slideshow. They do have the correct link though, but not really helpful.

@JoelEadeDesign, where do you put your code? Sorry, a bit new to all this.

Has anyone else find a simpler solution to this?

**Comment by JoelEadeDesign** [comment] 2017-06-08 23:39
Hey @MaliBacek. It depends on your theme but the quickest way is to add it to your theme's footer.php wrapped in a <script> tag and before the closing </body> tag. 

The better way to do it is to either add it to your theme's existing scripts.js (JavaScript) file or enqueue a new file in the footer.

As an example, here's my code for the example in my video:
![image](https://user-images.githubusercontent.com/1729832/26955068-7883bfc6-4cf7-11e7-9529-39cb29c86934.png)

Hope that helps!

**Comment by MaliBacek** [comment] 2017-06-09 12:15
@JoelEadeDesign thanks, I tried to tweak it so it would work with urls instead of #, failed, crashed the site a bit so I'm giving up:)

**Comment by carasmo** [comment] 2017-06-09 16:35
An easier way, once you learn how to add jQuery in your theme the WordPress way (plenty of tuts and courses out there) is to complete the following steps:

Add the Elementor carousel. 
Add your images. 
Make sure each image in your gallery has an Alt tag unique to that image. 
Use the Advanced Tab (next to Styles), write a class for that instance of that carousel. Don't use a period. In this example that class is ``my-custom-slider``
Save your carousel. 

Now [add the following jQuery the WordPress](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) way (dep jQuery) and adjust based on your unique classes and alt tags.
 

1. Change the class in the ``$slider_class`` variable to the one you used
2. Change the ``myprefix_`` in two locations in the code to your own
3. Change the  img alt value to your own for each one
4. Change the correspond url in the a href to your link (absolute urls)
5. Don't get clever unless you know what you're doing. Such as don't add content between the a tags, there is already something there: the image and the other content. The a tag is wrapping existing content.


```
( function( window, $, undefined ) {
 
    'use strict'; 

    $( document ).ready( function(  ) {
    
        
    	//Add links around individual slider items 
 	var $slider_class = $( '.my-custom-slider' );
 		
    	function myprefix_elementor_load_add_links() {
    	    
    	    //example with 4 images
    	    
    		$slider_class.find( "img[alt='Buddha Serenity Poster']" ).parent( '.slick-slide-inner' ).wrapInner( '<a href="http://mywordpresssite.com/the-slug-1"></a>' );
    		
    		$slider_class.find( "img[alt='Demo Blue Dress']" ).parent( '.slick-slide-inner' ).wrapInner( '<a href="http://mywordpresssite.com/the-slug-2"></a>' );
    		
    		$slider_class.find( "img[alt='Demo Orange Dress']" ).parent( '.slick-slide-inner' ).wrapInner( '<a href="http://mywordpresssite.com/the-slug-3"></a>' );
    		
    		$slider_class.find( "img[alt='Demo Green Dress']" ).parent( '.slick-slide-inner' ).wrapInner( '<a href="http://mywordpresssite.com/the-slug-1"></a>' );
    		
    
    	} //* end myprefix_elementor_load_add_links() function
                 
        //* Load function but check if slider class exists   
	if ( $slider_class.length ) {
        	myprefix_elementor_load_add_links();     
	}       
		
        
        
    } ); //* end doc ready

    
        

} )( this, jQuery );
```

**Comment by WPDevHQ** [comment] 2017-06-12 22:18
This: https://wordpress.org/plugins/wp-gallery-custom-links/ might an alternative temporary solution till Elementor implement in the plugin

**Comment by lgibson212** [comment] 2017-06-29 16:47
I would really appreciate this feature being implemented!

**Comment by orlandobritain** [comment] 2017-08-07 11:35
@carasmo hi, I am trying to implement your solution, I haven't got it working yet.

under your instruction 2, Change the myprefix_ in two locations in the code to your own. Is 'myprefix' the same as the slider class name I chose? i.e. in your example 'my-custom-slider' would be:
function my-custom-slider_elementor_load_add_links() 

or not? thanks

**Comment by orlandobritain** [comment] 2017-08-08 11:24
i managed to get it working with @carasmo method - hopefully this functionality will be built in soon.

**Comment by fimason** [comment] 2017-09-05 14:58
Would really appreciate this functionality too! I've been scratching my head thinking I've missed something, but clearly not. Will try a hack for now and hope for an update soon! :)

**Comment by mgpub** [comment] 2017-09-16 21:31
Really need this functionality - I am dead in the water without it.
Tried the plugin https://wordpress.org/plugins/wp-gallery-custom-links/ but this is not compatible with the image carousel.

**Comment by arielk** [comment] 2017-09-26 14:30
Finally Media Carousel is here with Custom URL for every slide, released in E-Pro v1.9.0

Thanks everyone for your feedback!

**Closed by arielk** 2017-09-26 14:30 UTC
Labels: widget request

**Comment by JoelEadeDesign** [comment] 2017-09-26 21:39
https://media3.giphy.com/media/pa37AAGzKXoek/giphy.gif Woohoo!

**Comment by jademese** [comment] 2018-05-05 04:13
Hello Everyone,
I would like to ask if this feature still works. Because I was not able to set it up. I can only choose one URL for the whole slider, not one for each slide. :(
Thanks for help!

**Comment by FatOrangeKitty** [comment] 2018-11-28 22:53
So it was mentioned above (Sept 2017) by arielk that this feature is now available from v1.9.0 (with pro). While there is an option to add a custom URL, it still only applies to the whole carousel, not individual images on the carousel. The user jademese also seems to be running into the same problem (although it was 6 months ago and I'm not sure if he/she fixed their situation).

My question is, has this feature become standard within E-Pro or do I still need to find a work around to add custom links to individual images on the image carousel? I'm currently using E-Pro v2.2.2 (updated this morning) and WordPress version 4.9.8.

**Comment by Braunson** [comment] 2018-12-19 04:12
I can't believe this is _still_ an unsolved issue. @pojome What's the purpose to hold back this feature? 2+ years with PRs and none were merged.. hmm..

**Comment by mihailkuznetsovs** [comment] 2019-01-13 14:20
@JoelEadeDesign It shows 3 slides no matter what amount I set. I even tried changing the default value 3 slides to 1 slide in the script and changing the possible range from (1, 10) to (1, 1), still shows 3 slides. Can you help?

**Comment by JoelEadeDesign** [comment] 2019-01-13 22:51
Hey @mihailkuznetsovs. Sorry, I'm not sure what the issue is. I'm able to set the _Slides To Show_ to any value:
![image](https://user-images.githubusercontent.com/1729832/51091654-83edf000-17e1-11e9-9744-f7fa52b23ad5.png)

I'm not sure which part of the script you're referring to when you say:
>  I even tried changing the default value "3 slides" to "1 slide" in the script and changed the possible range from (1, 10) to (1, 1), still shows 3 slides. 
There's nothing in the script that affects the number of slides shown.

Cheers

**Comment by JoelEadeDesign** [comment] 2019-02-03 23:51
Looks like you need Elementor Pro and the _Media Carousel_ to create a gallery with custom links for each image or _Slide_ as the case is with the Media Carousel [https://elementor.com/blog/introducing-media-carousel/](url)

**Comment by joshuaburcham** [comment] 2019-02-17 06:14
Hi @JoelEadeDesign 

In the screenshot above, is the text part of the image or did you figure out how to have the caption BELOW the image? Thanks!

**Comment by JoelEadeDesign** [comment] 2019-02-17 11:37
Hi @joshuaburcham,

The text is the _Image Description_, which sits below the image by default. The Job Title is wrapped in a span.

![image](https://user-images.githubusercontent.com/1729832/52912344-50344780-3304-11e9-9d17-4f9847394a90.png)

Does that help out?

**Comment by sebUbi** [comment] 2019-02-20 12:53
here is a small javascript code that will help you add individual links to carousel images. all you need to do is add an id 'carouselPartners' to carousel and add all the links separated by ';' in custom link adress in the same order than images in gallery.

`<script type="text/javascript">
	var link = jQuery('#carouselPartners').find(".slick-slide-inner a").attr('href');
	var links = link.split(';');
	var elements = jQuery('#carouselPartners').find(".slick-slide-inner a");
	for (var i = elements.length - 1; i >= 0; i--) {
		elements[i].href = links[i];
	}
</script>`

**Comment by sebUbi** [comment] 2019-02-20 12:53
+1 to this problem by the way

**Comment by M-Marbouh** [comment] 2019-09-14 17:56
Well this might a be an old issue, but I managed to get it to work following @JoelEadeDesign 's method, but with very minor tweaks, I removed the hashtag replace line, changed the class ID following the newest Elementor update, and as I am targeting Woocommerce categories with longest titles I edited the slice to pull up to 4 words: _.slice(0,4)_, I also set the carousel slider custom link to "/product-category/", so here is the code snippet that should be added in "functions.php":

`function wpb_hook_javascript() {
    ?>
        <script>
          jQuery("#carousel-cats").find(".swiper-slide").each(function() {
       var div = jQuery(this); 
       var name = div.find('figcaption');
       var hashtag = name.text().toLowerCase().split(/\s+/).slice(0,4).join("-");       
       var a = div.find('a');
       var url = a.attr('href');
       a.attr('href', url + hashtag);
       name.wrap('<a href="' + url + hashtag + '"></a>');
    }); 
        </script>
    <?php
}
add_action('wp_footer', 'wpb_hook_javascript');`

**I still recommend buying the pro version of Elementor, as I did, to take advantage of the Media Slider Carousel and support the awesome plugin developers.**

**Comment by Tahoooe** [comment] 2019-10-22 18:46
> here is a small javascript code that will help you add individual links to carousel images. all you need to do is add an id 'carouselPartners' to carousel and add all the links separated by ';' in custom link adress in the same order than images in gallery.
> 
> `<script type="text/javascript"> var link = jQuery('#carouselPartners').find(".slick-slide-inner a").attr('href'); var links = link.split(';'); var elements = jQuery('#carouselPartners').find(".slick-slide-inner a"); for (var i = elements.length - 1; i >= 0; i--) { elements[i].href = links[i]; } </script>`

Here's the updated version with the new class names. Works very well if you put it in an HTML widget after the slider :)

```
<script type="text/javascript">
    var link = jQuery('#carouselPartners').find(".swiper-slide a").attr('href');
    var links = link.split(';');
    var elements = jQuery('#carouselPartners').find(".swiper-slide a");
    
    for (var i = elements.length - 1; i >= 0; i--) {
        elements[i].href = links[i];
    }
</script>
```

**Comment by andretoldo** [comment] 2019-11-08 14:49
+1 for me too =)

**Comment by kimengelen** [comment] 2019-11-18 18:21
@Tahoooe What should I do after I placed the the code into the HTML widget? Since it is not yet working. Thank you so much!!
<img width="1680" alt="Screen Shot 2019-11-18 at 19 17 14" src="https://user-images.githubusercontent.com/57800564/69078543-63617880-0a38-11ea-878b-1fd864224f14.png">

**Comment by Tahoooe** [comment] 2019-11-22 11:14
@kimengelen Did you put the ID `carouselPartners` on the carousel? Also, are you using the right syntax for the links? Like this: `https://youtube.com;https://github.com/;https://www.reddit.com/`

**Comment by dv1961** [comment] 2019-12-08 08:28
@Tahoooe  Similar problem for me, I just don't know where the link are to be put. Can you help?

**Comment by maximedesro** [comment] 2020-01-03 18:59
I wrote a small write up for this here https://elementorcodes.com/elementor-image-carousel-links/ . let me know if it helps!

**Comment by bodhi1970** [comment] 2020-02-07 12:36
> Finally Media Carousel is here with Custom URL for every slide, released in E-Pro v1.9.0
> 
> Thanks everyone for your feedback!

What do I have to do to make that happen? It doesn't work for me. :(

**Comment by innovs** [comment] 2020-04-05 17:54
@guys,

you can try this plugin- CSS For Elementor
See how it works-
https://www.youtube.com/watch?v=j4J1eXL9gKQ&t=24s

**Comment by Panda805** [comment] 2020-04-15 18:01
https://nulledfree.pw/nulled-extensions-plugins/nulled-wordpress-plugins/elementor-pro-page-builder-nulled-crack-download/

**Comment by ZhaoYun17** [comment] 2020-07-11 00:03
It's July 2020, AKA 4 years later. I can't believe this feature wasn't implemented yet.

**Comment by JoelEadeDesign** [comment] 2020-07-11 03:23
Happy Birthday to this issue.
Happy Birthday to this issue.
It will never get addressed.
Happy Birthday to this issue 🎉

**Comment by M-Marbouh** [comment] 2020-07-11 11:16
This will never be implemented in the free Elementor because it's a feature of the pro version. "Media Carousel"

**Comment by ZhaoYun17** [comment] 2020-07-11 14:35
I have elementor pro, I have media carousel, but it's not the same. Media Carousel doesn't allow text under the media... ARgh, am so frustrated with everything.

**Comment by Gebrukal** [comment] 2020-12-08 14:54
Media Carousel is NOT the same thing with the image carousel. In the image carousel the image's height is always the same, while in the media carousel images are being acting like backgrounds, so there may be some screens that the image will be cut somehow.

**Comment by riccardovarrazza** [comment] 2021-09-09 09:15
I found a pretty simple, probably the easiest, workaround. 
**ASSUMPTION:** 
- It works in responsive and either links or website sections
- It applies for photos from website's media section
- I have not tested in other configurations nor in polylang configuration. 

**STEP 1:** in the carousel photo description add the following code
![Untitled](https://user-images.githubusercontent.com/90382845/132655566-ee784114-7b57-4a0e-846c-a777e5760ed5.jpg)

**STEP 2:** in the carousel's caption section, select description. 

Under each picture you will get a button where customer can click, in the attached screenshot I highlighted one of those
![Screenshot](https://user-images.githubusercontent.com/90382845/132657699-a6018589-abda-496c-883d-4b736b4df3ac.jpg)

Thanks all, without your brainstorming I would not have reached this easy resolution
Job done!!!
Riccardo

**Comment by CharlieEtienne** [comment] 2021-12-02 16:00
You could use this code too: 

https://gist.github.com/CharlieEtienne/c55fa9ada93cd33ef88d8641fc7fa98d

It adds two options for each image in media library (custom link and "Open in new tab ?" checkbox) and tells to Elementor to use this custom link if it is set.

This snippet is pure PHP, no JS. 

The only problem is it could break someday if Elementor rewrites its Carousel widget.

Enjoy!

**Comment by NicolasCarrasco** [comment] 2021-12-29 15:15
> You could use this code too:
> 
> https://gist.github.com/CharlieEtienne/c55fa9ada93cd33ef88d8641fc7fa98d
> 
> It adds two options for each image in media library (custom link and "Open in new tab ?" checkbox) and tells to Elementor to use this custom link if it is set.
> 
> This snippet is pure PHP, no JS.
> 
> The only problem is it could break someday if Elementor rewrites its Carousel widget.
> 
> **EDIT: finally I developed a plugin from this snippet: https://wordpress.org/plugins/custom-links-in-elementor-image-carousel/**
> 
> Enjoy!

everything will be OK? I'll see if I find the error.

Thanks for sharing!

**Comment by NicolasCarrasco** [comment] 2021-12-29 15:22
> Esto nunca se implementará en Elementor gratuito porque es una característica de la versión pro. "Carrusel de medios"

eyy! you're right hahaha I forget that widget exists! thanks for sharing

**Comment by daxpd28** [comment] 2022-01-06 01:23
> You could use this code too:
> 
> https://gist.github.com/CharlieEtienne/c55fa9ada93cd33ef88d8641fc7fa98d
> 
> It adds two options for each image in media library (custom link and "Open in new tab ?" checkbox) and tells to Elementor to use this custom link if it is set.
> 
> This snippet is pure PHP, no JS.
> 
> The only problem is it could break someday if Elementor rewrites its Carousel widget.
> 
> EDIT: finally I developed a plugin from this snippet:
> https://wordpress.org/plugins/custom-links-in-elementor-image-carousel/
> 
> Enjoy!

I installed the plugin and it worked perfectly!
It wasn't working for me at first but after I selected "Media File" from the link options it worked great.

![Screen Shot 2022-01-05 at 7 20 58 PM](https://user-images.githubusercontent.com/12687462/148312869-8ac98912-fb49-4058-94ef-9537fbc8b8c9.png)

**Comment by CharlieEtienne** [comment] 2022-01-06 08:29
> I installed the plugin and it worked perfectly! It wasn't working for me at first but after I selected "Media File" from the link options it worked great.

@daxpd28 glad to hear it! You can [leave 5 stars](https://wordpress.org/support/plugin/custom-links-in-elementor-image-carousel/reviews/#new-post) if you like it. Thanks
