### ISSUE TITLE
MultiStep Form for Elementor 

### ISSUE THREAD

**Issue by Dzirt07** [pojome/elementor#5975] opened 2018-10-23 16:32 UTC
Hello, 

It would be a great feature to have the ability to create a multi-step contact from 
With 
- status bar
- with checkbox 
It's a great option for marketers and other people who involved in the lead generation process 

Something similar to Contact Form 7 Multi-Step Forms
[https://wordpress.org/plugins/contact-form-7-multi-step-module/](url)

**Comment by bainternet** [comment] 2018-10-24 08:38
Duplicate of #3911

**Closed by bainternet** 2018-10-24 08:38 UTC

**Comment by Seifertson** [comment] 2018-11-13 16:08
I would also like this feature, please :)

**Comment by squasha4416** [comment] 2019-02-03 04:07
Another strong vote for multistep form with status/selection feedback bar. 
This is a beautiful example of what would be very helpful - selections are logged at the top and provide the ability to jump back and forth within the form. https://www.travelguard.com/buy/default#tripinfo

**Comment by firededge** [comment] 2019-02-28 23:27
A must have!! got my vote

**Comment by BetsyBurke** [comment] 2019-03-22 00:34
How close are we to getting this multi-step form? I saw Ben Pines saying in the Facebook group that they were working on it last February. Looking forward to it too.

**Comment by sp1dev** [comment] 2019-05-05 18:00
yes! this is a really important part of making user-friendly forms

**Comment by herooftheday77** [comment] 2019-10-10 12:54
+1 any news to this?

**Comment by kemeny** [comment] 2020-01-27 17:56
would be nice
