### ISSUE TITLE
Custom breakpoint for nav element

### ISSUE THREAD

**Issue by benhartwich** [pojome/elementor#4883] opened 2018-06-27 09:31 UTC
**What problem is your feature request going to solve? Please describe.**
Some nav trees are long and are displayed in two rows on smaller laptops. So it should be possible to fill in a custom value for the menu breakpoint.

**Describe the solution you'd like**
There should be three options at the nav element widget:
- Tablet
- Smartphone
- Custom
Custom opens a new input field, where I can insert a pixel value.

**Describe alternatives you've considered**
There is no alternative.

**Comment by bainternet** [comment] 2018-06-28 07:10
Duplicate of #78

**Closed by bainternet** 2018-06-28 07:10 UTC
