### ISSUE TITLE
Lose Layout & Formatting with EVERY 2. Update

### ISSUE THREAD

**Issue by wpgeeksaus** [pojome/elementor#4114] opened 2018-04-15 22:48 UTC
## Description

Every new 2. update causes my site to lose all formatting, layout and styling.

Caching is turned off before I update the plugin.  I have tried Regenerating CSS as suggested here https://docs.elementor.com/article/235-update-issues but that doesn't work.

The ONLY thing the works is clicking "Edit with Elementor" to open the editor then closing the editor.  I don't have to do anything and I don't even need to click on "update".  Simply open and close the editor and the page goes back to the way it should be.  BUT, I have to do this for each individual page!

At the moment I am only updating on 2 out of 15 sites and it does it with both sites.

This has happened with EVERY 2. update so far.

I LOVE Elementor but this is causing me a HUGE amount of work.
## Steps to reproduce

I disable my caching plugin, go to plugins, click update for Elementor.  When I vierw my site the formatting etc is gone.

## Environment

Server Environment |   |  
-- | -- | --
Operating System: | Linux |  
Software: | Apache |  
MySQL version: | 5.6.36 |  
PHP Version: | 7.0.29 |  
PHP Max Input Vars: | 3000 |  
PHP Max Post Size: | 128M |  
GD Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected |  

Version: | 4.9.5 |  
-- | -- | --
Site URL: | https://www.wpgeeks.com.au |  
Home URL: | https://www.wpgeeks.com.au |  
WP Multisite: | No |  
Max Upload Size: | 128 MB |  
Memory limit: | 128M |  
Permalink Structure: | /%postname%/ |  
Language: | en-AU |  
Timezone: | Australia/Perth |  
Admin Email: | rob@wpgeeks.com.au |  
Debug Mode: | Inactive

**Comment by drawcard** [comment] 2018-04-16 00:49
Have you tried regenerating the CSS?

Settings > Regenerate CSS

**Comment by wpgeeksaus** [comment] 2018-04-16 00:51
Yes.  I did say that in my initial post.

**Comment by drawcard** [comment] 2018-04-16 00:52
Sorry.

**Comment by wpgeeksaus** [comment] 2018-04-16 00:53
No worries bro.  Easy to miss :)

**Comment by drawcard** [comment] 2018-04-16 00:57
Are you running beta or the stable release? Only thing I can think of is that there's some sort of bug in the beta - I am having a similar issue with Google fonts not loading anymore: #4110 

Could you also post your full Environment report, in System Info > Copy & Paste Info so we can see what plugins / themes you're using?

Cheers

**Comment by wpgeeksaus** [comment] 2018-04-16 01:09
I've using the stable releases and updating form the plugin page...

**Comment by nms64** [comment] 2018-04-16 06:04
The workaround, as stated in the KB, is to:
Go to "Elementor" in the wordpress dashboard, then "Settings", then "Advanced" tab and change "CSS Print Method" to "internal embedding".

This used to happen to me, on every one of my sites when updating the pro addon, so I changed it to internal embedding and haven't lost layouts since.

Elementor saves the css in the uploads folder, so updating the plugin shouldn't affect this, but yet it does.

**Comment by codeagencybe** [comment] 2018-04-16 08:00
> Elementor saves the css in the uploads folder, if set to external, so updating the plugin shouldn't affect this, but yet it does.

Based on this comment, could it be possible that you have some incorrect permissions on those folders? So after clicking that update button, your Wordpress is downloading zip file, unpacking, etc... and if somewhere down that line the permissions are not completely correct, such error can happen. 
Because after the update, Elementor will try to (re-)generate your CSS files but because of the permissions problem, it skips and thus leaving you with a website with no formatting. 
Sounds very logic this way. 

I had a similar issue with Ithemes Security last year; after each update it lost my configuration and preferences and had to re-do them every time. At the end, the problem was coming from incorrect permissions on a subfolder in /wp-content/uploads/......

**Comment by wpgeeksaus** [comment] 2018-04-16 08:01
What should the permissions be??

**Comment by codeagencybe** [comment] 2018-04-16 08:09
> What should the permissions be??

@wpgeeksaus 

I have these on my projects:

in uploads folder /elementor: http://sharing.codeagency.be/3o3X311l0J0D
in subfolder CSS (inside elementor): http://sharing.codeagency.be/0j372Q0P2P1n
files inside subfolder CSS: http://sharing.codeagency.be/3r2H423r0C0i

And from wp-content/
http://sharing.codeagency.be/111Y103p1E0W
http://sharing.codeagency.be/2C1y2B3U1l1z

Make sure these are also correct for wp-content, as when installing a plugin, it's very possible that it will inherit the permissions from there and trying to regenerate files in other location with same permissions.

You can also try another thing first to confirm this problem (or not):
1. backup all those css files you see in /wp-content/uploads/elementor/css
2. try updating again (the original way) so if permissions are wrong that folder might get empty
3. if the folder is empty (or not touched, no new timestamp), it's sure that there might be some permissions problem going on. 
4. restore the original css files from your back and check if your layout still looks good (or not).

In all cases: ALWAYS backup your website before updating any plugin, theme, .... 
Take a full backup (database + files) so you can always roll back in any case of issues. 
This is rule #1 for everybody.

**Comment by wpgeeksaus** [comment] 2018-04-16 08:13
My cPanel uses numbers for permissions.  All the folders are set to 7 5 5

**Comment by codeagencybe** [comment] 2018-04-16 08:16
It's same, numbers are just visual presentation
here is view from FTP client:

http://sharing.codeagency.be/1j2W2k0D2e0S
http://sharing.codeagency.be/331u400d3L0z
http://sharing.codeagency.be/3q3e0Z08030V

**Comment by wpgeeksaus** [comment] 2018-04-16 11:36
They’re all 755

Rob
Founder
WP Geeks
PO Box 944, Innaloo, WA 6918
Tel: 0455 344 546<tel:0455%20344%20546>
www.wpgeeks.com.au<http://www.urbancloudwebdesign.com.au/>


On 16 Apr 2018, at 19:18, Drawcard <notifications@github.com<mailto:notifications@github.com>> wrote:


@wpgeeksaus<https://github.com/wpgeeksaus> what are the permissions of the files inside the folders of /wp-content/? They could be set to something other than 644 even though your folders are 755. Elementor might be trying to access a file vs. a folder.

Check out this guide for a definitive guide to permissions: https://codex.wordpress.org/Changing_File_Permissions

This plugin may also help troubleshoot things:
https://wordpress.org/plugins/wp-file-permission-check/

Good luck!

**Comment by drawcard** [comment] 2018-04-16 11:42
@wpgeeksaus 

> They’re all 755

Your files shouldn't be 755. They should be 644.

Also check file ownership as well as permissions - given it's cPanel all your files should be owned by the www server but it can't hurt to check.

**Comment by wpgeeksaus** [comment] 2018-04-16 11:46
755 is higher access so it shouldn’t do it any harm??

This is happening on all 15 sites I have across different hosts. Surely the file permissions can’t be wrong on all the hosts?!

Rob
Founder
WP Geeks
PO Box 944, Innaloo, WA 6918
Tel: 0455 344 546<tel:0455%20344%20546>
www.wpgeeks.com.au<http://www.urbancloudwebdesign.com.au/>


On 16 Apr 2018, at 19:42, Drawcard <notifications@github.com<mailto:notifications@github.com>> wrote:


@wpgeeksaus<https://github.com/wpgeeksaus>

They’re all 755

Your files shouldn't be 755. They should be 644.

Also check file ownership as well as permissions - given it's cPanel all your files should be owned by the www server but it can't hurt to check.

**Comment by codeagencybe** [comment] 2018-04-16 11:48
@wpgeeksaus does your host use any special processes to update files/folders on their systems? Or are they running as suexec?
I had one client a few years ago who also had a lot problems with their hosting provider one.com. 
Updating WP core always ran into problems even though permissions where set correctly. 
They got it fixed by using "umask" as below. 


From WP Codex: https://codex.wordpress.org/Editing_wp-config.php

Override of default file permissions

The FS_CHMOD_DIR and FS_CHMOD_FILE define statements allow override of default file permissions. These two variables were developed in response to the problem of the core update function failing with hosts running under suexec. If a host uses restrictive file permissions (e.g. 400) for all user files, and refuses to access files which have group or world permissions set, these definitions could solve the problem. Note that the '0755' is an octal value. Octal values must be prefixed with a 0 and are not delineated with single quotes ('). See Also: Changing File Permissions

     define( 'FS_CHMOD_DIR', ( 0755 & ~ umask() ) );
     define( 'FS_CHMOD_FILE', ( 0644 & ~ umask() ) );

Example to provide setgid:

     define( 'FS_CHMOD_DIR', ( 0755 & ~umask() ) );




Also worth to check out the FTP options here. 
Maybe some processes while updating plugins corrupt or fail due to ftp process in background. You could try one of those options in your wp-config.php file and test if things run better after. 

The following are valid constants for WordPress updates:

    FS_METHOD forces the filesystem method. It should only be "direct", "ssh2", "ftpext", or "ftpsockets". Generally, you should only change this if you are experiencing update problems. If you change it and it doesn't help, change it back/remove it. Under most circumstances, setting it to 'ftpsockets' will work if the automatically chosen method does not. Note that your selection here has serious security implications. If you are not familiar with them, you should seek help before making a change.
        (Primary Preference) "direct" forces it to use Direct File I/O requests from within PHP. It is the option chosen by default.
        (Secondary Preference) "ssh2" is to force the usage of the SSH PHP Extension if installed
        (3rd Preference) "ftpext" is to force the usage of the FTP PHP Extension for FTP Access, and finally
        (4th Preference) "ftpsockets" utilises the PHP Sockets Class for FTP Access.
    FTP_BASE is the full path to the "base"(ABSPATH) folder of the WordPress installation.
    FTP_CONTENT_DIR is the full path to the wp-content folder of the WordPress installation.
    FTP_PLUGIN_DIR is the full path to the plugins folder of the WordPress installation.
    FTP_PUBKEY is the full path to your SSH public key.
    FTP_PRIKEY is the full path to your SSH private key.
    FTP_USER is either user FTP or SSH username. Most likely these are the same, but use the appropriate one for the type of update you wish to do.
    FTP_PASS is the password for the username entered for FTP_USER. If you are using SSH public key authentication this can be omitted.
    FTP_HOST is the hostname:port combination for your SSH/FTP server. The default FTP port is 21 and the default SSH port is 22. These do not need to be mentioned.
    FTP_SSL TRUE for SSL-connection if supported by the underlying transport (not available on all servers). This is for "Secure FTP" not for SSH SFTP.

     define( 'FS_METHOD', 'ftpext' );
     define( 'FTP_BASE', '/path/to/wordpress/' );
     define( 'FTP_CONTENT_DIR', '/path/to/wordpress/wp-content/' );
     define( 'FTP_PLUGIN_DIR ', '/path/to/wordpress/wp-content/plugins/' );
     define( 'FTP_PUBKEY', '/home/username/.ssh/id_rsa.pub' );
     define( 'FTP_PRIKEY', '/home/username/.ssh/id_rsa' );
     define( 'FTP_USER', 'username' );
     define( 'FTP_PASS', 'password' );
     define( 'FTP_HOST', 'ftp.example.org' );
     define( 'FTP_SSL', false );

Some configurations should set FTP_HOST to localhost to avoid 503 problems when trying to update plugins or WP itself.

**Comment by wpgeeksaus** [comment] 2018-04-16 11:49
Most of the sites are with Siteground but there are others with various other hosts ALL having the same issue.

Rob
Founder
WP Geeks
PO Box 944, Innaloo, WA 6918
Tel: 0455 344 546<tel:0455%20344%20546>
www.wpgeeks.com.au<http://www.urbancloudwebdesign.com.au/>


On 16 Apr 2018, at 19:48, Fabio Tielen <notifications@github.com<mailto:notifications@github.com>> wrote:


@wpgeeksaus<https://github.com/wpgeeksaus> does your host use any special processes to update files/folders on their systems? Or are they running as suexec?
I had one client a few years ago who also had a lot problems with their hosting provider one.com<http://one.com>.
Updating WP core always ran into problems even though permissions where set correctly.
They got it fixed by using "umask" as below.

From WP Codex: https://codex.wordpress.org/Editing_wp-config.php

Override of default file permissions

The FS_CHMOD_DIR and FS_CHMOD_FILE define statements allow override of default file permissions. These two variables were developed in response to the problem of the core update function failing with hosts running under suexec. If a host uses restrictive file permissions (e.g. 400) for all user files, and refuses to access files which have group or world permissions set, these definitions could solve the problem. Note that the '0755' is an octal value. Octal values must be prefixed with a 0 and are not delineated with single quotes ('). See Also: Changing File Permissions

 define( 'FS_CHMOD_DIR', ( 0755 & ~ umask() ) );
 define( 'FS_CHMOD_FILE', ( 0644 & ~ umask() ) );


Example to provide setgid:

 define( 'FS_CHMOD_DIR', ( 0755 & ~umask() ) );


Also worth to check out the FTP options here.
Maybe some processes while updating plugins corrupt or fail due to ftp process in background. You could try one of those options in your wp-config.php file and test if things run better after.

The following are valid constants for WordPress updates:

FS_METHOD forces the filesystem method. It should only be "direct", "ssh2", "ftpext", or "ftpsockets". Generally, you should only change this if you are experiencing update problems. If you change it and it doesn't help, change it back/remove it. Under most circumstances, setting it to 'ftpsockets' will work if the automatically chosen method does not. Note that your selection here has serious security implications. If you are not familiar with them, you should seek help before making a change.
    (Primary Preference) "direct" forces it to use Direct File I/O requests from within PHP. It is the option chosen by default.
    (Secondary Preference) "ssh2" is to force the usage of the SSH PHP Extension if installed
    (3rd Preference) "ftpext" is to force the usage of the FTP PHP Extension for FTP Access, and finally
    (4th Preference) "ftpsockets" utilises the PHP Sockets Class for FTP Access.
FTP_BASE is the full path to the "base"(ABSPATH) folder of the WordPress installation.
FTP_CONTENT_DIR is the full path to the wp-content folder of the WordPress installation.
FTP_PLUGIN_DIR is the full path to the plugins folder of the WordPress installation.
FTP_PUBKEY is the full path to your SSH public key.
FTP_PRIKEY is the full path to your SSH private key.
FTP_USER is either user FTP or SSH username. Most likely these are the same, but use the appropriate one for the type of update you wish to do.
FTP_PASS is the password for the username entered for FTP_USER. If you are using SSH public key authentication this can be omitted.
FTP_HOST is the hostname:port combination for your SSH/FTP server. The default FTP port is 21 and the default SSH port is 22. These do not need to be mentioned.
FTP_SSL TRUE for SSL-connection if supported by the underlying transport (not available on all servers). This is for "Secure FTP" not for SSH SFTP.

 define( 'FS_METHOD', 'ftpext' );
 define( 'FTP_BASE', '/path/to/wordpress/' );
 define( 'FTP_CONTENT_DIR', '/path/to/wordpress/wp-content/' );
 define( 'FTP_PLUGIN_DIR ', '/path/to/wordpress/wp-content/plugins/' );
 define( 'FTP_PUBKEY', '/home/username/.ssh/id_rsa.pub' );
 define( 'FTP_PRIKEY', '/home/username/.ssh/id_rsa' );
 define( 'FTP_USER', 'username' );
 define( 'FTP_PASS', 'password' );
 define( 'FTP_HOST', 'ftp.example.org<http://ftp.example.org>' );
 define( 'FTP_SSL', false );


Some configurations should set FTP_HOST to localhost to avoid 503 problems when trying to update plugins or WP itself.

**Comment by codeagencybe** [comment] 2018-04-16 11:56
@wpgeeksaus 
Sometimes things can get messed up with too high permissions. 
So yes, sometimes its better to set it @ 644 and not 755. 

And @drawcard  is right, you should also check the owner of the files, as sometimes that can also screw up things. If your application is not the owner, it can block/deny writing access even though you apply correct permissions simply because the app is not allowed to change the files. 

And yes, it can be wrong on all 15 hosts (and more coming) if your hosting provider is using some specific custom rules/permissions on their systems or if a mistake is done with some configuration panel. 

There is a big difference between installing Wordpress from Cpanel (1-click stuff eg softacilous scripts etc...) vs manual installation (upload manually via FTP). 
When installed from Cpanel, often the owner of the application, folders and files is not the same as when you do via FTP. Via FTP, then the owner is the FTP account you are using. 

Same rules applies how you install plugins. Either via WP backend (owner = application), or via manual upload FTP (owner = FTP account)

Or if you upload stuff as root user in terminal/SSH, then you have another different set of permissions/ownership (root). 

So you can see, with UNIX there can be a dozen cases why something can go wrong. 
Some part you can control your self by using always the same workflow and some you can't control (e.g. your host is applying custom stuff you don't know).

**Comment by codeagencybe** [comment] 2018-04-16 12:00
@wpgeeksaus 

> Most of the sites are with Siteground but there are others with various other hosts ALL having the same issue.

I have elementor installed on more than 120+ projects, 98% hosted on our own infrastructure. 
NONE of them have anything from problems like you mention here. 
I'm not saying you can't have any problems, but at least it shows that it just has to be something very specific with either your hosting provider(s) or you are using some unconventional method to install plugins. 

I now see you are using siteground too. I know from others that SG sometimes can be a PITA about caching issues. 
So it's very important that you also check the caching (browser, plugin AND server side) that all caching is gone. 
If you are using something like REDIS/Memcached for object caching, also make sure you empty those.

**Comment by wpgeeksaus** [comment] 2018-04-16 12:01
I understand all of this but 7 of the sites are with completely different host ing providers.

Rob
Founder
WP Geeks
PO Box 944, Innaloo, WA 6918
Tel: 0455 344 546<tel:0455%20344%20546>
www.wpgeeks.com.au<http://www.urbancloudwebdesign.com.au/>


On 16 Apr 2018, at 19:56, Fabio Tielen <notifications@github.com<mailto:notifications@github.com>> wrote:


@wpgeeksaus<https://github.com/wpgeeksaus>
Sometimes things can get messed up with too high permissions.
So yes, sometimes its better to set it @ 644 and not 755.

And @drawcard<https://github.com/drawcard> is right, you should also check the owner of the files, as sometimes that can also screw up things. If your application is not the owner, it can block/deny writing access even though you apply correct permissions simply because the app is not allowed to change the files.

And yes, it can be wrong on all 15 hosts (and more coming) if your hosting provider is using some specific custom rules/permissions on their systems or if a mistake is done with some configuration panel.

There is a big difference between installing Wordpress from Cpanel (1-click stuff eg softacilous scripts etc...) vs manual installation (upload manually via FTP).
When installed from Cpanel, often the owner of the application, folders and files is not the same as when you do via FTP. Via FTP, then the owner is the FTP account you are using.

Same rules applies how you install plugins. Either via WP backend (owner = application), or via manual upload FTP (owner = FTP account)

Or if you upload stuff as root user in terminal/SSH, then you have another different set of permissions/ownership (root).

So you can see, with UNIX there can be a dozen cases why something can go wrong.
Some part you can control your self by using always the same workflow and some you can't control (e.g. your host is applying custom stuff you don't know).

**Comment by wpgeeksaus** [comment] 2018-04-16 12:04
I own. WordPress Support business so I’m very knowledgeable and I have tried everything.

I o my posted here as a last resort having tried everything I can.

I’m well aware of caching etc.

There’s no way this is my issue when it’s happening on 15 sites hosted across 8 different hosts.


Rob
Founder
WP Geeks
PO Box 944, Innaloo, WA 6918
Tel: 0455 344 546<tel:0455%20344%20546>
www.wpgeeks.com.au<http://www.urbancloudwebdesign.com.au/>


On 16 Apr 2018, at 20:00, Fabio Tielen <notifications@github.com<mailto:notifications@github.com>> wrote:


@wpgeeksaus<https://github.com/wpgeeksaus>

Most of the sites are with Siteground but there are others with various other hosts ALL having the same issue.

I have elementor installed on more than 120+ projects, 98% hosted on our own infrastructure.
NONE of them have anything from problems like you mention here.
I'm not saying you can't have any problems, but at least it shows that it just has to be something very specific with either your hosting provider(s) or you are using some unconventional method to install plugins.

I now see you are using siteground too. I know from others that SG sometimes can be a PITA about caching issues.
So it's very important that you also check the caching (browser, plugin AND server side) that all caching is gone.
If you are using something like REDIS/Memcached for object caching, also make sure you empty those.

**Comment by codeagencybe** [comment] 2018-04-16 12:41
> Yeah all of them use cPanel. This is a known issue....I posted the link that Pojo have for the issue so it does seem to happen as they know about it. The problem is the solution they give doesn’t work for me. Maybe it would help if you could explain why simply opening and closing the editor fixes the issue. Without doing anything. Why would opening the editor then closing it fix whatever the issue is??

I'm not familiar with this issue specific as I never have it on my end, but I don't find or read much about this begin a big global problem. 
So the only thing I can say from this, which is still the same as I said before, is that it must be something specific under certain conditions (either host or something else) is causing this. 
Maybe it's a plugin conflict or one of the addons that is conflicting or not completely compatibel with E. 2.*? Maybe it's a theme conflict? I only have experience with OceanWP (premium), so I can't say anything from the others outdoor (GP, Astra, .... there are so many)
If it really was a global problem, everybody should have the same issue no matter which host, addons or theme. And this is not the case. 


The fact you now say that just opening/closing the editor is solving the problem, still confirm my thoughts about file permissions. 
Opening editor = loading file, so that means by opening the editor the system will re-generate the CSS that is required. 
While most customers see this happen during plugin update, yours only do it when opening/closing the Elementor editor. So during a plugin update, it seems you don't have the right permissions but when opening the editor, then it does. 

Can you replicate the problem btw over and over on the same host? 
Can you start a test project (perhaps copy one of your existing projects) on one of those hosts with E. 2.0.
Next update to a higher version, check logfile and see what it gives back. 
If it fails to touch, edit or save a file, it must return at least something so you have a point to search for. 
If you save a backup from v 2.0, you can keep upgrading and roll back to v 2.0 and check the logfiles.
Share that information with the Elementor support team so they also know about this and they can think about wether it's something they can improve in Elementor or provide some helpers functions in a next release.

**Comment by wpgeeksaus** [comment] 2018-04-16 12:50
It’s only been an issue since the first 2.0.0 stable release. I never had the issue before. Also, I didn’t test the beta so didn’t update until the first stable 2.0 release.

As for the theme, all sites use OceanWP.

Other Elementor plugins are -

Elementor Extra
Essential addons for Elementor
Granular Controls
OceanWP Elementor Widgets

Rob
Founder
WP Geeks
PO Box 944, Innaloo, WA 6918
Tel: 0455 344 546<tel:0455%20344%20546>
www.wpgeeks.com.au<http://www.urbancloudwebdesign.com.au/>


On 16 Apr 2018, at 20:42, Fabio Tielen <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah all of them use cPanel. This is a known issue....I posted the link that Pojo have for the issue so it does seem to happen as they know about it. The problem is the solution they give doesn’t work for me. Maybe it would help if you could explain why simply opening and closing the editor fixes the issue. Without doing anything. Why would opening the editor then closing it fix whatever the issue is??

I'm not familiar with this issue specific as I never have it on my end, but I don't find or read much about this begin a big global problem.
So the only thing I can say from this, which is still the same as I said before, is that it must be something specific under certain conditions (either host or something else) is causing this.
Maybe it's a plugin conflict or one of the addons that is conflicting or not completely compatibel with E. 2.*? Maybe it's a theme conflict? I only have experience with OceanWP (premium), so I can't say anything from the others outdoor (GP, Astra, .... there are so many)
If it really was a global problem, everybody should have the same issue no matter which host, addons or theme. And this is not the case.

The fact you now say that just opening/closing the editor is solving the problem, still confirm my thoughts about file permissions.
Opening editor = loading file, so that means by opening the editor the system will re-generate the CSS that is required.
While most customers see this happen during plugin update, yours only do it when opening/closing the Elementor editor. So during a plugin update, it seems you don't have the right permissions but when opening the editor, then it does.

Can you replicate the problem btw over and over on the same host?
Can you start a test project (perhaps copy one of your existing projects) on one of those hosts with E. 2.0.
Next update to a higher version, check logfile and see what it gives back.
If it fails to touch, edit or save a file, it must return at least something so you have a point to search for.
If you save a backup from v 2.0, you can keep upgrading and roll back to v 2.0 and check the logfiles.
Share that information with the Elementor support team so they also know about this and they can think about wether it's something they can improve in Elementor or provide some helpers functions in a next release.

**Comment by bainternet** [comment] 2018-04-16 13:19
Thanks everyone for helping out.

@wpgeeksaus 
The issue you are describing happens most like by one or more caching layer,
 * Browser/Client cache
 * GateWay cache ( like cloudflare )
 * Server File Cache (nginx,apache, reverse proxy ...)
 * Server Memory Cache (in memory like memcache,redis ...)
 * WordPress caching (mu-plugins,drop-ins or any cache plugin )
 * Something else ??

Now the same process of regenerating the CSS just by entering the editor is the one that runs on the front-end, meaning if the CSS file does not exist it gets generated by the first-page load, and if it's not then the page is most likely served from one of the above caching layers.

Now if clearing all caches after update you still don't get the css generated and using the inline mode still dosnt work for you, please contact our support at support @elementor.com for guidance in resolving this issue.

thanks

**Closed by bainternet** 2018-04-16 13:19 UTC

**Comment by tannerchung** [comment] 2018-07-15 04:37
I'm facing this issue as well with a client that uses DreamPress. Meaning, every time I update the plugin or click Regenerate Files in the Regenerate CSS page I get a bunch of errors in the console reporting 404 for all of the css of the templates & pages using elementor. 

The only way to fix the issue was as the OP said, I have to click on Edit with Elementor for every template and page created for the errors to go away and the styling to be fixed BUT the css files are _not_ being regenerated. **I sometimes see global.css appear in the folder but it disappears as soon as I click refresh in FileZilla** I have yet found any correlation as to why global.css keeps disappearing from the folder.

Some others are reporting this as well https://wordpress.org/support/topic/disappearing-styles-after-update/

To try and fix the issues I've tried
1. Making sure the entire uploads folder and its subdirectories are 755 and the files are 644.
2. Using the Regenerate CSS under Elementor->Tools
3. Disabling Varnish - doesn't seem to help

**Comment by doofusdavid** [comment] 2018-08-22 15:51
Agreed, this is happening on several of our multisite installs as well.  I find it hard to imagine that varnish caching is causing files to be deleted.

**Comment by codeagencybe** [comment] 2018-08-22 17:38
@doofusdavid 
Varnish does not delete any files. It stores a static copy from the assets (CSS, JS, ...) into your server RAM so it loads it instantly without letting PHP work again to render everything. 

So if we look at the facts we know as of now, we can confirm the following happens:
* it only happens AFTER updating Elementor, correct? 
* After you did the horrible job of opening all pages, so the CSS is regenerating, you can go back to any page and the styling is still correct? It's a re-do one-time for each page after updating elementor, correct? 
* After the update, the CSS files are gone/vanished from the folder where they should be? 
Did you check if that folder is really empty? Or is it just a mis-reading/mal-reading while loading the page? Or did the CSS files just gone corrupt? This can point to a permissions error. 

I know some hosts have certain php mods disabled/enabled (e.g. su_exec, curl_multi_exec, symlink), so it can be possible that something like that can cause the trouble. 
Perhaps Elementor changed something since version 2.* that requires such php_mod must be installed/enabled, if your host does not have it, it cause these problems. 

Maybe somebody from Elementor staff can verify and confirm this? 


Some more php functions/mods that are common enabled/disabled by hosting providers. 
If one of them is wrongly configured or Elementor does now require it since version 2.*, ... it could explain this sudden error. 


getmyuid,passthru,leak,listen,diskfreespace,tmpfile,link,ignore_user_abord,shell_exec,dl,set_time_limit,exec,system,highlight_file,source,show_source,fpassthru,virtual,posix_ctermid,posix_getcwd,posix_getegid,posix_geteuid,posix_getgid,posix_getgrgid,posix_getgrnam,posix_getgroups,posix_getlogin,posix_getpgid,posix_getpgrp,posix_getpid,posix,_getppid,posix_getpwuid,posix_getrlimit,posix_getsid,posix_getuid,posix_isatty,posix_kill,posix_mkfifo,posix_setegid,posix_seteuid,posix_setgid,posix_setpgid,posix_setsid,posix_setuid,posix_times,posix_ttyname,posix_uname,proc_open,proc_close,proc_nice,proc_terminate,escapeshellcmd,ini_alter,popen,pcntl_exec,socket_accept,socket_bind,socket_clear_error,socket_close,socket_connect,curl_multi_exec,symlink,posix_geteuid,ini_alter,socket_listen,socket_create_listen,socket_read,socket_create_pair,stream_socket_server

**Comment by doofusdavid** [comment] 2018-08-22 18:44
I run our own servers, so I'm able to add/remove any php functions.  It's an ubuntu 16.04 with the distribution's recommended php, varnish, mariadb, apache2 and nginx.  PHP version 7.0.

I have absolutely confirmed that those files are just plain gone from the folder.  It is a multisite.  /public_html/wp-content/uploads/sites/49/elementor/css was completely empty.  After visiting the affected pages, the files came back.

We are running about 250 wordpress sites in a combination of multi and single site, and had been migrating to elementor from visual composer, but if updates can cause multiple sites to break, that's pretty uncool.

The elementor sites which we have that did not break were dependent on css files in the theme, and not generated by elementor.  (assigning classes in elementor, then styling them through our own external css)

I would love to hear if there are specific php mods required, because that would be an easy fix throughout our servers.  

One of our designers did manage to kick it back into gear by reverting to a previous version of elementor, which then broke our Pro, because it was an old version of non-pro elementor, then manually updating elementor again.  

The only thing about the updating process which we do differently is we coordinate everything through mainwp which actually performs the updates.  If Elementor does something on update which isn't triggered by something external doing the update that would a) explain it and b) be unlike every other plugin we use.

**Comment by codeagencybe** [comment] 2018-08-22 19:11
@doofusdavid 

Does this problem only happen on multi site? Or also on the non-multisite setups? 
Perhaps that could be a path that needs to be checked if it's multi site only. 

Does this happen only when you update via MainWP? Or also if you update manually from the site backend directly? 
If it happens only via MainWP, well than it seems the problem is coming there. 
I have used mainwp too in the past, but had a lot issues with sites not being updated. 
Mainwp said it was done and all good, but when I checked the backend directly, no update was done or plugins gone corrupt and gave me errors that plugin was disabled due to missing files. 

After all the issues with mainwp, we started using our own maintenance script with WP-CLI. 
So that could also be a another way for you to test if it works fine if you update via WP CLI
https://developer.wordpress.org/cli/commands/plugin/update/

Elementor has also WP CLI integration since version 2.1
https://elementor.com/2-1-new-features/

Elementor now comes included with WP-CLI integration, allowing you to trigger the following tasks via the command line:

flush_css – Flush the Elementor Page Builder CSS Cache
replace-urls – Replace old URLs with new URLs in all Elementor pages
sync-library – Sync Elementor Library
import-library – Import template files to the Library
Activate or deactivate license – Activate or deactivate your Pro license.
We will continue to add more CLI commands for Elementor in the future.
