### ISSUE TITLE
Elementor + Astra bug

### ISSUE THREAD

**Issue by SylviaRodin** [pojome/elementor#4866] opened 2018-06-25 22:32 UTC
Installed the beta and get blank site. No stress, I can waiting for the release. 

My config, Astra, Elementor Extras, Elementor Pro. 

Thanks for a good job!

**Comment by stevecove** [comment] 2018-06-26 22:10
Elementor extras is not compatible with the latest beta, see #4861 comments, user who made comment has reported issue to elementor extras dev

**Comment by bainternet** [comment] 2018-06-27 06:49
Duplicate of #4861

**Closed by bainternet** 2018-06-27 06:49 UTC

**Comment by SylviaRodin** [comment] 2018-06-27 06:50
Big thanks for the info. No stress and no panic :-) Wish you all a beautiful day.
