### ISSUE TITLE
Can't edit posts previously edited with Elementor

### ISSUE THREAD

**Issue by markwill890** [pojome/elementor#1322] opened 2017-02-20 19:09 UTC
As requested, posting here to report the issue discussed in the following Facebook post.

https://www.facebook.com/groups/Elementors/permalink/1072174629574989/

I receive a server error (HTTP 500) when I try edit edit posts that I had **previously** edited in Elementor.

- Preview works fine

- Creating a new post and editing it works fine

- Editing PAGES previously edited with Elementor works fine (note: this probably needs more testing but it worked at least once)

- Cut the post down to bare bones (in regular editor) - problem remains.

Will add more detail soon.

[system-info-www.perfectbee.com-20-02-2017.txt](https://github.com/pojome/elementor/files/788321/system-info-www.perfectbee.com-20-02-2017.txt)

**Comment by markwill890** [comment] 2017-02-20 19:27
I'm guessing this is somehow related to metadata, not content. I grabbed the HTML from the broken post, copied to a new post and it worked fine.

Now that doesn't prove too much, since I can create any new post and edit it just fine, but would imply that there's nothing corrupt/weird in the content itself.

**Comment by WPDevHQ** [comment] 2017-02-20 19:43
is there any chance of getting an export of your posts in an xml format? Just posts and nothing else please

**Comment by markwill890** [comment] 2017-02-20 19:48
[perfectbee.wordpress.2017-02-20.zip](https://github.com/pojome/elementor/files/788392/perfectbee.wordpress.2017-02-20.zip)

**Comment by markwill890** [comment] 2017-02-20 20:01
All set.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by WPDevHQ** [comment] 2017-02-20 21:05
Thank you the xml and system info - dome some testing and it seem that the culprit is the Table of Contents Plus plugin.

**Comment by markwill890** [comment] 2017-02-20 21:16
Any ideas why this a) doesn't happen on newly created posts and b) happens on the broken posts when I have no reference to TOC  in the post?

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by WPDevHQ** [comment] 2017-02-20 21:25
The shortcode `[toc wrapping="right"]` is what's preventing Elementor from loading.

I deactivated the plugin and edited the post with Elementor - removed the shortcode and save.

Went back and activated the plugn and was still able to edit all posts with Elementor

**Comment by WPDevHQ** [comment] 2017-02-20 21:26
Should that have a closing tag?

**Comment by markwill890** [comment] 2017-02-20 21:30
I have a post with only the word “Hello” in it (no other content and no reference to TOC) – that post won’t load either,

Mark

**Comment by WPDevHQ** [comment] 2017-02-20 21:52
Deactivate the plugin and then have a look at the post in Elementor, you'll probably find that the shorcode was inserted automatically.

**Comment by markwill890** [comment] 2017-02-20 21:57
Pretty sure that’s not the case (I just insert [toc] where I need it and have many posts that don’t use it). But let me do some more digging.

By the way, just to put this in context, I have been driving interest in Elementor on a private Facegroup I am in, with several hundred participants. Many are very interested now, but TOC is very heavily used amongst that group (its kind of the defacto standard for a Table of Contents). This would be a showstopper for many people, especially with TCB 2.0 coming out soon (many are waiting for that).

Is it your opinion that this is a bug in TOC and not how Elementor works with it? I ask because it’s a rock solid and very mature plugin use very heavily so I can’t see TOC spending too much time investigating, but I can see many folks not being able to move to Elementor because of this.

Thanks.

Mark

**Comment by arielk** [comment] 2017-05-16 14:17
Is this problem still happening to you?

If so, can you please send us a link to the plugin you're usin

**Comment by arielk** [comment] 2017-07-09 17:49
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Closed by arielk** 2017-07-09 17:49 UTC

**Comment by williamsmith147** [comment] 2017-07-25 15:38
facebook editing is the most important function of facebook and knows everyone's but if you are not able to do this on your hand so just click here http://www.facebook-customer-service.com/

**Comment by cedri7c** [comment] 2017-08-24 00:06
I can confirm that Elementor is still not working with Table of Contents Plus , every time I add a table to a page it becomes uneditablle with Elementor, just white screen.
Here the link to the plugin: https://de.wordpress.org/plugins/table-of-contents-plus/

I hope this issue will get solved because I won't be able to switch to Elementor if the problem persists.

**Comment by Aryoubarzan** [comment] 2018-10-31 13:51
Thank you [
![image](https://user-images.githubusercontent.com/43348109/47791959-242e8f80-dd30-11e8-9444-29e0efb80926.png)
](https://izolearn.com)
