### ISSUE TITLE
Limited the repeater item

### ISSUE THREAD

**Issue by congthien** [pojome/elementor#4100] opened 2018-04-14 16:06 UTC
Someone know how to limit the number of item in Repeater? 

Thank you!

**Comment by bainternet** [comment] 2018-04-14 16:09
please follow guidelines for opening a new issue, more specifically use the search before you open.

Duplicate of #3997

**Closed by bainternet** 2018-04-14 16:09 UTC

**Comment by congthien** [comment] 2018-04-14 16:10
Thank you. Hope you guys will add it soon.
