### ISSUE TITLE
Popup window with form

### ISSUE THREAD

**Issue by proddigital** [pojome/elementor#5733] opened 2018-09-13 15:52 UTC
Hello guys,

An idea for you ... Elementor could offer Popups.

I wanted to be able to put a popup where inside the popup would have a form. So when the user clicked the button, it would open the popup with the form.

Go to this page https://lp.ingleswinner.com/vocabulario-2/ and click the green button for you to see an example of what I'm talking about.

Obviously the popup would not need to be used only for form, but rather for anything else like image that fills the entire popup window, or any design. It would be like the Popup Ninja plugin.

Thank you.
Rodrigo Carlos

**Comment by bainternet** [comment] 2018-09-13 19:17
Duplicate of #628

**Comment by bainternet** [comment] 2018-09-13 19:17
Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Closed by bainternet** 2018-09-13 19:17 UTC
