### ISSUE TITLE
Feature Request: Compare Item features chart or table

### ISSUE THREAD

**Issue by smellcoffee** [pojome/elementor#3764] opened 2018-03-14 20:06 UTC
I would like to have the ability to create a chart or table that compares features side by side for multiple products.  My plan is to have this for products that we offer. It would be nice to be able to do this for items separate from WooCommerce, but it would be nice to be able to include WooCommerce products too ;-). 

I'm including an image I layout out in a redesign I'm working on. I mocked this up and don't know how I will implement this in my design other then an image, but then I thought of adding it to the feature request wish list. 

There are plenty of pricing tables out there but none that really do side by side comparisons to well.
Thanks

-josh
[compare-graph-or-chart](https://user-images.githubusercontent.com/22917199/37428045-4f28e77a-2788-11e8-9b53-96de9c084435.png)

**Comment by bainternet** [comment] 2018-03-15 09:17
Duplicate of #1342

**Closed by bainternet** 2018-03-15 09:17 UTC
