### ISSUE TITLE
REPEATER control/empty default value bug

### ISSUE THREAD

**Issue by shinTM** [pojome/elementor#3865] opened 2018-03-23 10:12 UTC
since Elementor version 2.0 beta.3 I got a trouble with REPEATER control, if default is left empty [http://prntscr.com/iv8civ](http://prntscr.com/iv8civ),  id option is not saved in the post meta _elementary_ data value, therefore I get notice error here http://prntscr.com/iv8g86  https://github.com/pojome/elementor/blob/release/2.0.0/includes/base/controls-stack.php#L1714

**Comment by bainternet** [comment] 2018-03-25 07:10
@shinTM 

can you please update to beta 4 and report back?
#3706

**Comment by shinTM** [comment] 2018-03-25 13:00
Thanks for attention to my problem. I updated the version to beta4 http://prntscr.com/iw3brf but the problem is not solved http://prntscr.com/iw3dmp and error notice still here http://prntscr.com/iw3duj
I added a default value but for the sections that were added earlier I have an error. I fixed in my plugin http://prntscr.com/iw3gg7 (using 'wp' action) but its very very bad solution and last resort for me

**Comment by KingYes** [comment] 2018-03-27 11:53
Fixed by this PR: https://github.com/pojome/elementor/pull/3916

**Closed by KingYes** 2018-03-27 11:53 UTC
Labels: Waiting For Input

**Comment by atashinbar** [comment] 2018-06-04 09:00
@KingYes The issue is not fixed.
