### ISSUE TITLE
[Feature Request] Font Size in global settings

### ISSUE THREAD

**Issue by Source3Media** [pojome/elementor#4899] opened 2018-06-28 18:50 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Adding this feature makes it easier to maintain a themetic style accross entire websites simply by specifying it in one place.

**Describe the solution you'd like**
I would like to have the ability either in the editor or in Elementor settings to set default font sizes for elements like headers, spans and paragraphs. 

**Additional context**
I feel like adding this to Elementor would improve the maintainability for all users.

**Comment by BrookeRaraAvis** [comment] 2018-06-28 21:01
Definitely needed. This is basic.

**Comment by bainternet** [comment] 2018-07-01 14:06
Duplicate of #1324

**Closed by bainternet** 2018-07-01 14:06 UTC
