### ISSUE TITLE
UI Improvement - Fixed (on scroll) Section/Column/Widget settings Tabs

### ISSUE THREAD

**Issue by zeinnicholas** [pojome/elementor#5062] opened 2018-07-14 19:36 UTC
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I'm always frustrated when I am editing a Section, Column or Widget settings and have to scroll all the way up to click on a Tab to change Layout, Content, Styles or Advanced settings.

**Describe the solution you'd like**
It would be awesome and so much quicker if the settings Tabs remained fixed on scroll, so we can reach them whenever we want without having to scroll all the way up.

**Describe alternatives you've considered**
None, this is pretty much straight forward and would be a legitimate improvement to the UI/UX and workflow in general.

**Additional context**
Just to make sure what I'm talking about, here is a GIF I made:
![screencast-elementor-ui-improvement](https://user-images.githubusercontent.com/26891676/42727849-159e4142-8784-11e8-8435-5d1344d4cd42.gif)

**Comment by bainternet** [comment] 2018-07-15 07:17
Duplicate of #525

**Closed by bainternet** 2018-07-15 07:17 UTC

**Comment by zeinnicholas** [comment] 2018-07-16 01:17
Joinha!
