### ISSUE TITLE
Library of my own designs

### ISSUE THREAD

**Issue by arbex5** [pojome/elementor#5164] opened 2018-07-22 17:10 UTC
As a designer I will really appreciate to have my own library to be choosed with 1 click install just like elementor does.

It could be a togle or tab where you can choose either, or just one, of the library's (elementor's and our own or even third parties library)

This will certainly be much more interesting since the import/export feature isn't much practical as elementor's library with live preview. 

Thanks for considering and if there is a way I can implement it I'll be very happy.

**Comment by bainternet** [comment] 2018-07-23 07:33
Duplicate of #454

**Closed by bainternet** 2018-07-23 07:33 UTC
