### ISSUE TITLE
Section Carousel

### ISSUE THREAD

**Issue by Boffice** [pojome/elementor#6233] opened 2018-11-20 18:25 UTC
Hello,

Would be nice to have carousel effect for sections itself where you can slide columns. 

for example i have 1 section with 3 columns and am using very nice premium static info box widget from 3rd party elementor plugin. i want to keep those 3 by default and slide to view additional 4 columns. 

p.s.
As an addition it can work the same way but instead of columns would be nice to shift between full sections

**Comment by bainternet** [comment] 2018-11-21 08:12
Duplicate of #2898

**Closed by bainternet** 2018-11-21 08:12 UTC

**Comment by Boffice** [comment] 2018-11-21 12:30
Hello,
How is my topic duplicate of #2898? i am not talking about the background or images. i am referring to full columns or sections with its content.

Visual example:
Section4 < Section1 > Section3
Column5 < Column1 , Column2 , Colum3 > Column4

Content elements inside <> are visible on the screen, content from left and right sides are coming to the screen after clicking left or right arrow.

Something like normal slider but instead of images you can slide full content of elements and columns.
