### ISSUE TITLE
MailerLite

### ISSUE THREAD

**Issue by fery379** [pojome/elementor#4808] opened 2018-06-20 08:32 UTC
Hi

Please consider adding **MailerLite** integration.

I know I can use Zapier, but zapier has  #limitations as it registers only 100 processes (contacts) per month. 
And it only gives 5 zaps.

**Comment by bainternet** [comment] 2018-06-20 09:36
Duplicate of #4462

Thanks for the feedback,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Closed by bainternet** 2018-06-20 09:36 UTC

**Comment by fery379** [comment] 2018-06-22 12:22
Thanks. I got the guide here:
https://github.com/pojome/elementor/issues/2397#issuecomment-361185892

But, I don't know what to do with it :)
Specifically:

1. What should I exactly change in the sample code?
2. Where should I put the code in my website?

Best
