### ISSUE TITLE
Featured Section on the first page with widget post

### ISSUE THREAD

**Issue by BorjaAV** [pojome/elementor#4903] opened 2018-06-29 08:21 UTC
## Prerequisites

- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
If you try to optimice the SEO of your website. You need to create a featured content in the first page of the post widget (if you want to create an optimice blog with Elementor). This content have to disappear on the next pages 2,3...

One solutions for that is create a featured secction . 
The other solutions is create and infinite scroll for the post widgets.

**Comment by bainternet** [comment] 2018-07-01 07:19
Duplicate of #4246

**Closed by bainternet** 2018-07-01 07:19 UTC

**Comment by nicholaszein** [comment] 2024-04-12 06:10
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
