### ISSUE TITLE
Beta bug? Center option does not work

### ISSUE THREAD

**Issue by knireis** [pojome/elementor#4929] opened 2018-07-03 08:14 UTC
Elementor Versie: 2.1.0-beta3
Pro: Versie: 2.1.0-beta1
Astra theme, 2017 theme
All other plugins disabled

The option to center an image, title, button does not work anymore.

**Comment by bainternet** [comment] 2018-07-03 09:14
Duplicate of #4861 

also 2.1.0 beta4 is released

**Closed by bainternet** 2018-07-03 09:14 UTC
