### ISSUE TITLE
File control for inserting links to uploaded content

### ISSUE THREAD

**Issue by hybridvision** [pojome/elementor#4468] opened 2018-05-16 09:04 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When building custom widgets, I need the ability to insert the URL of a file (eg. a PDF) that has been uploaded to the WordPress media library. This functionality is almost there with the Elementor `media` control but it is restricted to images only (technically I can upload a PDF but it will return that URL in an `img` tag so it doesn't really work. The library is also filtered to show only images).

The main problem I'm trying to solve is one of usability - right now there's no easy way for a user to reference an uploaded file (PDF/ZIP/DOC/etc) unless they go and manually copy the URL from the media library and paste that into a text field. It's tangentially related to #255 but this is about media uploads instead of pages/posts.

**Describe the solution you'd like**
I've examined the Elementor source code and I would like to have a similar media library popup that allows me to select a file and return that URL and/or ID. It would also be ideal if the media library could be filtered by MIME type so I could specify the file type(s) I want (eg. `application/pdf`, `video/mp4` etc).

A good example of this functionality is available in [Carbon Fields' File Control](https://carbonfields.net/docs/fields-file/). If I could have this functionality in Elementor, I'd be very happy.

For reference, this is how the Carbon Fields file control renders:

![image](https://user-images.githubusercontent.com/11492432/40107016-813b8074-58f7-11e8-8ecb-30d05df94e47.png)

It uses the same preview icon/image as is shown in the standard WordPress media library.

**Describe alternatives you've considered**
I considered using a simple text field to store the URL but that has too many usability issues, as described above. I also considered making a custom post type and using Carbon Fields to manage the uploads but in many cases this is overkill and it's not very convenient to embed individual custom post type elements into Elementor (again, if issue #255 was resolved, this would be much easier).

Lastly, I considered implementing the control myself in Elementor but it seems like such a useful control that it would be better done in the core. Hopefully it won't be too much to add since it is mostly a variation on the media control.

I know the Elementor team has a huge number of requests and issues to deal with but I hope you'll consider this feature. Thanks!

**Comment by bainternet** [comment] 2018-05-16 14:49
Duplicate of #1573

**Closed by bainternet** 2018-05-16 14:49 UTC

**Comment by hybridvision** [comment] 2018-05-16 16:56
Thanks for the reply @bainternet and sorry about the duplicate - I somehow missed that other issue. It would be great to have this in the core but for now I'll investigate the options from the other ticket.
