### ISSUE TITLE
Custom Card Templates for posts/cards widget

### ISSUE THREAD

**Issue by scorpiknox** [pojome/elementor#4726] opened 2018-06-11 21:51 UTC
It would be very helpful if users could simply design a custom card template to be used in the posts widget.

For example, if I have a custom post type called Personas, I would like to be able to design a card using the page builder that allows for full control of the layout and metadata calls (using pods or whatever else.) 

This card template would then be used whenever I have a post widget for the certain custom post type. If my Persona template has attributes like age, occupation, location already defined in the post, I'd like to be able to add that info to the card in a layout of my design.

Not only would this bypass the the widget query that limits our metadata, we could add add various custom field values and metadata along with titles for that metadata.

**Comment by bainternet** [comment] 2018-06-12 10:07
Duplicate of #4440

**Closed by bainternet** 2018-06-12 10:07 UTC
