### ISSUE TITLE
Post Archive - Filter Bar

### ISSUE THREAD

**Issue by RocketGS** [pojome/elementor#4449] opened 2018-05-14 16:45 UTC
I would like to see the same Filter Bar option available in the Post Archives as Elementor does with the Portfolio widget. Where the site visitor can review posts by category or tag, etc.

(https://user-images.githubusercontent.com/32072440/40010682-16ed688c-576b-11e8-8c48-eecf59066c41.png)

## Prerequisites
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Site visitors want to get to the info they need quickly without having to filter all the different types of information on the site. By being able to filter Post with relevant information they visitor will likely stay longer and not bounce as quickly as they might if find the information they seek seems like too much trouble.

**Describe the solution you'd like**
A simple filtering option similar to what is available for the portfolio widget. Although I'd like to see some greater styling available other than just picking a color. Perhaps providing the same styling options as are available for the NavMenu settings.

**Describe alternatives you've considered**
Third part plugins.

**Comment by bainternet** [comment] 2018-05-15 09:38
I merged this issue with  #3140, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by bainternet** 2018-05-15 09:38 UTC

**Comment by peterkinvara** [comment] 2018-12-03 17:31
Yes, if filter bar is available for portfolios, why not  custom post archives? Would dearly like to see this feature available. Elementor Pro is great, but is let down by lack of fetures such as this.

**Comment by stefanico** [comment] 2019-04-16 10:16
+1

**Comment by rodolphebertozzo** [comment] 2019-12-11 12:30
+1

**Comment by dvoorajak** [comment] 2020-04-09 18:32
+1, just asked the same question in Elementor FB community.

**Comment by vladimirtana** [comment] 2020-05-07 20:42
+1 this feature would be nice to have!

**Comment by nicholaszein** [comment] 2022-11-09 14:17
Hello peeps!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #3140

Which is on the same subject. 

As @bainternet said, this issue has been 🔃 **Merged** with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

Best regards,

Nick

**Comment by nicholaszein** [comment] 2023-08-02 01:10
Hello everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released as the Taxonomy Filter widget for the Loop Builder with Elementor Pro v3.15.0! 🥳 

You can now place a standalone taxonomy filter widget anywhere on your layout and target one of the Loop Grid widgets on the page. You can also use multiple taxonomy filters.

You can learn more about this new feature here: https://elementor.com/help/taxonomy-filter-widget/

Thank you, everyone, for your feedback and patience! 🙏  

We are just getting started with filters. 🤫 😉 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
