### ISSUE TITLE
[feature request] Being able to Start Typing with a Negative (via a Hyphen (-)) in the Margin and Padding Fields

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#2240] opened 2017-08-23 09:30 UTC
Hey guys,

In the most recent version of Elementor, you are unable to type a negative value (i.e. -16) without first typing in the 16, and then retrospectively adding the - afterwards.

Please allow me to be able to enter - without the prerequisite of having to a numeric value first.

Thanksssss

**Comment by arielk** [comment] 2017-09-08 14:54
Duplicate of #1035

**Closed by arielk** 2017-09-08 14:54 UTC
