### ISSUE TITLE
Feature request: Dynamic Colors

### ISSUE THREAD

**Issue by djekanovic** [pojome/elementor#6823] opened 2019-01-21 18:39 UTC
Not much to say, Dynamic Colors feature would be nice to have. To be able to use dynamic colors and if needed change them anytime in 1 place and it will apply everywhere. Just like Elementor Default Colors but this would be for colors selected in widgets that are dynamic

**Comment by shilo-ey** [comment] 2019-01-22 08:07
Hi @djekanovic ,

Thanks for the feedback,
Please follow guidelines for opening a new [feature request](https://github.com/pojome/elementor/issues/new?template=Feature_request.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for your request, we are currently working on something that would answer your request. 

Duplicate of #1324

Thanks.

**Closed by shilo-ey** 2019-01-22 08:07 UTC
