### ISSUE TITLE
direct link from Elementor editing interface to the live page.

### ISSUE THREAD

**Issue by ajlcomputers** [pojome/elementor#5810] opened 2018-09-27 16:55 UTC
**What problem is your feature request going to solve? Please describe.**
There's no easy way to get from editing a page within Elementor to viewing the live page. Currently you have to exit to dashboard and then "view page" to make sure the changes have done what you expected.

**Describe the solution you'd like**
An option within the burger menu at the top left to "View live page" ideally above or below "Exit to dashboard" as that would make the most sense to me.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bainternet** [comment] 2018-10-02 11:47
Duplicate of #5287

**Closed by bainternet** 2018-10-02 11:47 UTC

**Comment by vgstef** [comment] 2018-12-13 03:35
That's nice to have this options in the editor, but it should open in a new tab. As a workaround, I tried to press Ctrl+Click to force open in a new tab, but it doesn't work. Same for Shift+Click to open in a new window. Is it a bug or a feature request? But for me, I very often try to open the actual page (or or to the website) in a new tab to see the actual page, not the preview.
