### ISSUE TITLE
Feature request: first shown slide set to item #1 by default for Testimonial Carousel

### ISSUE THREAD

**Issue by Dhilofe** [pojome/elementor#3796] opened 2018-03-18 15:52 UTC
Hi there,

While the need for ordering in a testimonial carousel might seem trivial per se,  I am actually using this element in a way that would require a chronological order in the way its content is shown (instead of individual blurbs and quotes imagine for instance a series of sentences connected together, as in a question-answer relationship).

I just noticed that the widget invariably considers the second item out of four in the carousel as its starting slide, no matter what I try. However, starting from the second slide kind of ruins the overall sequence/message I would like to show, because the user has to either manually go back one slide or wait for the cycle to end and start over just to read the first slide.

With that said, I might of course suggest you to devise a starting slide selector of some sort. But in the meantime...

...since I believe most users won't be particularly interested in the slides ordering (and since when they are, they will probably want to start from number 1 in any case), would you please consider **setting the first item in a testimonial carousel as the very first slide shown by default**?

Thanks and best regards,
Dario

**Comment by bainternet** [comment] 2018-03-19 09:42
Duplicate of #3187

**Closed by bainternet** 2018-03-19 09:42 UTC
