### ISSUE TITLE
Feature Suggestion - Pagination more complete

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#4345] opened 2018-05-04 16:27 UTC
Hello guys,

I think is missing a option to let the pagination continuous, when I mark I want to show only 5 pages, I want to the possibilite to show more after page5

**Comment by Artneo7** [comment] 2018-05-04 17:40
I agree. I would like an option to display in search results page more than 8 results without pagination. I try to change inside WordPress settings "Settings> Reading > Blog pages show at most" but it doesn't work right now.

**Comment by PrashGupta** [comment] 2018-06-10 10:06
@bainternet 
This issue is different than what I had reported. Also, these are bugs, not a new feature suggestion. Anyways. Reproducing the issues below here, since you have merged it with this one

There are 2 issues with Pagination in the Posts Widget

1. Clicking on Posts Pagination goes to the next page (as desired), but it reloads the whole page and goes to top of the page. This behaviour is seen on all types of devices - desktop, tablet as well as mobile. This is really very frustrating, when the widget it towards the end of a long page

2. Only the current page shows up on mobile & tablet in the pagination area. So if you are in Page1, it does not show any link for Page 2 on mobile/tablet - but shows all pages on the desktop

**Comment by bainternet** [comment] 2018-06-10 13:50
@PrashGupta 

Like I said,
1) is a normal behavior of a web page.
2) Again, not a bug.

what comes out of it is that you are asking for more options on mobile, which fits right in this feature request.

thanks.

**Closed by bainternet** 2018-06-10 13:50 UTC
Labels: request/enhancement

**Comment by Craigeniah** [comment] 2024-09-26 17:42
I think what's really desired here is for the pagination to work like this for example: https://datatables.net/
The next button and the numbers do not reload the entire page, and they do not move the user away from their scroll position on the page. I vote to reopen this issue.
