### ISSUE TITLE
Request: Copy Paste Widget Style

### ISSUE THREAD

**Issue by dudaster** [pojome/elementor#3529] opened 2018-02-21 08:12 UTC
Just like Photoshop it would be nice to able to copy  paste a widget/element Style.

I know it is tricky because every widget has a different type of style but you can make it between the same widgets/elements types, else alert("This style is for 'some widget' only! ").

**Comment by arielk** [comment] 2018-02-21 20:30
Duplicate of #1479

**Closed by arielk** 2018-02-21 20:30 UTC
