### ISSUE TITLE
Accordion and Toggle widget should allow us to determine if its initial display is expanded or collapsed

### ISSUE THREAD

**Issue by jonathanasbell** [pojome/elementor#3980] opened 2018-04-01 15:51 UTC
Right now when I use Accordion and Toggle widgets for some reason the first item always displays initially as expanded. I dont want that. I want it to start out collapsed. Can you please edit the code

**Comment by bainternet** [comment] 2018-04-02 13:05
Duplicate of #2584

**Closed by bainternet** 2018-04-02 13:05 UTC
