### ISSUE TITLE
Add Internal Links for URL to elements for existing pages in website

### ISSUE THREAD

**Issue by richcb7** [pojome/elementor#4631] opened 2018-06-03 15:12 UTC
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

In Posts and Pages, WP has the ability to set URL links to Internal Existing pages by listing those pages.
I have not seen this feature in any of the Elementor elements.
This forces the users to display the desired page in live mode to retrieve the URL to be copied and then pasted into the URL field in the Elementor element.

**Describe the solution you'd like**

Simple - Do the same thing with links as WP and make existing pages available in the URL link elements.

**Describe alternatives you've considered**

See above

**Comment by bainternet** [comment] 2018-06-03 15:42
Duplicate of #255

**Closed by bainternet** 2018-06-03 15:42 UTC
