### ISSUE TITLE
Additional formatting for Posts Widget

### ISSUE THREAD

**Issue by kcfitzgerald** [pojome/elementor#6676] opened 2019-01-10 14:56 UTC
[ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I'd love to see more customization options for the presentation in the posts widget like position of the text in relation to the image and which order the content appears in (aka metadata above title instead of below etc.)

I've attached a screenshot of how I would like to present my posts.

![c42219ed-9919-4626-8fd8-93007cf04b60](https://user-images.githubusercontent.com/7206587/50976449-fd25d400-14bd-11e9-91c7-12e40c3ed8e6.jpg)

**Comment by bainternet** [comment] 2019-01-13 11:31
Duplicate of #4440

**Closed by bainternet** 2019-01-13 11:31 UTC

**Comment by nicholaszein** [comment] 2023-08-01 18:58
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
