### ISSUE TITLE
More Responsive

### ISSUE THREAD

**Issue by gadudi** [pojome/elementor#4101] opened 2018-04-14 19:12 UTC
Hello guys
Regarding the presets for desktop, tablets and mobile.
for mew, on each website I used elementor to design the pages, header and footer I ALWAYS HAD TO ADD Custom Media queries to fit the design to all screen sizes (desktop mainly)
meaning, if the designer handed me a PSD for 1920px, the design will never fit also for laptop screen, and I will definitely have to costume CSS all widgets to fit screens.
I really thing the best way to approach it, will add the option to choose screen size and not only 3 presets.
I know you are trying to keep it simple as it can be, but this will add much needed functionality.

**Comment by bainternet** [comment] 2018-04-15 06:30
Duplicate of #78

**Closed by bainternet** 2018-04-15 06:30 UTC
