### ISSUE TITLE
Trouble selecting Columns and Sections tab under Absolute Positioned elements

### ISSUE THREAD

**Issue by katart** [pojome/elementor#962] opened 2016-11-30 14:03 UTC
## Description

I am working with a theme that has the Primary Nav absolutely positioned above the main content area. This makes selecting the Section or Columns tab on the first Elementor element impossible.

I've seen this issue before. I would like to find a solution to this problem, but I do have a feature suggestion that might help with issues like this in the future.

Would it be possible to have a Navigation Tree that will allow the user to select elements up the "DOM tree"? Similar to the section at the bottom of the WordPress TinyMCE editor. For example, if I choose an Elementor Widget within a column, the "tree" would look something like this: <u>section</u> > <u>column</u> > <u>widget</u>. Now I can select the Section that is wrapping this column and widget within the Navigation Tree. This would allow me to Edit that section even if I cannot select the Section Tab.

## Steps to reproduce

1. Create first Elementor Section
2. Attempt to select the Section tab (to modify Section settings) by hovering over the top of the Elementor section
3. The Section Tab disappears because the absolute positioned element is above it and does not allow me to select the underlying tabs.

## Environment

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.18 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
	MySQL version: 5.5.5
	PHP Version: 5.6.18
	PHP Max Input Vars: 10000
	PHP Max Post Size: 8M
	GD Installed: Yes
	Elementor Library: connected

== WordPress Environment ==
	Version: 4.6.1
	Site URL: http://www.lakewaramaugobserved.com
	Home URL: http://www.lakewaramaugobserved.com
	WP Multisite: No
	Max Upload Size: 2 MB
	Memory limit: 40M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Active

== Theme ==
	Name: Lake Waramaug Observed
	Version: 1.0.0
	Author: KatArt Graphics
	Child Theme: Yes
	Parent Theme Name: KAG Default
	Parent Theme Version: 2.0
	Parent Theme Author: KatArt Graphics

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

== Active Plugins ==
	Elementor
		Name: Elementor
		Version: 0.11.2
		Author: Elementor.com

	WooCommerce
		Name: WooCommerce
		Version: 2.6.8
		Author: WooThemes

**Comment by drawcard** [comment] 2016-12-01 06:08
I've had this happen before. The elementor editor has the body class "elementor-editor-active" so I wrote a custom style for the problematic element within that class, eg 

```css
.elementor-editor-active .my-ab-pos-menu { position: static; } 
```

So whenever that menu shows up inside the elementor editor viewer, it just gets fixed in its position. Or, you can hide it completely with "display: none".

Alternately you can add some margin to the content container directly under the menu, to reveal the tabs: 

```css
.elementor-editor-active .main-container { margin-top: 200px; }
```

**Comment by WPDevHQ** [comment] 2016-12-01 08:54
The problem is most certainly always from the theme itself, at least those that I have encountered with a fixed top navbar - they set their navbar's z-index way too high, some as high as 99999.

To combat this you just have to add some CSS - assuming the theme's the class is `.navbar-fixed-top` something like should do the trick.
`.elementor-body .navbar-fixed-top,
.elementor-editor-active  .navbar-fixed-top {
        z-index: 1;
}`

**Comment by dasigna** [comment] 2016-12-01 09:19
encountered the same problem several times now - and even if theres no header or navbar with high z-index or else. simply create a full width/screen section on blank page and just drag one element too much into it - your ability to reach the sections tab is gone ...
not that really big thing, just not very comfortable to tweak with css every time, so i think somehow there must be a better way to solve this. (still havent found one yet)

**Comment by katart** [comment] 2016-12-01 12:41
I think the Navigation Tree (I'm not sure if that's the correct term) is a good idea even for those not having this problem.

**Comment by hasitha92** [comment] 2016-12-05 16:17
I'm also having the same issue. i wrote a temporary css code till a fix release and added it using a custom css plugin. 

`.elementor-editor-active .elementor.elementor-edit-mode .elementor-editor-column-settings{
   bottom:auto !important;
}`

**Comment by drawcard** [comment] 2016-12-05 23:58
Thanks for the idea about including it as a custom plugin @hasitha92, that's probably the right way to go about it.

**Comment by hasitha92** [comment] 2016-12-06 07:00
@drawcard you can use  [Simple Custom CSS](https://wordpress.org/plugins/simple-custom-css/) or [siteorigin CSS](https://wordpress.org/plugins/so-css/) plugin to override the css code. The code I mentioned above will show the column and section buttons inside the section container top left corner. not on top of the section container. check the screenshot attached.
  
![image](https://cloud.githubusercontent.com/assets/10194063/20915937/fb0ffb56-bbae-11e6-89f4-c873038a23c0.png)

code I added using the custom css plugin 

`.elementor-editor-active .elementor.elementor-edit-mode .elementor-editor-column-settings
{ 
     bottom:auto !important; 
}`

**Comment by arielk** [comment] 2017-03-23 10:22
Temp fix for this issue:
https://github.com/pojome/elementor/commit/e2b1916182bcc19ea7dba37ea7746a5a74d9cf48
https://github.com/pojome/elementor/commit/3644762f5b9882fa9a0259e8b2898280cc76dcea

**Closed by arielk** 2017-03-23 10:22 UTC
Labels: enhancement, ui/ux

**Comment by katart** [comment] 2018-05-07 13:26
This is what I was looking for: https://wordpress.org/plugins/navigation-tree-elementor/#description

**Comment by breath-ee** [comment] 2018-06-14 17:16
Had the same issues using a Bootstrap4 theme with a fixed-top. Adding `.elementor-editor-active .navbar { position: static; }` pushes the elementor section below the navigation so you can select it.
