### ISSUE TITLE
I can't edit the page using Elementor. 

### ISSUE THREAD

**Issue by dinakaranAppViewX** [pojome/elementor#3445] opened 2018-02-12 06:38 UTC
Hi Guys,

I see some "Edit Widget Duplicate Widget Remove Widget" Error in white page. I am afraid of If I remove the plugin or change anything my site may go down. Can you suggest an solution without having down time?

**Comment by norewp** [comment] 2018-02-12 10:07
Sounds like you are seeing a bulleted list of the mentioned output and that means you have JS conflict somewhere in your install.

Start by deactivating all other addons and plugins other than Elementor Core & Elementor Pro (if installed) - then proceed to edit and see if the issue has been resolved. You may need to switch to the default theme to rule out your theme as the cause of the conflict.

If the issue is resolved by following the above action the proceed to reactivate each plugin 1 at a time and checking the editor till you find the one causing the conflict.

If the above process does not resolve the issue then check on Memory Limit set for your site together with PHP version - the easiest way to do that is by going to Elementor > System Info & scanning through it. Would also help if you post that info here for further assistance.

**Comment by dinakaranAppViewX** [comment] 2018-02-12 11:52
I'll check that and get back to you. 

Thanks for helping me out.

**Comment by bainternet** [comment] 2018-02-25 15:42
Closing for lack of activity,

Feel free to reopen if the issue persists.

**Closed by bainternet** 2018-02-25 15:42 UTC

**Comment by ThomasKoscheck** [comment] 2018-03-01 09:56
Same issue here, but no solution found yet.

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.10.3
	MySQL version: 5.5.5
	PHP Version: 7.0.27-0+deb9u1
	PHP Max Input Vars: 9000
	PHP Max Post Size: 8M
	GD Installed: No
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.4
	Site URL: https://web.thomaskoscheck.de
	Home URL: https://web.thomaskoscheck.de
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 96M
	Permalink Structure: /%postname%/
	Language: de-DE
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Twenty Seventeen
	Version: 1.4
	Author: the WordPress team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: de_DE
	User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.189 Safari/537.36 Vivaldi/1.95.1077.55

== Active Plugins ==
	Elementor
		Version: 1.8.12
		Author: Elementor.com

	Elementor Pro
		Version: 1.15.2
		Author: Elementor.com


== Debug ==
	Errors: 
		ReferenceError: google is not defined
			at https://web.thomaskoscheck.de/wp-admin/post.php?post=559&action=elementor - 2:2
			2018-02-18 16:47 +00:00
			x 3 times
