### ISSUE TITLE
Dynamic background image

### ISSUE THREAD

**Issue by srcek** [pojome/elementor#4019] opened 2018-04-06 21:55 UTC
It would be awesome if I could, for example, add post featured image as a background image to every single post type. To achieve that I would have to be able to dynamically add picture background to sections or columns. That way I could get custom image background heading for every single post on my site.

**Comment by bainternet** [comment] 2018-04-08 06:30
Duplicate of #3971

**Closed by bainternet** 2018-04-08 06:30 UTC
