### ISSUE TITLE
Elementor UI's language should be the user's language rather than the page's

### ISSUE THREAD

**Issue by Jaska** [pojome/elementor#5848] opened 2018-10-04 07:57 UTC
- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The very confusing Elementor UI when adding new pages with different languages that one is not familiar with. 

When using Elementor and Polylang, Elementor changes it's entire UI to be the same language as the site. It's very confusing when trying to add e.g chinese and russian translations to a copied elementor page. Translations are often received from third party so the user adding the translation may not understand that language.

The elementor editing interface should be the language of the user editing it - not the language of the page in question. Or at least it should be changeable.

**Describe the solution you'd like**
A checkbox into elementor settings "Set admin language as the editing language"
And by clicking it, the UI would always be english regardless of the translation I'm working on. (if my admin language was set as english)

**Describe alternatives you've considered**
Deleting all .pot files of Elementor plugin?

**Comment by bainternet** [comment] 2018-10-04 08:19
Duplicate of #5148

**Closed by bainternet** 2018-10-04 08:19 UTC

**Comment by numanzahid** [comment] 2019-03-06 12:52
We need this feature please.
can not develop second language website. all element names are translated. now I cant find and search.
there should be some options to select language of elementor UI.
