### ISSUE TITLE
Select Single Post Template in the Dashboard on Per-page Basis

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#4654] opened 2018-06-05 10:41 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be handy to have the possibility to choose the single post template in the Dashboard on per-page basis.

**Describe the solution you'd like**
Similar approach as in Anywhere Elementor Pro:
![obrazek](https://user-images.githubusercontent.com/5634870/40971385-ba911fb6-68bd-11e8-93cb-77d00d6ae60d.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment] 2018-06-05 11:55
Duplicate of #4611

**Closed by bainternet** 2018-06-05 11:55 UTC

**Comment by black-eye** [comment] 2018-06-05 13:20
I'm not sure, wheather it's the same problem like #4611. 
Just to be sure, I meant to be able to select Elementor's Single Template on a specific (non-elementor) page.

E.g. I have a template made in Elementor Theme Builder for a single page, with no display conditions set, and I will be able to select it for non-elementor page in the dashboard.

**Comment by bainternet** [comment] 2018-06-05 15:08
Yep.

**Comment by teolaz** [comment] 2018-07-11 09:00
@bainternet 3 (same) requests and still no time to think about a solution ? :D
