### ISSUE TITLE
ACF Fields in Archive Page (e.g. Post Widget)

### ISSUE THREAD

**Issue by Turanligil** [pojome/elementor#6427] opened 2018-12-13 14:04 UTC
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Its possible to style a "Elementor Single Page" but its not possible to design the "Archive Page Elements"...

**Describe the solution you'd like**
Would be nice if i could Design the ELELEMENT wich is used for example in the "Post Widget".
You know what i mean. For exmaple i have createt the CPT -> "Event" with the ACF Fields -> "event-date, event-location, event-time ...." now an want to create the Overview (Archiv Page) for the Events but at the moment its not possible to show all the ACF Fields in my Archiv Page because the standart "Post-Widget" dont allow ACF Fields... Would be great if i could DESIGN the Single "Post Widget Item and choose this for the Archiv Page. You know what i mean?

**Comment by bainternet** [comment] 2018-12-13 15:06
Duplicate of #4440

**Closed by bainternet** 2018-12-13 15:06 UTC

**Comment by sandeepamb** [comment] 2019-01-18 23:11
for this problem got any solution?

**Comment by nicholaszein** [comment] 2023-08-01 18:52
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce the new Loop Builder released with Elementor Pro v3.8.0! 🥳 

With the new Loop Grid widget, you can customize your post listings with custom templates! 💪 
Drag & Drop widgets to create complex designs, fine-tune your Loop Grid layout, add alternate templates, and much more!

This is just the first phase. More customization is coming!

Check out the article here: https://elementor.com/help/loop-grid/

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
