### ISSUE TITLE
Pasting from one page to another loses IDs

### ISSUE THREAD

**Issue by bkjproductions** [pojome/elementor#5795] opened 2018-09-25 02:22 UTC
## Prerequisites
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Description
The latest version of Elementor allows you to copy and paste from one page to another, which is a great new thing, something I have wanted from day 1.  Unfortunately, in doing so, you lose the IDs of various elements. This may be a "feature" because if you were to copy/paste on the _same_ page, of course you wouldn't want to have two ID's of the same name.

## Steps to reproduce
Create a Section, put something in it, give it an ID under the Advanced tab. Maybe give several elements an ID for good measure. Right-click the Section to copy it. Go to another page and edit with Elementor. Paste, and your copied Section should appear. However, it will not have IDs.

I would hope that there might be an alert to let you know that the IDs are going to disappear, if that happens.

Maybe if the point of not carrying over the IDS is to prevent ID collisions, then (better) you are prompted for new IDs, or (worse) the IDs are named with suffixes -1, -2, -3 (etc. like what happens to images if you upload the same file several times).

## Isolating the problem
- [x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.32
	PHP Version: 7.0.31
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.8
	Site URL: http://elementor.abbotmill.com/site
	Home URL: http://elementor.abbotmill.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Minimalist
	Version: 
	Author: BKJ Productions
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

== Active Plugins ==
	Admin Columns Pro
		Version: 4.3.7
		Author: AdminColumns.com

	Duplicate Page
		Version: 2.7
		Author: mndpsingh287

	Duplicate Theme
		Version: 0.1.6
		Author: Muller Digital Inc.

	Duplicator
		Version: 1.2.46
		Author: Snap Creek

	Elementor
		Version: 2.2.4
		Author: Elementor.com

	Elementor Button Extended
		Version: 1.0.2
		Author: InternetCSS

	Elementor Pro
		Version: 2.1.9
		Author: Elementor.com

	Enable Media Replace
		Version: 3.2.7
		Author: ShortPixel

	Essential Addons for Elementor
		Version: 2.7.11
		Author: WPDeveloper

	GitHub Updater
		Version: 8.3.1
		Author: Andy Fragen

	ManageWP - Worker
		Version: 4.6.2
		Author: ManageWP

	Media Library Thumbnail Enhancer
		Version: 1.3
		Author: Nick Ciske (ThoughtRefinery)

	PopBox For Elementor
		Version: 1.0.7
		Author: Zulfikar Nore

	Post Type Switcher
		Version: 3.1.0
		Author: John James Jacoby

	Regenerate Thumbnails
		Version: 3.0.2
		Author: Alex Mills (Viper007Bond)

	WP Version in Query String Modifier REVISED
		Version: 1001.0.0.6 bkj 0.0.1
		Author: joesat

== Must-Use Plugins ==
	Endurance Page Cache
		Version: 1.1
		Author: Mike Hansen

	Endurance PHP Edge
		Version: 0.2
		Author: Mike Hansen

	ManageWP - Worker Loader
		Version: 
		Author: ManageWP

== Debug ==
	Errors: 
		TypeError: Cannot read property 'prev' of undefined
			at http://elementor.abbotmill.com/site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=0111537493740 - 2:208894
			2018-09-21 02:07 +00:00

		TypeError: Object.values is not a function
			at http://elementor.abbotmill.com/site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=0111536869093 - 2:110478
			2018-09-13 20:09 +00:00
			x 5 times

		TypeError: Object.values is not a function
			at http://elementor.abbotmill.com/site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=0111536869093 - 2:187489
			2018-09-13 20:09 +00:00

		TypeError: Object.values is not a function
			at http://elementor.abbotmill.com/site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=0111536869093 - 2:110478
			2018-09-13 20:09 +00:00
			x 2 times

		TypeError: Object.values is not a function
			at http://elementor.abbotmill.com/site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=0111536869093 - 2:187489
			2018-09-13 20:09 +00:00
			x 2 times

		TypeError: Cannot read property 'pageYOffset' of undefined
			at http://elementor.abbotmill.com/site/wp-includes/js/jquery/jquery.js?ver=1.12.4 - 4:30811
			2018-08-22 20:22 +00:00

		TypeError: Cannot read property 'errors' of undefined
			at http://elementor.abbotmill.com/site/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.8 - 2:139163
			2018-08-22 19:54 +00:00
			x 6 times

		TypeError: Object.values is not a function
			at http://elementor.abbotmill.com/site/wp-content/plugins/elementor/assets/lib/inline-editor/js/inline-editor.min.js?ver=4.9.8 - 1:3265
			2018-08-21 22:37 +00:00

		TypeError: Cannot read property 'query' of null
			at http://elementor.abbotmill.com/site/wp-content/plugins/elementor/assets/lib/e-select2/js/e-select2.full.min.js?ver=4.0.6-rc.1 - 1:60824
			2018-08-20 03:02 +00:00

				
</details>

**Comment by bkjproductions** [comment] 2018-09-25 02:39
Before copy we have an ID:
![before copy we have an id on an image element](https://user-images.githubusercontent.com/4551281/45989646-89fd6c80-c04a-11e8-926c-9c0ae285a695.JPG)

After paste we have no ID:
![after pasting there is no id](https://user-images.githubusercontent.com/4551281/45989645-89fd6c80-c04a-11e8-9907-37023441bfeb.JPG)

**Comment by bainternet** [comment] 2018-09-25 06:50
Duplicate of #5691

**Closed by bainternet** 2018-09-25 06:50 UTC

**Comment by swinggraphics** [comment] 2021-01-05 22:24
@bainternet This is not quite the same as #5691. This issue is specific to copying between pages, where the ID should be kept.

**Comment by swinggraphics** [comment] 2021-03-19 19:10
@bainternet I'm running into this problem again, so posting again to please get this fixed. #5691 is closed, which is fine, but this is a different issue—_not_ a duplicate. It needs to be reopened.

**Comment by lursyy** [comment] 2021-12-14 10:56
Ran into the same problem today & took me some time to figure it out.
Maybe one could add some clear indication when copying to inform the user about this circumstance?

**Comment by vincentjflorio** [comment] 2022-01-19 18:58
Also happening reliably every single time for me. Oddly enough, independent of other themes, plugins or hosts. 

Maybe it's a feature? But like @lursyy said, a heads up would smooth things over for client sort of people who can't be bothered to be surprised.

I can't think of a reason off the top of my head to expect to lose it, but maybe then could we opt into retaining it?

**Comment by kasket091** [comment] 2022-05-26 00:55
Any fixes this should be an easy fix retaining class/ID would be great.

**Comment by mikeecho2** [comment] 2023-04-17 14:40
Any fix to this yet?
I have latest Elementor, and copy/past to new page still drops the CSS ID's

**Comment by indysigner** [comment] 2023-08-24 13:19
>We removed the ID property from copy/paste because it would create multiple elements with the same ID which is simply invalid markup.

It still should not be removed when copy-pasting to a different site or template. Please fix! @bainternet

**Comment by 10000things** [comment] 2024-11-25 19:53
Bump - this is happening for me too, really needs a fix. Or alternatively, if duplicating IDs is prevented by design (shouldn't be for distinct page templates), adding a button to duplicate a template (including IDs) would also work. I'm trying to show a client variations on page designs right now, very time consuming to have to hunt and replace all the missing IDs....

**Comment by bkjproductions** [comment] 2024-11-25 21:30
At this point, my workaround is to stick with **class**, and not use IDs. Also, this issue seems to be marked as **Closed**. ;)

**Comment by phkoon** [comment] 2025-04-11 11:02
Only almost 7 years after this issue was opened and it's still haunting the editor, wow
