### ISSUE TITLE
Feature Request: My Template Thumbnails

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#3418] opened 2018-02-07 20:17 UTC
## Description

It would be really great if My Templates could show up as thumbnails. It would make it so much easier to see what's in there without having to guess,

**Comment by drank** [comment] 2018-02-07 22:26
This is a duplicate of https://github.com/pojome/elementor/issues/3127.

**Comment by bainternet** [comment] 2018-02-08 12:16
I merged this issue with  #3127 , which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by bainternet** 2018-02-08 12:16 UTC
