### ISSUE TITLE
Remove default 20px margin below Elementor Widgets

### ISSUE THREAD

**Issue by katart** [pojome/elementor#1221] opened 2017-01-25 16:57 UTC
All Elementor Widgets seem to have a default 20px bottom margin and there doesn't seem to be a way to override this in the Elementor Widget settings. This is the CSS code that affects the Elementor widgets:

`.elementor-widget:not(:last-child) {
    margin-bottom: 20px;
}`

I would like to remove this 20px margin without editing the CSS. Is this possible?

**Comment by pingram3541** [comment] 2017-02-08 19:20
I just want to add that I understand the need to have this default margin for those that would be simply using the widgets "as-is" and not need to worry about white space above/below widgets but there should be a way to remove this without having to use custom css...especially with how selectors can change with future updates breaking that custom css.

I propose a simple checkbox that would remove any default container margins.

**Comment by mjflower** [comment] 2017-05-07 12:45
Great idea. +1

**Comment by pingram3541** [comment] 2017-05-07 22:38
Yes, don't remove it, just allow us to disable it when it applies and then it doesn't break any sites going backwards =)

**Comment by bmwillrath** [comment] 2017-06-09 04:00
+1

**Comment by tudormnt** [comment] 2017-06-09 10:39
Definitely a big + for not having this as default. As design patterns go, there is a need to add margin to some elements but adding this for a widgets (which bundle more than one base html element) is a incorrect. I'm thinking that a control to space out widgets **at the column level** (like spacing anything in Elementor, really) is the way to go, instead of having to disable this.

**Comment by soyket** [comment] 2017-06-10 06:50
agreed !

**Comment by arielk** [comment] 2017-06-20 15:20
Elementor 1.5 RC2 has already been released with this enhancement, please check this issue #1827

Thanks for the feedback!

**Closed by arielk** 2017-06-20 15:20 UTC
Labels: enhancement

**Comment by leocrespo** [comment] 2019-04-13 21:57
Where can I find this setting to disable the default margin-bottom? I know it has been released on 1.5 RC2 but where it is?

**Comment by pingram3541** [comment] 2019-04-15 23:44
It can be found in each column's layout tab under Widget's Space (px):

![Screen Shot 2019-04-15 at 4 36 18 PM](https://user-images.githubusercontent.com/319284/56172213-3aa66b80-5f9d-11e9-8509-8d471d356ba1.jpg)


...and in the Global Settings found using the upper-left nav menu icon (3 bars) or within Elementor's back end settings. 

![Screen Shot 2019-04-15 at 4 36 41 PM](https://user-images.githubusercontent.com/319284/56172278-9c66d580-5f9d-11e9-903b-e0b65d1a1056.jpg)

![Screen Shot 2019-04-15 at 4 36 58 PM](https://user-images.githubusercontent.com/319284/56172223-48f48780-5f9d-11e9-9f46-c2c5fec28550.jpg)

**Comment by leocrespo** [comment] 2019-04-17 18:08
Thank you for that, but when I change from 20 to 0 there is no save button.
The UPDATE button doesn't turn green so I can't save the setting, *even
when focusing out of the input.*






On April 15, 2019 at 4:44:36 PM, pingram3541 (notifications@github.com)
wrote:

It can be found in each column's layout tab under Widget's Space (px):

[image: Screen Shot 2019-04-15 at 4 36 18 PM]
<https://user-images.githubusercontent.com/319284/56172213-3aa66b80-5f9d-11e9-8509-8d471d356ba1.jpg>

...and in the Global Settings found using the upper-left nav menu icon (3
bars) or within Elementor's back end settings.

[image: Screen Shot 2019-04-15 at 4 36 41 PM]
<https://user-images.githubusercontent.com/319284/56172278-9c66d580-5f9d-11e9-903b-e0b65d1a1056.jpg>

[image: Screen Shot 2019-04-15 at 4 36 58 PM]
<https://user-images.githubusercontent.com/319284/56172223-48f48780-5f9d-11e9-9f46-c2c5fec28550.jpg>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/elementor/elementor/issues/1221#issuecomment-483458474>,
or mute the thread

**Comment by pingram3541** [comment] 2019-04-18 06:40
Yep, you've found a bug. (tested v2.5.14)

- Editing a column's settings and adding any value in the "Widget's Space" field results in the update button turning green and when clicked successfully saving.

- Going to Global Settings and adding any value in the "Widget's Space" field results in the update button NOT turning green nor is it clickable to update the settings.

If I then edit something else, forcing the update button to turn green and click update, it saves and even when refreshing the page I can see the global setting is also saved.  Checking the back end settings as well (/wp-admin/admin.php?page=elementor#tab-style) I can see my value is also stored there.  So you *can* get around this but it's a little bit tricky.

**Comment by austinsparx** [comment] 2019-09-05 02:16
+1 to the idea to be able to disable this per element with a checkbox or similar! 

The current solution is very all or nothing - use custom padding everywhere, or nowhere. In most use cases you want to adjust for a small amount of items only, so having this option would be great to avoid having to add custom padding in for every element.

**Comment by pingram3541** [comment] 2019-10-22 17:51
Another method is to simply match the bottom margin offset in the element's advanced tab setting bottom margin to the polar offset.

i.e. if default margin is 20px, set element's bottom margin -20px

The next element you drop in (minding no theme or plugin css bothers) will snug right up top just underneath the previous element as desired, but yeah, a checkbox would still be nice.

**Comment by startupsclubplatform** [comment] 2020-01-03 07:24
I found a way to overcome this problem If you select the section completely and go to layout, you need to change the content width to full page

<img width="296" alt="Screenshot 2020-01-03 at 12 52 19 PM" src="https://user-images.githubusercontent.com/47053507/71711681-18ed5d00-2e28-11ea-91ed-4ca46ea91e17.png">

**Comment by innoforce-dev** [comment] 2020-02-25 14:23
What happened to this issue - all the suggestions were just work arounds? Why was the issue closed?

**Comment by tienlx91** [comment] 2020-03-07 11:17
@innoforce-dev  
There is a quick fix for this. 
Open "Text" tab, remove last character then re-enter the character that you just remove. And Done!

**Comment by marekmaurizio** [comment] 2020-07-24 12:57
If you hide a responsive element this becomes hell very fast.

**Comment by leecollings-sb** [comment] 2021-07-21 13:47
Just annoyed to find out the issue is STILL PRESENT, despite this issue being closed and there being no solid resolution?

**Comment by trulyergonomic** [comment] 2022-08-11 05:02
Updated Elementor and this issue appeared.
How to solve: Edit Column > Layout > Widgets Space (px) > Set to 1 or other than zero (if set to zero it defaults to 20)

**Comment by Dade88** [comment] 2022-08-11 12:15
> Updated Elementor and this issue appeared. How to solve: Edit Column > Layout > Widgets Space (px) > Set to 1 or other than zero (if set to zero it defaults to 20)

Same issue, I used -1 as a workaround. But indeed, if set to 0 if defaults to 20 :/

**Comment by neylwalecki** [comment] 2022-08-11 18:07
+1
