### ISSUE TITLE
Please widen color input so that the alpha value is visible

### ISSUE THREAD

**Issue by maxwellhibbert** [pojome/elementor#4434] opened 2018-05-13 01:22 UTC
When setting a colour with an alpha value, it's not visible in the UI without adding your cursor and scrolling to the end first.

![rgba](https://user-images.githubusercontent.com/2948524/39962892-c96fad98-569f-11e8-9f3c-7c0d6396ac77.png)

**Comment by bainternet** [comment] 2018-05-13 07:34
We already addressed it as much as we could without messing out the editor panel layout.

Duplicate of #3320

**Closed by bainternet** 2018-05-13 07:34 UTC

**Comment by maxwellhibbert** [comment] 2018-05-13 08:26
There's a fair amount of unused space to the right there.. not sure I understand? 🤔

**Comment by maxwellhibbert** [comment] 2018-05-18 00:34
I ended up using a Chrome extension to inject css. Works great, but not sure why the input can't take up the full available width by default.

`.wp-color-picker {
  width: 100% !important;
}`

![works](https://user-images.githubusercontent.com/2948524/40210184-dd804f28-5a86-11e8-8a89-c73794dfeac1.png)
