### ISSUE TITLE
[Feature Request] Captions in Lightbox

### ISSUE THREAD

**Issue by rja66** [pojome/elementor#3608] opened 2018-02-28 07:20 UTC
I would like to be able to add custom captions to lightbox images

I do not want caption to show on page, only in lightbox.

Currently in Image Gallery it's possible to add a caption to the image on the page, but the caption does not show in lightbox.

Thanks for your consideration

**Comment by jayalove** [comment] 2018-02-28 11:36
+1

**Comment by bainternet** [comment] 2018-03-05 09:09
Duplicate of #2502

**Closed by bainternet** 2018-03-05 09:09 UTC
