### ISSUE TITLE
Feature Request: Configure conditions based on language in Polylang or Body class

### ISSUE THREAD

**Issue by Webtica** [pojome/elementor#4944] opened 2018-07-03 20:18 UTC
- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
It would be good to display different headers or footers based on the language or body class on a page.

**Comment by bainternet** [comment] 2018-07-04 07:46
Duplicate of #4839

**Closed by bainternet** 2018-07-04 07:46 UTC
