### ISSUE TITLE
Elementor should get its interface language from user's language not site's language

### ISSUE THREAD

**Issue by themedleb** [pojome/elementor#4608] opened 2018-05-31 03:03 UTC
Imagine a French designer is going to redesign a Chinese website, the Chinese man will create a user account for the French designer and gives it the proper abilities/permissions to design the website, the French designer can't understand Chinese because Elementor pulls its interface language from the site language (Chinese) not from the user's language (French), and of course the site's language must not be changed to French just because the site needs to be redesigned.

For Elementor to support websites that has multi users with different languages, it should get its interface language from user's language ("Users => User profile") not from the website's language ("Settings => General").

If this is corrected, each user will be able to use Elementor no matter their language.

I hope this make sense.

**Comment by JohnMulderFrance** [comment] 2018-05-31 05:29
+1

**Comment by bainternet** [comment] 2018-06-03 15:55
@themedleb 

thanks for your suggestion, 
Next time please follow the new issue/feature request guidelines and template.

Duplicate of #3623

thanks again.

**Closed by bainternet** 2018-06-03 15:55 UTC

**Comment by themedleb** [comment] 2018-06-03 19:06
Thank you @bainternet, but the issue [#3623](https://github.com/pojome/elementor/issues/3623) is closed, why by the way?

**Comment by bainternet** [comment] 2018-06-04 04:42
Read my answer there. Sadly it still applies.
