### ISSUE TITLE
Elementor can't load after activate Polylang

### ISSUE THREAD

**Issue by blaisck** [pojome/elementor#7022] opened 2019-02-09 14:22 UTC
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I want to implement my web with a tool (ID as default and EN), so I installed the plugin, but I haven't activated it yet.

I prepared the English pages, when I finished, I just activated the plugin and configured it.

But after I activate it, I can't edit my page, after I disable the plugin, I can edit my page again.
## Steps to reproduce
1. Install Polylang
2. Create dual language pages
3. Activate and configure the plugin
4. Connect each page to support dual language
5. Try to edit the page

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.10.3
	MySQL version: Source distribution v5.6.40
	PHP Version: 5.6.37-1+ubuntu16.04.1+deb.sury.org+1
	PHP Max Input Vars: 2000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: No
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.0.3
	Site URL: https://cakap.com
	Home URL: https://cakap.com
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 96M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 7
	Debug Mode: Inactive

== Theme ==
	Name: Cakap Theme
	Version: 1.0.0
	Author: Cakap by Squline
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 1.6.8
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.1.1
		Author: Automattic

	All In One SEO Pack
		Version: 2.11
		Author: Michael Torbert

	Astra Premium Sites
		Version: 1.2.12
		Author: Brainstorm Force

	Astra Pro
		Version: 1.6.13
		Author: Brainstorm Force

	Contact Form 7
		Version: 5.1.1
		Author: Takayuki Miyoshi

	Duplicate Page and Post
		Version: 2.4.1
		Author: Arjun Thakur

	Elementor
		Version: 2.4.5
		Author: Elementor.com

	Elementor Pro
		Version: 2.4.3
		Author: Elementor.com

	Essential Addons for Elementor
		Version: 2.9.5
		Author: WPDeveloper

	Google Tag Manager for Wordpress
		Version: 1.9.2
		Author: Thomas Geiger

	Really Simple CAPTCHA
		Version: 2.0.1
		Author: Takayuki Miyoshi

	Redirection
		Version: 3.7.3
		Author: John Godley

	Ultimate Addons for Elementor
		Version: 1.9.1
		Author: Brainstorm Force

	Unbounce Landing Pages
		Version: 1.0.43
		Author: Unbounce

	WP Rocket
		Version: 3.2.4
		Author: WP Media

	Zendesk Chat Widget
		Version: 1.4.14
		Author: Zendesk


== Log ==
	: 
Log: showing 7 of 72019-01-22 09:44:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.1',
  'to' => '2.4.3',
)]
2019-01-22 09:45:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.3.1',
  'to' => '2.4.0',
)]
2019-01-25 10:01:43 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.3',
  'to' => '2.4.4',
)]
2019-01-25 10:02:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.0',
  'to' => '2.4.1',
)]
2019-01-27 10:06:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.1',
  'to' => '2.4.2',
)]
2019-02-01 14:08:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.4.4',
  'to' => '2.4.5',
)]
2019-02-06 12:08:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.4.2',
  'to' => '2.4.3',
)]

PHP: showing 1 of 1PHP: 2019-01-29 00:51:15 [error X 12][/var/www/cakap/mainsite/wp-content/plugins/elementor/includes/controls/base-multiple.php::59] Maximum execution time of 0 seconds exceeded [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 5 of 5JS: 2019-01-31 11:44:37 [error X 32][https://cakap.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.4.2:2:41002] Cannot read property \'get\' of undefined 
JS: 2019-02-01 04:35:46 [error X 14][https://cakap.com/wp-admin/js/editor.min.js?ver=5.0.3:1:694] Cannot read property \'style\' of undefined 
JS: 2019-02-01 04:35:46 [error X 14][https://cakap.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.4:2:209315] Cannot read property \'on\' of null 
JS: 2019-02-06 09:46:28 [error X 5][https://cakap.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:213956] Cannot read property \'models\' of undefined 
JS: 2019-02-09 10:11:53 [error X 1][https://cakap.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.4.5:2:82347] Blocked a frame with origin \"https://cakap.com\" from accessing a cross-origin frame. 

<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by shilo-ey** [comment] 2019-02-10 07:55
Hi @blaisck ,

After trying to reproduce the issue without success and after reviewing your log, it is possible to be caused by another cause.

Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Closed by shilo-ey** 2019-02-10 07:55 UTC

**Comment by blaisck** [comment] 2019-02-11 04:10
Hi @shilo-ey , thanks for your responses.

Sorry, I upload System Info when I deactivated Polylang plugin, this problem occurs when I connect each page to become support dual language. When I disconnect each page, then Elementor can work well again.

**Comment by blaisck** [comment] 2019-02-11 04:12
And please don't close when the problem is not solved yet.
Because I think this is bug, so I open the issue.

**Comment by shilo-ey** [comment] 2019-02-11 08:45
[**@blaisck**](https://github.com/blaisck) commented on [Feb 11, 2019, 6:12 AM GMT+2](https://github.com/pojome/elementor/issues/7022#issuecomment-462215444 "2019-02-11T04:12:26Z - Replied by Github Reply Comments"):
> And please don't close when the problem is not solved yet.
> Because I think this is a bug, so I open the issue.

@blaisck and because we need further information to debug this, and couldn't reproduce on our side we referenced you to our support. 

Please follow the instructions provided and we will do our best to help.

Thanks.

**Comment by mikari94** [comment] 2022-11-30 04:35
I have a similar problem. When Polylang is active, the Elementor Editor throws a 500 error and the layout of the main language sites is broken. The second language pages work as they should.

**Comment by orenplevin** [comment] 2023-05-11 03:31
Was this ever solved? I am getting this error as well...
After going though the installation of polylang - and for example adding a new homepage in a different lanaguge when I click on edit with elementor - everything gets stuck....

**Comment by pierre-wts** [comment] 2023-05-17 09:48
Same issue here, when polylang (and polylang connect for elementor) are active, i get 500 errors when trying to update a change in pages. I've tried many fixes, nothing works, i'll try to switch to wpml. To note : it was progressive, working at first but the more i was building the site, the more problem.  I put the wp memory limit to 256M, but polylang seems to need more :
Error log (one of many, all the same) : 

"URL/wp-admin/post.php?post=8&action=elementor"
2023/05/15 13:31:39 [error] 108379#108379: *89983 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 40960 bytes) in /www/redacted_632/public/wp-content/plugins/polylang/vendor/composer/ClassLoader.php on line 364" while reading upstream, client: redacted, server: redacted, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8.0-fpm-redacted sock:", host: "redacted:55737", referrer: "redacted/wp-admin/post.php?post=8&action=elementor"

server : nginx (kinsta staging site)
PHP : 8 and tried 8.1 too
wordpress : 6.2.1
Elementor : 3.13.2 (pro 3.13.1)
Polylang 3.3.3
polylang connect for elementor 2.4.1
(i also use jet plugins by crocoblock)
