### ISSUE TITLE
Condition selection for displaying header/footer 

### ISSUE THREAD

**Issue by fingers-morris** [pojome/elementor#4438] opened 2018-05-13 10:29 UTC
It would be very useful to be able to set a new header/footer to display only on pages which are written in a particular language, or have a particular identifier in the URL - i.e. in my particular case, I would like to be able to show a particular header on pages where the URL for the page contains ?lang=fr - which is what WPML adds when an English page is translated (in this case to French).

I note many people having problems  (similar to I am experiencing at the moment), where however good a theme or translation plugin may be, there can still be difficulties in getting second language pages to display correctly.
I think that to be able to select where to display a header/footer (or even a complete page?) based on a search term would be really useful to many, and enhance  Elementor no end

**Comment by bainternet** [comment] 2018-05-13 10:45
Duplicate of #4280

also next time please follow guidelines for opening a new issue/feature request.

thanks

**Closed by bainternet** 2018-05-13 10:45 UTC
