### ISSUE TITLE
Global Styling Control for H1, H2, etc. 

### ISSUE THREAD

**Issue by dotpdesign** [pojome/elementor#4657] opened 2018-06-05 13:36 UTC
[x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
There isn't a way to globally style headers within Elementor. You can use a text widget and select the H tag which will allow adopting of global styles from your theme, but that doesn't give you visual control globally and some themes don't have extensive global styling built in. So you are left with custom CSS for global styling.

**Describe the solution you'd like**
I would like to be able to globally style all headers within Elementor employing all the style options available in Elementor for other site elements.  

**Describe alternatives you've considered**
Custom CSS for H tags. Developing a plugin for Elementor to do this. Mashup up between Elementor text widget and Theme global styling (not pretty).

**Additional context**
With all the amazing control in Elementor, this seems like a very basic need to be able to control all H1, H2, etc. globally. Please make it happen :).

**Comment by bainternet** [comment] 2018-06-05 14:21
Duplicate of #4657

**Closed by bainternet** 2018-06-05 14:21 UTC

**Comment by dotpdesign** [comment] 2018-06-05 14:43
Can you provide a link to #4657?

**Comment by dotpdesign** [comment] 2018-06-05 14:44
I don't understand where the duplicate is. Please provide a link to where this has already been brought up.

**Comment by Shirkit** [comment] 2018-06-29 17:58
@bainternet did you just the issue close saying it's a duplicate of itself?

**Comment by dotpdesign** [comment] 2018-06-29 18:34
I only submitted one request. If there is a duplicate, I can't find the original.

**Comment by bainternet** [comment] 2018-07-01 14:06
I meant #1324 sorry
