### ISSUE TITLE
Include your own font icons (linea-Icons)

### ISSUE THREAD

**Issue by WAM-Meerbusch** [pojome/elementor#2700] opened 2017-11-06 14:12 UTC
A possibility to integrate own font icons like Linea Icons
So this z.b. in the FlipBox, Iconbox or can be selected.
Would really help if that would work

**Comment by arielk** [comment] 2017-11-06 19:53
Duplicate of https://github.com/pojome/elementor/issues/110

**Closed by arielk** 2017-11-06 19:53 UTC
