### ISSUE TITLE
Allow to Add Custom Fields, Buttons, etc to Single Items in Archive Template 

### ISSUE THREAD

**Issue by damithruwan1234** [pojome/elementor#5523] opened 2018-08-24 06:26 UTC
Please Allow to add custom fields, buttons, etc to single items in archive template.

Let say, you are building a site for vehicle selling business. We can't at least display the price which is a custom filed in archive template. It is a big disadvantage. Please at least add a `add_action` to single items in archive template. So WordPress developers can modify the single items area in Archive Template .

**Comment by collindavis** [comment] 2018-08-24 06:51
@damithruwan1234 you can achieve this with this plugin: https://wordpress.org/plugins/ele-custom-skin/

**Comment by bainternet** [comment] 2018-08-26 11:53
Duplicate of #4440

**Closed by bainternet** 2018-08-26 11:53 UTC
