### ISSUE TITLE
Update Icon Library From Fontawesome 4 to Fontawesome 5

### ISSUE THREAD

**Issue by pscully** [pojome/elementor#5458] opened 2018-08-17 14:29 UTC
## Prerequisites

- [ x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Updated icons for various 3rd party companies. 

**Describe the solution you'd like**
Update using Fontawesome 4 to Fontawesome 5. Several logos have been updated in the past year and Fontawesome 4 still uses the old logo. For example, the Houzz logo was updated last March but its not available through Social Icons module. 

**Describe alternatives you've considered**
None

**Additional context**
None.

**Comment by bainternet** [comment] 2018-08-19 07:31
Duplicate of #4430

**Closed by bainternet** 2018-08-19 07:31 UTC
