### ISSUE TITLE
Global setting for Line Height and Font size

### ISSUE THREAD

**Issue by IdioticDoodler** [pojome/elementor#5879] opened 2018-10-09 03:21 UTC
I already saw a similar request, but still not solved.
This is one of the basic features we need, we can edit the font-size using custom CSS but some client don't have knowledge in coding. So I'm requesting if we can have a global setting for font-size and line-height. We already have global setting for default font-family ,font-weight and color so I just want to ask why don't we have this kind of feature? Little bit hassle to edit every widget and set their font-size and line-height. I think my request will be closed as a Duplicate **but before you do that please read it first and reply if we can have this?** Thanks

**Comment by bainternet** [comment] 2018-10-09 07:45
Duplicate of #3345

**Closed by bainternet** 2018-10-09 07:45 UTC

**Comment by bainternet** [comment] 2018-10-09 07:46
@IdioticDoodler 

When we close as duplicate it's not that we don't read it, it simply means that this request is/has been discussed on another issue and its done so we could deal with it more efficiently.


Thanks for your feedback!

**Comment by drewclifton** [comment] 2019-03-05 20:25
Hi I don't think this is a duplicate? This is about a setting to add default line height (ie to the Default Fonts section I presume), not editing CSS (from what I can see).

**Comment by ndstate** [comment] 2019-05-17 23:40
> Hi I don't think this is a duplicate? This is about a setting to add default line height (ie in the Default Fonts section I presume), not editing CSS (from what I can see).

I agree.

**Comment by RobertShippey** [comment] 2019-06-19 15:42
@bainternet this is definitely not a duplicate of the Issue you mentioned. This is a specific feature request about adding 'line height' and 'font size' options to the 'Default Fonts' panel. The issue you mentioned is looking for better ways to add custom CSS, this is about reducing the amount of custom CSS needed - so the opposite. 
Please reopen the issue.

**Comment by sriharsha1403** [comment] 2019-07-05 05:14
hi i have a problem with line height settings in paragraph in elementor.. i can seem to set the gap for two lines in a paragraph. please help me solve this problem. i want to increase the line space of a paragraph.

**Comment by giorgiogio48** [comment] 2019-09-03 13:46
Firefox css. line-height not working? I solved this problem this way: https://firebird-vbnet.blogspot.com/2019/09/firefox-css-line-height-not-working.html

**Comment by highlyheidi** [comment] 2020-04-10 07:11
line-spacing has a default set to zero how do i fix this on elementor pro?
