### ISSUE TITLE
Feature Request: Add custom ID to Tabs

### ISSUE THREAD

**Issue by collindavis** [pojome/elementor#1264] opened 2017-02-01 16:41 UTC
In order to load specific tabs on page-load, or via external links, tab's require an ID. Elementor creates its own IDs and uses data-tab attributes.

I would like to be able to add my own custom ID to each tab element which could be added in addition to whatever Elementor already assigns for the ID.

e.g.
<div class="elementor-tab-title" data-tab="1" id="mycustomtab"><span>My Tab</span></div>

If a custom ID is not possible, then perhaps a custom data-id attribute can be supported instead? The goal is to have a way to automatically toggle/open a tab via a hash URL.

**Comment by sigersmit** [comment] 2017-08-02 18:36
This would be great, @arielk . For example; I have a FAQ using the Toggle element, throughout the website I would like to link to specific questions/answers in the FAQ. Right now that is not possible. Could you add the option to set an ID per toggle-item? And the option to set a toggle-item open or closed by default. 

An other useful addition would be to add different element-types to an toggle-item, like icon list, image slider, elementor template, etc. Maybe the toggle-content can be an empty div, where one could drag and drop an item?

These apply to the accordion and tabs also :-)
Thanks anyway for the great tool Elementor is!

**Comment by JosiahCarberry** [comment] 2017-09-08 15:13
It should be mentioned that a custom ID can easily be added to the contents of any tab by coding using the text tab in the editor, not the visual tab.  For me, the issue is to have the page displayed with that tab opened.

**Comment by kurieuo** [comment] 2017-10-31 13:44
Will this be coming any time soon? I just purchased elementor and this'd be a really great feature to have.

**Comment by bainternet** [comment] 2017-12-26 13:19
already merged https://github.com/pojome/elementor/commit/0b2e9bb1e1163244588a265efd6031d6a9781a2a

will be out next version.

**Closed by bainternet** 2017-12-26 13:19 UTC
Labels: request/enhancement

**Comment by navotera** [comment] 2022-06-14 08:47
I am sorry to open this again. 
I am using the latest version of elementor. 

Cannot find any input to add the ID on each of the tabs:
![image](https://user-images.githubusercontent.com/1424851/173535123-321ba05b-1a26-4f78-bb12-ea84f35bb492.png)

Please let me know where to add the ID for each of the tabs. 

Thank you.

**Comment by micksw** [comment] 2022-10-12 13:18
Having the same issue. Appears to not be implemented in the Elementor Pro Version yet. Can't also find any documentation on it.

**Comment by Key2info** [comment] 2022-10-13 12:38
Hi,

having the issue. Has this been implemented yet?
