### ISSUE TITLE
Feature Request - Link Modules Styles

### ISSUE THREAD

**Issue by ericft** [pojome/elementor#6449] opened 2018-12-14 19:29 UTC
Hi,

Probably already asked by someone but it would be really great to have the option to link same modules styles between them instead of changing individually, it will be cleaner in the css and quicker to change.

Thanks for your great work!

**Comment by bainternet** [comment] 2018-12-16 12:47
Duplicate of #965

**Closed by bainternet** 2018-12-16 12:47 UTC
