### ISSUE TITLE
Sucess Message Forms Can't style

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#4816] opened 2018-06-20 15:28 UTC
hello guys, it's impossible to edit the style of the message of thhe forms, I think you should put this option

http://prntscr.com/jx832v

Plus one feature is missing, please we need popups ;)

**Comment by bainternet** [comment] 2018-06-21 13:06
Duplicate of #1180

Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Closed by bainternet** 2018-06-21 13:06 UTC
