### ISSUE TITLE
Social Icons Are Only Showing Squares

### ISSUE THREAD

**Issue by NTuneMusic** [pojome/elementor#5293] opened 2018-08-03 13:54 UTC
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by jstillings1** [comment] 2018-08-04 00:47
have a look at this. [https://www.jeremiahstillings.net/n-tune-music-help-for-git-hub/](url)

**Comment by NTuneMusic** [comment] 2018-08-04 00:50
Thank you, but I am using Elementor Pro for the Social Icons widget.

**Comment by jstillings1** [comment] 2018-08-04 00:58
I updated my post to show what pro offers.

**Comment by arielk** [comment] 2018-08-06 17:39
Can you share with us a link to this page or steps to reproduce this situation?

**Comment by NTuneMusic** [comment] 2018-08-06 18:12
http://brantleycountybands.com

The steps are that I added the social icon widget and this is how it turned out.

**Comment by arielk** [comment] 2018-08-06 18:41
It looks fine, please take a look: http://i.imgur.com/oJQXGZ7.png

**Comment by jstillings1** [comment] 2018-08-06 23:37
Very odd... I actually see more issues then he is even reporting. 
![image](https://user-images.githubusercontent.com/29980804/43746081-1cf63dda-99b0-11e8-9e03-890ef75e7ae2.png)

**Comment by jstillings1** [comment] 2018-08-06 23:38
Both that Icon List and the Social Icons fall under the General Section and I think are part of Elementor free not pro?

**Comment by NTuneMusic** [comment] 2018-08-07 00:56
I think so, but I have Pro too.

**Comment by arielk** [comment] 2018-08-07 14:53
It looks like a conflict with other plugins, please try deactivate one by one and you'll know if it works out. For now I'm closing the issue, feel free to let us know if everything worked out for you.

**Closed by arielk** 2018-08-07 14:53 UTC
Labels: status/needs feedback
