### ISSUE TITLE
Global and individual link styling

### ISSUE THREAD

**Issue by UncloudedStudio** [pojome/elementor#7011] opened 2019-02-08 01:19 UTC
I'm using the "Elementor Hello Theme" and I was looking for the option to set the global link styling in Elementor. I assumed this was a standard/basic feature but apparently it is not. 

It would be great if there was an option to set the global link styling in elementor. And an option for individual link styling incase you need to override the global styling on specific pages etc.

**Comment by shilo-ey** [comment] 2019-02-10 08:41
Duplicate of #3345

**Closed by shilo-ey** 2019-02-10 08:41 UTC
