### ISSUE TITLE
"Menu Cart" widget not translated?

### ISSUE THREAD

**Issue by thread404cp** [pojome/elementor#6423] opened 2018-12-13 11:21 UTC
Hello there,
I am using the "Menu Cart" widget, but the buttons "Show Cart" and "Checkout" are both in English, even if I've set my Wordpress dashboard to my language (Danish). 

Is there any solution to this? I've tried adding a piece of code to functions.php (found on Stackoverflow) but to no avail.

**Comment by bainternet** [comment] 2018-12-13 13:31
Duplicate of #5495

**Closed by bainternet** 2018-12-13 13:31 UTC
