### ISSUE TITLE
Link to existing files and pages

### ISSUE THREAD

**Issue by DaMiGGe** [pojome/elementor#1440] opened 2017-03-08 16:24 UTC
Please add a dialog to buttons and other widget for linking to existing pages and files (pdf etc...)
beaver builder already has samething like this.

**Comment by arielk** [comment] 2017-03-14 18:00
Can you please explain a little more about this feature?
(links or screenshot could be better)

Thanks

**Comment by Twisterking** [comment] 2017-05-05 10:31
I agree with @DaMiGGe! Frankly speaking it is beyond me how you could overlook such an essential, very very basic feature! the thing is that (at least in the free version), widgets like the button only offer a simple url input for the link. But this is **not the standard usecase for any button or link** on a page! Usually you would link to another page of your wordpress site, a certain post or whatever.So please, like any other page builder out there, include some way to link to other existing pages and posts in a simple way!

**Comment by arielk** [comment] 2017-05-05 14:17
Did you mean something like this issue https://github.com/pojome/elementor/issues/255 ?

**Comment by Twisterking** [comment] 2017-05-06 19:34
Yes you are exactly right @arielk something like that. am I missing something here? is an option like that for buttons and stuff already present?!

**Comment by arielk** [comment] 2017-05-07 08:49
No, we're working on it for the next versions.

I merged this issue with another issue #255 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Closed by arielk** 2017-05-07 08:49 UTC

**Comment by climberjase** [comment] 2018-02-12 05:55
Is this available in the commercial version? I just purchased this theme, and I'm shocked that buttons can't link to pages. That's nuts.

**Comment by carlosnpz** [comment] 2018-03-20 02:27
I'm dying for this feature as well...

**Comment by bodhi1970** [comment] 2018-04-13 11:43
This is a thread from last year and the issue is still not fixed in the latest version.

**Comment by DaMiGGe** [comment] 2018-04-13 11:53
agree. it would be much more better for clients ;)

**Comment by matthewwoodard** [comment] 2018-04-20 00:02
Why is this closed, this is a necessary feature.
![elementor aletrue homes](https://user-images.githubusercontent.com/1444663/39024095-9f78cbaa-440c-11e8-8538-f3f762c5eeba.png)

**Comment by olabre** [comment] 2018-05-11 09:34
agree, this is a very importand feature especially when you work with WPML, setting a fixed URL is really old fashioned - please integrate ASAP.

**Comment by amilabandara** [comment] 2018-06-25 17:51
Is this fixed yet? I'm using the pro and I still can't make a link to the pages except putting direct URL. It's very inconvenient. Elementor gives a lot's of flexibility and lots of great features, I wonder why they did not provide this basic feature yet.

**Comment by LeonSkrilec** [comment] 2018-07-23 08:13
I would also like to see this. I come into this when dealing with multilanguage support in custom widgets. Currently every link to internal page needs to be "translated" so it points to the right language. That needs to be solved with "Link to page" functionality, where elementor automatically takes current language page URL.

**Comment by markhagemann** [comment] 2018-07-23 22:50
+1 for this essential feature. It's also a lot more practical for when you're working on a staging site with a different domain than production.

**Comment by evanre** [comment] 2018-07-31 22:02
Guys, hello! Why this issue is abandoned?? You've created a supercar and forget to put a car door handle on it!

**Comment by arielk** [comment] 2018-08-01 06:25
This feature is not abandoned is just merged to another request on the same subject.

See the demo: https://github.com/pojome/elementor/issues/255#issuecomment-406346596

**Comment by olabre** [comment] 2018-08-30 14:01
Hi, linking works now very good, there is only a problem left if you work with WPML. If have tanslated a page and want to modify the link (e.g. English and German language) I only get English pages in the selection box when editing the German page. Is there any solution?

**Comment by Merlin-the-Warlock** [comment] 2020-08-07 19:05
For those still struggling, check out my answer in https://github.com/elementor/elementor/issues/255#issuecomment-670665153.

Easy fix.
