### ISSUE TITLE
Elementor POPUP CLICK 2.4

### ISSUE THREAD

**Issue by Peak14Media** [pojome/elementor#6797] opened 2019-01-19 21:03 UTC
I made a button popup with click instances with the new Elementor 2.4 beta. On homepage I made a button to play a youtube video. When clicking on the button everything works perfectly. But now when you click on any other links the popup for the video comes up and closes automatically.

Example you can click on the main nav link and before it takes you to that page the video popup comes up. Below are my instances settings for the popup.

Condition: Entire Site
Triggers: On Click
Advance Rules: none

Button setting
Link: Popup

![popup](https://user-images.githubusercontent.com/46849714/51432317-d587e780-1bf2-11e9-8fd7-58cd2aae1ab8.jpg)

**Comment by bainternet** [comment] 2019-01-20 09:15
Duplicate of #6798

**Closed by bainternet** 2019-01-20 09:15 UTC
