### ISSUE TITLE
The accordian/Toggle - suggestions for improvements

### ISSUE THREAD

**Issue by rammyleeds** [pojome/elementor#4099] opened 2018-04-14 13:10 UTC
I noticed on the toggle function that there is a button which says "add media" to the toggle content. And that worked a treat. The only thing I couldn't work out was how to split the content box into like two columns with text on the left and image on the right. is there any way of splitting the content in a toggle or an accordian so that you can have columns just like you can have in a text content widget.  You can use the 'add media' button to add an image - but you can't then position it very well like adding columns with text to left and image to the right etc

There is a complicated horrible workaround where you can create your style in a new ordinary section and save it as a template and then put the template ID in the toggle's content box.  But that is ugly and complicated and means editing is horrible too.

Please can you improve things so that rather than just adding text and images/videos to the toggle/accordian content, that we have more control over styling.  That means
1. being able to add column sections to the content area
2. being able to add other widgets to the content area from the main database (like another heading a button and so on
3. Currently the accordian closes one section if you click the other.  In contrast, the toggle section opens one section and leaves the one you opened before still open unless you physically close it.    Both have their merits.   THe accordian feature is cleaner.  The toggle method is great for people who want to print off the whole toggle content section (they just click open to all the indvidual sections).   BUT can't we have BOTH FEATURES in both?

Thanks

Ramesh

**Comment by bainternet** [comment] 2018-04-15 08:11
Duplicate of #2587

**Closed by bainternet** 2018-04-15 08:11 UTC

**Comment by lorrik** [comment] 2019-03-05 00:33
I design "newsletters" for my business and post them on my website for other sales leaders to download and use in their businesses.  I use the accordian or toggle sidebar that displays the "years" and then below the years, the months are listed. I want to be able to click on a monthly newsletter and have the other months for that year to remain viewable.  Currently once you click on a month the whole list of months close and you go back to just seeing the years.  I'm sure this is a simple "fix"?

**Comment by nicholaszein** [comment] 2023-07-31 17:43
Hello there @rammyleeds and @lorrik!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was released with Elementor Core v3.15.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
