### ISSUE TITLE
Full control on archives

### ISSUE THREAD

**Issue by unclerom** [pojome/elementor#4995] opened 2018-07-08 20:32 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**

Creating advanced archive pages.
Example: I am displaying podcast episodes as a custom post type then built an archive page with elementor but cannot insert episode player custom field into each post in the archive using the standard posts widget. While using generatepress the episode player shows by default on archives, either above or below the content maybe because its calling the full the_content?

**Describe the solution you'd like**

An element or section that can be customized with standard elementor widgets, custom fields and dynamic elementor widgets. After creating the desired layout and content of this section it is then set as a loop/repeater section when used on an archive page to list your posts or cpt archive repeating the custom section you created for each post 

**Describe alternatives you've considered**
(probably the more efficient way)
Just expanding the functionality of the current posts widget to allow the selection and display of available post meta/fields

**Comment by bainternet** [comment] 2018-07-10 15:22
Duplicate of #4440

**Closed by bainternet** 2018-07-10 15:22 UTC
