### ISSUE TITLE
Font Icon conflict issue

### ISSUE THREAD

**Issue by artconic** [pojome/elementor#6557] opened 2018-12-28 05:25 UTC
Hello,
I loaded Contact 7 plugins and now I get font issues on 'Elementor' UI/UX = Icons Disappear....
see attached images 4 explanation and plugin list
thank you

![screen shot 2018-12-28 at 12 14 29 am](https://user-images.githubusercontent.com/33140773/50503725-fb2c3180-0a36-11e9-971d-7aa81f715bd9.png)

![screen shot 2018-12-28 at 12 19 36 am](https://user-images.githubusercontent.com/33140773/50503699-d20ba100-0a36-11e9-9cca-73e577fd98cd.png)

![screen shot 2018-12-28 at 12 19 25 am](https://user-images.githubusercontent.com/33140773/50503708-e64f9e00-0a36-11e9-8fb1-b62e57fb8a81.png)

![screen shot 2018-12-28 at 12 19 02 am](https://user-images.githubusercontent.com/33140773/50503712-ea7bbb80-0a36-11e9-9626-4162e4bd8b0d.png)

![screen shot 2018-12-28 at 12 16 49 am](https://user-images.githubusercontent.com/33140773/50503715-eea7d900-0a36-11e9-910b-4d6d92b5e5cd.png)

**Comment by shilo-ey** [comment] 2018-12-30 06:36
@artconic 

You have PLUGIN/THEME conflict somewhere in your install.

Start by deactivating all other add-ons and plugins other than Elementor Core & Elementor Pro (if installed) - then proceed to edit and see if the issue has been resolved. You may need to switch to the default theme to rule out your theme as the cause of the conflict.

If the issue is resolved by following the above action the proceed to reactivate each plugin 1 at a time and checking the editor till you find the one causing the conflict.

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


Thanks.

**Comment by artconic** [comment] 2018-12-30 19:49
Yes. You are Correct. the 'Font Awesome' Plugin. When will Elementor make 'Font Awesome' fonts available for Elementor?

**Comment by shilo-ey** [comment] 2018-12-31 14:18
We don't have specific ETA, but we are actively working on it.

thanks.

**Closed** 2018-12-31 14:19 UTC
Labels: compatibility
