### ISSUE TITLE
Visibility filter for Sections / Columns / Widgets

### ISSUE THREAD

**Issue by bonest** [pojome/elementor#4420] opened 2018-05-11 16:14 UTC
Beaver Builder has some visibility features, where you can decide to show an element (row/column/module) based upon if the user is logged in or not.

And Beaver Builder also has a filter which you can hook into if you want to control if anything should be displayed or not.

You can read about this beaver builder filter here: https://kb.wpbeaverbuilder.com/article/462-hide-row-or-module-when-field-connection-is-empty-themer

I have recently switched from Beaver Builder to elementor, but I really need more control on when a section / columns / widget should be displayed or not. 

In beaver builder I had developed my own filter, that was added to the filter above so I could control visibility of a section which I use for a membership site.

But such a filter does not appear to exist in Elementor or Elementor Pro. 

Membership sites needs to be able to control this, so please add such a filter or add visibility options to sections / columns / widgets. 

The Widget-Options plugin : https://wordpress.org/plugins/widget-options/

Has an elementor beta function that adds a visibility field to elementer / advanced. But this only works on windgets, and not on sections / columns.

I have looked at the code, and I can tell that this may actually be because of a missing section render filter. 

Henrik

**Comment by bainternet** [comment] 2018-05-13 06:52
Duplicate of #4246

**Closed by bainternet** 2018-05-13 06:52 UTC

**Comment by codezz** [comment] 2018-12-30 10:31
Hi, here is a a plugin that allows you to hide/show any Elementor widget based on user role or if it is logged in or not: https://wordpress.org/plugins/visibility-logic-elementor/

Any other suggestions are welcome.

**Comment by nicholaszein** [comment] 2024-04-12 06:05
Hello!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0, and improved with Elementor Pro 3.20.0! 🥳 

You can now use Display Conditions for widgets based on a variety of conditions, including date, time, user role, logged in/out, and others (more to come too). Check the [documentation for the new Display Conditions](https://elementor.com/help/show-and-hide-elements-on-a-page-display-conditions/) for widgets (Pro).

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
