### ISSUE TITLE
Replacing URLs only works on JSON data

### ISSUE THREAD

**Issue by fedeisas** [pojome/elementor#6764] opened 2019-01-16 21:23 UTC
[The tool that replaces URLs](https://github.com/pojome/elementor/blob/master/includes/utils.php#L213-L246) uses this SQL query that only affects rows with JSON values:
```
$rows_affected = $wpdb->query(
    "UPDATE {$wpdb->postmeta} " .
    "SET `meta_value` = REPLACE(`meta_value`, '" . str_replace( '/', '\\\/', $from ) . "', '" . str_replace( '/', '\\\/', $to ) . "') " .
    "WHERE `meta_key` = '_elementor_data' AND `meta_value` LIKE '[%' ;" ); // meta_value LIKE '[%' are json formatted
```

In my database I have rows like:
```
mysql> select * from wp_postmeta where meta_value like '%http://%' limit 1\G
*************************** 1. row ***************************
   meta_id: 518
   post_id: 8
  meta_key: _elementor_page_settings
meta_value: a:6:{s:21:"background_background";s:7:"classic";s:16:"background_image";a:2:{s:3:"url";s:82:"http://abcdef.somesite123.com/uploads/sites/1234/2016/01/XXXXXXXXXX_YYYYYYYYYY.jpg";s:2:"id";i:47;}s:17:"background_repeat";s:9:"no-repeat";s:15:"background_size";s:7:"contain";s:10:"hide_title";s:3:"yes";s:19:"background_position";s:10:"top center";}
1 row in set (0.00 sec)
```

Is my database holding an old data format? Or the tool is just not handling the serialized data and it's a bug?

The tool was added in [this commit](https://github.com/matipojo/elementor/commit/7ed8672fd31c6c48c6929cbaf801b277d9f01318) so maybe @matipojo can help. It was later refactored in [this PR](https://github.com/pojome/elementor/pull/4693) but the gist of it didn't change.

PS: this project have been using Elementor for a while, maybe we could have an old Elementor format that did not migrate properly.

**Comment by fedeisas** [comment] 2019-01-16 21:41
I solved it using https://developer.wordpress.org/cli/commands/search-replace/ if anyone ever faces this problem.

**Comment by shilo-ey** [comment] 2019-01-17 07:43
@fedeisas 

Your data is in old format as you mentioned.

In order to change the format, we created the update mechanism which converts your DB records to the new format and then the tool is working for you.

Glad you managed to work it out, but let us know which version are you using and if you transferred your database manually before you used this tool. 
This is essential for us to know if there was an issue with the DB update system.


Thanks.

**Comment by fedeisas** [comment] 2019-01-17 19:13
Is this information good enough?

```
== Server Environment ==
    Operating System: Linux
    Software: nginx/1.14.0
    MySQL version: 5.7.16
    PHP Version: 7.2.9-1+ubuntu16.04.1+deb.sury.org+1
    PHP Max Input Vars: 1000
    PHP Max Post Size: 250M
    GD Installed: Yes
    ZIP Installed: Yes
    Write Permissions: There are some writing permissions issues with the following directories/files:
         - WordPress root directory
    Elementor Library: Connected

== WordPress Environment ==
    Version: 4.9.8
    Site URL: https://sub.domain.com
    Home URL: http://sub.domain.com
    WP Multisite: Yes
    Max Upload Size: 50 MB
    Memory limit: 128M
    Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
    Language: en-US
    Timezone: 0
    Debug Mode: Inactive

== Theme ==
    Name: Theme
    Version: 1.0
    Author: Me
    Child Theme: No

== User ==
    Role: 
    WP Profile lang: en_US
    User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

== Active Plugins ==
    WordPress Importer
        Version: 0.6.4
        Author: wordpressdotorg


== Network Plugins ==
    Akismet Anti-Spam
        Version: 4.0.8
        Author: Automattic

    Elementor
        Version: 2.1.8
        Author: Elementor.com

    Elementor Pro
        Version: 2.1.1
        Author: Elementor.com

    Gravity Forms
        Version: 2.3.3
        Author: rocketgenius

    Scheduled Post Trigger
        Version: 2.21
        Author: Jennifer Moss - Moss Web Works

    Simple Custom CSS and JS
        Version: 3.18
        Author: SilkyPress.com

    Simple Page Sidebars
        Version: 1.2.1
        Author: Cedaro

    User Role Editor Pro
        Version: 4.47.2
        Author: Vladimir Garagulia

    W3 Total Cache
        Version: 0.9.7
        Author: Frederick Townes

    Wordfence Security
        Version: 7.1.10
        Author: Wordfence

    Yoast SEO Premium
        Version: 3.8
        Author: Team Yoast


== Debug ==
    Errors: 
        TypeError: Cannot read property 'jQuery' of undefined
            at https://sub.domain.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.4 - 2:31339
            2017-09-20 18:02 +00:00

        TypeError: Cannot read property 'jQuery' of undefined
            at https://sub.domain.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.7.4 - 2:154283
            2017-09-20 18:02 +00:00
            x 4 times
```

**Comment by shilo-ey** [comment] 2019-01-20 15:05
@fedeisas Thanks.

**Closed by shilo-ey** 2019-01-20 15:05 UTC
Labels: status/needs feedback

**Comment by fedeisas** [comment] 2019-01-20 15:52
So I have old data or what? Should I do something about it?

**Comment by fedeisas** [comment] 2019-01-23 14:44
@shilo-ey you asked for feedback to troubleshoot why I have an old data format and then closed the issue. Is there any way I can migrate my data to the new format?

**Comment by shilo-ey** [comment] 2019-01-23 14:52
@fedeisas The issue probably caused by manual manipulations on the database, and that caused the migration issues (not a problem with the upgrades mechanism).

Your data seems to be in the new format.

thanks.
