### ISSUE TITLE
More (general) styling options

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#4427] opened 2018-05-12 06:20 UTC
Since we try to be independent from theme settings, we need more general styling options as default settings. We need for every h1...h6 (not grouped in h1...h3 and h4...h6), p etc. the full range of typographie, text color and (in case of h1...h6) text shadow for every of the 3 device types. We also need seperate settings for link and link : hover. So there would be less work for styling every widget on a website. In many cases, it would save time significantly.

**Comment by bainternet** [comment] 2018-05-13 06:37
Duplicate of #1324

**Closed by bainternet** 2018-05-13 06:37 UTC
