### ISSUE TITLE
Style Template Widgets

### ISSUE THREAD

**Issue by buffdownunder** [pojome/elementor#5827] opened 2018-09-28 23:12 UTC
- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to use a small selection of widgets that have the same styling all over the site. Just like good old CSS style sheets that separated content from looks.
Global widgets or templates currently don't do it for me because the content always changes. I just want to control the styles globally.

I just realised that Elementor offers copy/paste of widget styles [https://elementor.com/introducing-copy-paste/]. This means that widget styles can be bundled and transferred from one widget to the other.

**Describe the solution you'd like**
-I would love to have Style Templates for widgets. Just like global widgets are implemented.
-You save a widget as a style template and then you find it in an additional Group under the "Elements" tab or maybe in the "Global Widgets" tab or maybe as a new tab "Custom".
-The UI would be the same as a global widget.
Only difference is that if you drag this widget into your post/page there is no content pre-filled. Just the styles are pre-filled.
If you change the style you get asked if you want to apply the style globally or if you want to unlink the widget.
-Bonus: You can set user rights so front-end developers can make sure, their clients can only see the widgets that have a style template and they can not change the style.
-Bonus 2: They have their own style sheet so if posts or pages only contain style template widgets then there is only one CSS file loaded.

**Describe alternatives you've considered**
I have considered shortcode and already posted a feature request about this. I consider this solution more elegant.

**Additional context**

**Comment by bainternet** [comment] 2018-10-02 08:31
Duplicate of #965

**Closed by bainternet** 2018-10-02 08:31 UTC

**Comment by buffdownunder** [comment] 2018-10-02 11:27
I had a look at the other thread and I don’t consider it a duplicate.

To clarify my feature request I’m looking more beyond css and default settings. I’m requesting a global widget without the content elements. 

If I look at the posts widget, for example, my feature request would exclude only the query section. All other settings would remain untouched.

Hope this helps to clarify the request. 

From a UI point of view, I wouldn’t be interested in defining presets or applying presets to widgets via dropdown menues or the sorts.
