### ISSUE TITLE
Bugs in new elementor 2.1 beta

### ISSUE THREAD

**Issue by mauritzbotha92** [pojome/elementor#4863] opened 2018-06-25 18:58 UTC
Hi,

Couple of issues I have seen with a few minutes of playing.

I am no longer able to copy the colour codes of any elements on the page using ctrl + c keyboard shortcuts, however, I can still copy it with the mouse using the context menu by right clicking.

The other issue is, some widgets, for example, images and text are no longer editable. I am able to edit the column or section they sit in, but not the actual element itself. If I click on the icon to edit the element, the menu bar on the left goes completely blank. I have attached a screenshot of this.
![unnamed](https://user-images.githubusercontent.com/39256352/41869758-4e3ca44a-78ba-11e8-9e83-7247e6133d74.png)

Thanks.

**Comment by cavalierlife** [comment] 2018-06-25 19:56
I also have the problem of being unable to edit an image widget, and the sidebar editor goes blank for me as well.

**Comment by bainternet** [comment] 2018-06-26 08:37
Duplicate of #4861

already reposted

**Closed by bainternet** 2018-06-26 08:37 UTC
