### ISSUE TITLE
[Feature Request] Allow selection of single post template when adding new content via editor.

### ISSUE THREAD

**Issue by digitalinksol** [pojome/elementor#4836] opened 2018-06-22 20:20 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Will allow me to choose one of many single post templates when building out a post.

**Describe the solution you'd like**
I would like to build many vastly different Single Post templates via elementor and allow my team to be able to choose which template they'd like to use from a picklist of some sort.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by black-eye** [comment] 2018-06-23 07:45
+1

**Comment by bainternet** [comment] 2018-06-25 08:06
Duplicate of #4611

**Closed by bainternet** 2018-06-25 08:06 UTC

**Comment by teolaz** [comment] 2018-07-11 09:00
@bainternet 3 (same) requests and still no time to think about a solution ? :D
