### ISSUE TITLE
Make Global Colours and Fonts useful

### ISSUE THREAD

**Issue by willcitizen** [pojome/elementor#5206] opened 2018-07-25 09:12 UTC
The ability to switch out entire graphic design templates/colour and typography schemes is for me what really makes framework/pagebuilder type design an attractive prospect.

the current implimentation of Global fonts and colours provides very little control over their deployment and really doesn't achieve this goal.

I would really love to see an implimentation of something like the colour schemes used in the gantry framework, or the ability to switch out entire themes ala DT Baker's Stylepress extension which appears to have been abandoned.  extending the default colour and fonts that currently exist and then making all widget font/color choices dynamic (so I could choose $primary, $secondary) as the color on a widget) might be a way to do this.

I understand that these things can be achieved with sass variables and so forth, but then we are not really living the dream of being able to visually build powerful reusable components for our sites, without writing any custom code :)

Thanks
Will

**Comment by bainternet** [comment] 2018-07-25 09:22
Thanks for the feedback,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

**Comment by bainternet** [comment] 2018-07-25 09:22
Duplicate of #1324

**Closed by bainternet** 2018-07-25 09:22 UTC
