### ISSUE TITLE
ACF Repeater field templates, Archive Post Item Templates, Dynamic templates

### ISSUE THREAD

**Issue by seanvandermolen** [pojome/elementor#4913] opened 2018-07-01 18:27 UTC
This would be similar to the ability of Divi Layout injector to template archive pages but also the post loop

Could design a template that would loop ACF repeater info and display on a page

Essentially you could create skins that had elements like post title, post meta, short description, description.  All those pieces could be placed and styled in a template.  For ACF it there would be an element that let you position repeater fields that could be styled.

Dynamic templates:
For example, a blog that would alternate the template used based on function such as

Tags or custom fields that direct which template to use
Alternating posts (for example, the first post would use a template that displays an image to the left, the next the image is on the right)

**Comment by bainternet** [comment] 2018-07-02 12:06
Duplicate of #4440

**Closed by bainternet** 2018-07-02 12:06 UTC
