### ISSUE TITLE
Improvement of menu to Elementor Megamenu with elementor templates

### ISSUE THREAD

**Issue by neoset** [pojome/elementor#5040] opened 2018-07-12 18:40 UTC
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Request to improve the menu with a Megamenu using the elementor page templates to create the drop-down of each menu item and sub-menu.
Show when there are new entries in the blog or products on offer in the store with "new" and "offer" icons.
Thank you.

**Describe the solution you'd like**
From the appearance / menu section, you can activate the Elementor Megamenu and generate the dropdowns from elementor templates for menus and submenus.

**Describe alternatives you've considered**

**Additional context**
![menu](https://user-images.githubusercontent.com/5489630/42652266-2a08e1fa-8612-11e8-9a52-64519145010d.png)
![menu2](https://user-images.githubusercontent.com/5489630/42652273-3056117c-8612-11e8-9358-24162c246591.png)
![menu3](https://user-images.githubusercontent.com/5489630/42666802-993e163c-8647-11e8-8a35-082184542068.png)

**Comment by bainternet** [comment] 2018-07-15 08:28
Duplicate of #3275

**Closed by bainternet** 2018-07-15 08:28 UTC

**Comment by rumyantsekov** [comment] 2018-12-28 17:00
I would love to see this integrated, instead of using plugins that add the widget to the Elementor list: [https://www.megamenu.com/documentation/elementor/](url)
