### ISSUE TITLE
Gradient background button

### ISSUE THREAD

**Issue by toton333** [pojome/elementor#5818] opened 2018-09-28 08:21 UTC
Gradient background of buttons is necessary in any modern styling of website. Currently the workaround is making button background 100% transparent and then use the column's gradient background.
Also transition duration doesn't work on gradient background on hover.
So a gradient button background and transition effect on gradient background(ofcourse gotta use alternative way, as it is not supported atm) would set elementor on a pretty high level from the rest.

**Comment by arielk** [comment] 2018-09-30 12:34
Duplicate of #3142

**Closed by arielk** 2018-09-30 12:34 UTC
