### ISSUE TITLE
API: Detect if code is running in the editor or the actual page

### ISSUE THREAD

**Issue by KimchaC** [pojome/elementor#4538] opened 2018-05-24 15:42 UTC
## Prerequisites
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I have created a plugin that extends the button element to wrap it in a shortcode to show a Thrive Leads 2step popup signup using the render_content hook. 

The shortcode causes issues while editing the page, so I would like it to only execute when a user views the final page.

**Describe the solution you'd like**
I'd like to be able to check if my plugin is currently in edito mode or not. Something like 
`if(is_elementor_editor() == true) { ... }`

**Describe alternatives you've considered**
I have come up with this code as an alternative, but it seems a bit dirty and I think other addon developers would benefit from a solution that comes with Elementor by default.

``` php
$elementor_editor = false;
function is_elementor_editor() {

	global $elementor_editor;
	return $elementor_editor;
}

add_action( 'elementor/editor/before_enqueue_scripts', function() {
	global $elementor_editor;

	$elementor_editor = true;
} );
```

**Additional context**
None

Thank you for your consideration and your amazing work

**Comment by bainternet** [comment] 2018-05-27 14:34
Duplicate of #4491

see comment: 
https://github.com/pojome/elementor/issues/4491#issuecomment-390666686

**Closed by bainternet** 2018-05-27 14:34 UTC
