### ISSUE TITLE
Allow Image from 3rd party service such as imgur.com

### ISSUE THREAD

**Issue by minhpara** [pojome/elementor#4463] opened 2018-05-15 12:55 UTC
In the 2.0 version, Elementor allows only image stored in wp hosting, which is a annoying limitation.
I suggest Elementor has a textbox so that users can type the absolute href for the image.

**Comment by bainternet** [comment] 2018-05-15 13:47
Duplicate of #413

next time please follow guidelines to opening a new issue/feature request.

**Closed by bainternet** 2018-05-15 13:47 UTC
