### ISSUE TITLE
WordPress Multisite with Mapped Domain: Uncaught ReferenceError && Uncaught DOMException

### ISSUE THREAD

**Issue by ianmubangizi** [pojome/elementor#3891] opened 2018-03-25 21:44 UTC
I seem to be having an issue running Elementor on a WordPress Multisite installation with domain Mapping for a subdirectory site - actually I changed to the subdir method thinking it will fix the cross-origin issue, coming from the sub-domain method but it still seems that Elementor is being served an iframe from different ports and I don't want to tamper with my config for security reasons. Plugins are not the issue here because I have nearly no plugins only a theme Domain Mapping and Elementor
I Know am using the Beta but I get the same problem on 1.9.8.

**Uncaught ReferenceError: butterbean is not defined**
    at post.php?post=11&action=elementor:6793
00
Love using Elementor? Join our growing community of Elementor developers: https://github.com/pojome/elementor
www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-99097461-2&cid=1402534580.1521977301&jid=749231473&_v=j66&z=2046016904 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
editor.min.js?ver=2.0.0-beta4:2 

**Uncaught DOMException: Blocked a frame with origin** "https://main.domain" f**rom accessing a cross-origin frame.**
    at n.onPreviewLoaded 
(https://main.domain/subdir-dmoain/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.0-beta4:2:93189)
    at HTMLIFrameElement.dispatch 
(https://main.domain/subdir-dmoain/wp-admin/load-scripts.php?c=1&load%5B%5D=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.4:9:12444)
    at HTMLIFrameElement.r.handle 
(https://main.domain/subdir-dmoain/wp-admin/load-scripts.php?c=1&load%5B%5D=underscore,jquery-core,jquery-migrate,backbone,shortcode,utils,wp-util,wp-backbone,media-models,moxiejs,plupload,wp-plupload,jqu&load%5B%5D=ery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.4:9:9173)

**Comment by bainternet** [comment] 2018-03-26 09:34
@ianmubangizi 

First issue: "butterbean is not defined" is coming for either your theme or a 3rd party plugin, elementor has no `butterbean` in it code.

please make sure you don't have JS/PHP/PLUGIN/THEME conflict somewhere in your install.

Start by deactivating all other add-ons and plugins other than Elementor Core & Elementor Pro (if installed) - then proceed to edit and see if the issue has been resolved. You may need to switch to the default theme to rule out your theme as the cause of the conflict.

If the issue is resolved by following the above action the proceed to reactivate each plugin 1 at a time and checking the editor till you find the one causing the conflict.

If not, Please contact our support at support@elementor.com for guidance in resolving this issue.

**Closed by bainternet** 2018-03-26 09:34 UTC

**Comment by ianmubangizi** [comment] 2018-03-26 14:38
@bainternet 
What about the cross-origin issue, I tried adding [ "allow-access-from domain= *" ], to my .htacces file but it didn't work, I am not sure of how to fix this because am unable to use Elementor, but I aware this is just caused by the different port numbers serving the same file.

**Comment by airsidworld** [comment] 2019-03-26 10:35
@ianmubangizi 
Hello,
Did you resolved your issue please? 
I have the same one :(

**Comment by LeodanDesign** [comment] 2019-06-09 23:14
I had the same issue today. I found this was an issue on multisite when running through Nginx without apache proxy (I think that was what was causing it). I managed to fix it by forcing the elementor_template post type to move from "draft" to "publish" immediately on creation using the wp_insert_post_data filter.

You can access the snippet I created to fix the issue (with more detailed notes) at [https://bitbucket.org/snippets/LeodanDesign/7eGzen](url)

and here:

```
<?php
apply_filter('wp_insert_post_data', 'fix_elementor_draft_issue', 10, 1);

function fix_elementor_draft_issue($data){
    if($data['post_type'] == 'elementor_library' && $data['post_status'] == 'draft'){
        $data['post_status'] = 'publish';
    }
    return $data;
}
```
Alternatively if you want to do this the manual way, or you have created and then hit the "no load" situation, if you go to "Saved Templates" in the dashboard, and manually publish the template (using the standard WP edit post procedure, which should then leave you free to edit as normal.
