### ISSUE TITLE
Add Condition for Responsive Breakpoints

### ISSUE THREAD

**Issue by vongoh** [pojome/elementor#4869] opened 2018-06-26 00:28 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The banner version of some brands logos is horizontally pretty wide.  This means that at tablet and mobile screen sizes,  the logo shrinks down t0o small to be seen and read.

A design hack around this is to use a square version of the brand logo on smaller device sizes.

Currently, I'm using hooks - along with the 'Hide on Desktop' - 'Hide on Tablet' - Hide on Mobile' -  functions to swap between different header sections, with a different logo versions ... one for desktop (wide logo) and one for small screens (with a square logo).

**Describe the solution you'd like**
We should be able to do this kind of thing completely in Elementor 2.0 now - by setting a Display Condition to 'Desktop' or 'Tablet' or 'Mobile'.   Then we would have total control over where to display different headers (and footers, or any template) depending on design and functionality requirements of the project.

This is only one use case that I just ran into, but it would open the doors to a lot more responsive flexibility

**Comment by bainternet** [comment] 2018-06-26 08:55
Duplicate of #4413 

I merged this issue with #2355, which is on the same subject so we could deal with it more efficiently.
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by bainternet** 2018-06-26 08:55 UTC
