### ISSUE TITLE
Feature Request: Choose Header/Footer/Single Page Templates from Page Settings

### ISSUE THREAD

**Issue by katart** [pojome/elementor#5029] opened 2018-07-11 15:04 UTC
Elementor Pro does a great job of allowing for Conditional Display settings for my Header, Footer or Single Page Templates. 

If my site has multiple Single Page Templates or multiple Header/Footer options, it would be nice to have the ability to choose those Template options on the page I am editing within Elementor. I would set a Default within the Elementor Template, but there would be an option to "override" those settings on each individual page (most likely in the Page Settings screen).

Would it be possible to allow us to select the Header, Footer or Single Page Template from the Page Settings screen?

**Comment by bainternet** [comment] 2018-07-12 07:22
Duplicate of #4611 #4654

**Closed by bainternet** 2018-07-12 07:22 UTC
