### ISSUE TITLE
Allowing Multiple Inner Sections

### ISSUE THREAD

**Issue by frozenfire98** [pojome/elementor#5842] opened 2018-10-02 21:54 UTC
- [X ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Please allow us to drag the inner section element INTO an inner section element. Sometimes we have a page split into two columns, but we then want to add columns inside of one of those.

For example, I am trying to re-create this page on Wordpress from Weebly. Notice the Location section. I have the stamp of excellence beside the Reservations button. On Wordpress with Elementor, I can't do that, I have to have them on top of each other, taking up more space lengthwise, and leaving extra white space all around it.

http://www.dreamingdirty.com/event.html

I feel like this would be a great option to add, as many page could benefit from it that utilize buttons, various menus, photos with text content underneath, etc. Being able to add multiple columns inside of larger columns would help us deisng our pages down to the last iota, utilizing all of the free space available and removing some of the empty space that happens with everything being stacked on top of each other all the time.

**Comment by bainternet** [comment] 2018-10-03 06:40
Duplicate of #2218

**Closed by bainternet** 2018-10-03 06:40 UTC
