### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by Federicro** [pojome/elementor#6853] opened 2019-01-23 15:10 UTC
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Elementor PRO forms is still not suitable as a registration form. This is frustrating, Elementor Team please make this possible: **make the form widget able to create/update WP users**.

**Describe the solution you'd like**
At the moment I found a simple plugin, Easy Registration Forms [https://www.easyregistrationforms.com] that gives the possibility of **mapping every form field with a META KEY** (see screenshot below). In this way it is possible to send the field entry to a specific WP Users' database field (for example 'billing_first_name', but also works with custom fields).

Another big plus is that with the existing webhooks option of the Elementor Forms widget it would be possible to send the user's details to an external service such as google sheets as soon as a new user is created. This would be just great for non coders like me, it's something not possible at the momenent.

**Describe alternatives you've considered**
Coding unfortunately is not an option for me.

**Additional context**
Here a plugin settings screenshot:

![immagine](https://user-images.githubusercontent.com/39328835/51614928-ef913500-1f26-11e9-9499-b0c4fdc4d9ef.png)

**Comment by shilo-ey** [comment] 2019-01-23 15:45
Duplicate of #5184

**Comment by shilo-ey** [comment] 2019-01-23 15:46
@Federicro 
I merged this issue with  #5184, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by shilo-ey** 2019-01-23 15:46 UTC
