### ISSUE TITLE
Global Styles

### ISSUE THREAD

**Issue by mskks64** [pojome/elementor#5640] opened 2018-09-01 22:37 UTC
Global styles would be a great addition to Elementor's already awesome list of features. The ability to copy and paste styles is pretty close to what I/others want, but it would be great if you could create a system for adding global styles. Right now the only way to accomplish a truly global style would be to go into the module and add a class then add that css to your website. I have no problem writing css, but it would be a great additional feature to add that many users would appreciate. When I build websites I use a lot of the same styling throughout the website. If I end up changing it on one page I need it to change on all plages. Thank you for considering this!

## Prerequisites

- [ X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**Comment by bainternet** [comment] 2018-09-02 09:08
Duplicate of #965

**Closed by bainternet** 2018-09-02 09:08 UTC
