### ISSUE TITLE
[Version 2.0.0-beta1 ] error after submission contact form

### ISSUE THREAD

**Issue by Basilou38** [pojome/elementor#3866] opened 2018-03-23 12:35 UTC
Hi,

[Elementor - Pro version: Version 2.0.0-beta1 ]
[Elementor - Free version: Version 2.0.0-beta4 ]

I have a problem with the contact form, I get an error message (see screenshot) after submitting the form. I tried to disable my cache plugin and remove the captcha field, same problem. An idea ? (I use the beta version of elementor)

screenshot of the error:
http://zupimages.net/viewer.php?id=18/12/too2.jpg

**Comment by Basilou38** [comment] 2018-03-24 12:22
there is a problem with the form of the beta version, because I delete the beta version and no problem

**Comment by bainternet** [comment] 2018-03-25 07:08
@Basilou38 

Is the form inside a modal??

**Comment by bainternet** [comment] 2018-03-25 08:33
Duplicate of #3826 
https://github.com/pojome/elementor/issues/3826#issuecomment-375670405

**Closed by bainternet** 2018-03-25 08:33 UTC
Labels: Waiting For Input

**Comment by bainternet** [comment] 2018-03-26 09:54
Well then its probably a conflict with that 3rd party plugin, please try without.

**Comment by Basilou38** [comment] 2018-03-26 09:56
I delete the beta, no problem. I use the theme OceanWP with its plugin "Ocean Modal Window"

**Comment by Basilou38** [comment] 2018-03-26 13:39
@bainternet I also tried without modal, the problem is still there, even with the final version elementor, how to solve this problem? Because we can not contact me
