### ISSUE TITLE
Feature Request: Mobile Navigation Layout Options

### ISSUE THREAD

**Issue by get8bit** [pojome/elementor#5039] opened 2018-07-12 17:18 UTC
Currently, there is only one format for mobile navigation. The menu drops down and the text is either centered or aligned left. I can't even get it to align right. You can see what I mean here: http://anchorpointdigital.com/

I was thinking it would be awesome to have an option for the navigation to appear from left or right side (not just straight down) and allow the text to align right also. It looks much more modern.

Examples:
https://braveux.com/
http://devinholmesdesign.com/

**Comment by bainternet** [comment] 2018-07-15 08:29
Duplicate of #3275

**Closed by bainternet** 2018-07-15 08:29 UTC
