### ISSUE TITLE
Bug with Posts Widget Pagination

### ISSUE THREAD

**Issue by PrashGupta** [pojome/elementor#4703] opened 2018-06-09 06:36 UTC
I am a Pro User & had raised a ticket with the Elementor Support Team, who inspected my environment & has then asked me to report the issue here.

There are 2 issues with Pagination in the Posts Widget

1. Clicking on Posts Pagination goes to the next page (as desired), but it reloads the whole page and goes to top of the page. This behaviour is seen on all types of devices - desktop, tablet as well as mobile. This is really very frustrating, when the widget it towards the end of a long page

2. Only the current page shows up on mobile & tablet in the pagination area. So if you are in Page1, it does not show any link for Page 2 on mobile/tablet - but shows all pages on the desktop

It is really quite bothering that these basics are not in place. Request resolution at the earliest possible. I am attaching the system info file for my environment

Regards
Prashant

[system.txt](https://github.com/pojome/elementor/files/2086713/system.txt)

**Comment by bainternet** [comment] 2018-06-09 20:15
@PrashGupta 

1) Is not really an issue or something that needs fixing, simply position your posts higher up the page.

2) you are saying that the pagination is missing on mobile?  can you provide a screenshoot?

**Comment by PrashGupta** [comment] 2018-06-10 06:01
Hi Raz

I'm afraid, I do not agree with you on point1. It is most certainly an
issue.
Let me explain why.
On each of our product pages, we are first explaining the product features,
benefits etc - and then towards the end of the page, we show different ways
of using the product thru blog posts (using the posts widget). We cannot
follow your advice of moving the posts widget on top of the page - for
obvious reasons, as explained.
Moreover, this is a standard functionality offered by other page builders
and do not think Elementor should continue with this bug. Hence, would
request that this is fixed in future releases.

On point2 - attaching screenshots of desktop version & the mobile version
of the same area of the page. As you can see, on the desktop version we can
see pages 1,2 & 3
Whereas on Mobile version, only the current page number can be seen

Regards
Prashant

**Comment by bainternet** [comment] 2018-06-10 08:55
@PrashGupta 

screenshot is missing.

**Comment by PrashGupta** [comment] 2018-06-10 09:02
Sorry, my mistake. Attaching it now


![desktop](https://user-images.githubusercontent.com/40087099/41200049-0a2bc976-6cbb-11e8-9ffe-b86097cae6a1.jpg)
![mobile](https://user-images.githubusercontent.com/40087099/41200050-0a6427bc-6cbb-11e8-8724-83d5c230b090.jpg)

**Comment by bainternet** [comment] 2018-06-10 09:58
Thanks for clarifying, but it's like that by design, and not a bug.


I merged this issue with  #4345, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by bainternet** 2018-06-10 09:58 UTC
Labels: status/needs feedback

**Comment by aliasbody** [comment] 2018-07-05 18:46
> Clicking on Posts Pagination goes to the next page (as desired), but it reloads the whole page and goes to top of the page. This behaviour is seen on all types of devices - desktop, tablet as well as mobile. This is really very frustrating, when the widget it towards the end of a long page

Sorry for asking this on a closed issue but how is the "goes to top page" not an issue?
For me, either it updates the page and uses a section ID to scroll to the place or it just uses ajax. But right now we doesn't make any sense for the design of the website to be modified just because of this.

**Comment by PrashGupta** [comment] 2018-07-05 19:07
Exactly. This is certainly an issue, as it does make sense to have the
default design this way. But the elementor team neither acknowledges it nor
provides a logic for having this intentionally as default behavior

**Comment by aliasbody** [comment] 2018-07-05 19:30
@PrashGupta In the meantime you can do something like this. It's a simply hack without having to edit the elementor files directly:

```
  jQuery('div.elementor-widget-posts').each(function(_, widget) {
    // Add ID to the posts Widget (using the data-id)
    jQuery(widget).attr('id', jQuery(widget).attr('data-id'));

    // Add the id to the pagination URL
    jQuery('a.page-numbers', widget).map(function(_, link) {
      jQuery(link).attr('href', jQuery(link).attr('href') + '#' + jQuery(widget).attr('id'));
    });
  });
```
What this does is simply use the data-id of every post widget as an ID and then use it to navigate to the location by simply adding that value to the href url of the pagination.

Two small notes:
1. It's buggy
2. It's only enabled for posts widgets
3. It's only enabled for "Numbers" pagination

But try it out and let me know, I can see if I can update this. In the meantime I'll check if there a is a way to just fix this directly in code and send a request.

**Comment by PrashGupta** [comment] 2018-07-06 01:13
Thanks so much Luis. Let me try implementing this

**Comment by jainnidhi** [comment] 2018-08-08 12:33
Hello @aliasbody ,
I have tried the solution that you given.
Its not working for me.

Can you please help me out?

**Comment by markd91** [comment] 2018-10-26 18:46
@aliasbody ++ I would also like help on setting this up! I'm not sure where to put that code...

**Comment by aliasbody** [comment] 2018-10-26 19:04
@jainnidhi and @markd91 Sorry I didn't mentioned that but you need to put that code into a javascript library loading, here I'm using a jQuery example that should work with the outdated version of jQuery that comes natively in Wordpress.

So for example you just need to

1. Create a js file (called **main.js** for example) in a folder, for better organization like this: **js/main.js** and add to it that code I wrote in my earlier comment.
2. Enable that file to be loaded by added the following code to your **functions.php** file:
```
// List Scripts to Load
function my_theme_scripts() {
  // jQuery
  wp_enqueue_script('jquery');

  // Main (JS)
  wp_register_script('main-js', get_template_directory_uri() . '/js/main.js', false, null, true);
  wp_enqueue_script('main-js');
}
```
3. Load the function (which loads the scripts) by doing in the same **functions.php** file:
```
// Load Scripts
add_action('wp_enqueue_scripts', 'my_theme_scripts');
```

Please be aware that this work at the time of writing, so I'm not sure if this works nowadays with the current versions of Elementor.

**Comment by KazemirLms** [comment] 2019-02-09 20:54
I also use the pro version. This is a very, very cruel BUG. To switch to the slider you need to reload the entire page. Please take steps to eliminate this trouble.

**Comment by Fubart** [comment] 2020-01-23 15:43
Still no fix? :(

For the moment I use AnyWhere Elementor Pro where the post/carrouselwidget reloads as it should be...

**Comment by saumi785** [comment] 2020-04-03 02:28
I am also having the same problem. Does anyone find the solution?

**Comment by trezbit** [comment] 2020-04-14 21:35
A possible workaround is to create an anchor on the page marking the head of the posts widget then to use @aliasbody's custom js to jump to the newly added anchor: #archive-top-posts . 

```
  jQuery('div.elementor-widget-posts').each(function(_, widget) {
    // Add the id to the pagination URL
    jQuery('a.page-numbers', widget).map(function(_, link) {
      jQuery(link).attr('href', jQuery(link).attr('href') + '#archive-top-posts');
    });
  });
```

**Comment by phil-beachler-id** [comment] 2021-05-06 14:59
Greetings, writing in 2021 and this still appears to be an issue. Whether or not the team chooses to acknowledge this as a 'bug', it still falls under the column of poor UX and is done better by myriad other plugins and/or platforms. Some amazing features are coming out as of late, but it would be nice to see some visibility on UX issues like this.

**Comment by Mauricio-Urrego** [comment] 2021-05-12 17:07
Just dropping in here to add to the list of people requesting this. :) Maybe we can get this issue opened back up?

**Comment by webinfinitynz** [comment] 2021-07-26 21:31
Just to add a +1 to this issue.

Moving the user all the way back to the top of the page on a Pagination click is very bad UX.

Also, the Pagination menu needs UX improvements;
1. There isn't an option for 'Start' & 'End' items.
2. When you get to the last page, 'Next' is still shown (not clickable but I've had a client complain about this). The ideal solution is to hide the 'Next' menu item when the user reaches the last page.

**Comment by RonR-WebDesign** [comment] 2021-12-15 19:36
Pagination definitely needs some work.  It should NEVER work like this - taking the viewer to the top of the page.

**Comment by tamal-sen** [comment] 2022-06-15 09:36
Folks, chiming in here to add some notes.
Current pagination implementation is route-based (e.g. the next page button is a new page `<URL>/page/2`). This is really counter-intuitive because you want users to show 3 more posts at the expense of reloading the whole page and it also bring the user to the top of the page (again, because it is route-based).
The potential solution I can see is Elementor introducing AJAX-based pagination in Posts widget. The foundation is already there with the "Load More" pagination, it is already ajax-based. 

Would love to hear some thoughts @bainternet

**Comment by SamPourrahim** [comment] 2023-05-09 22:51
It's 2023 and this bug still exist..

**Comment by GuillaumeWld** [comment] 2023-07-12 12:20
incredible bug...
This fix works for me : 

`function fix_elementor_load_more_pagination( $string, $type ){

    $elements = explode("/", $string);
    $last_elem = end($elements);

    if (is_numeric($last_elem)) {
        array_pop($elements);
        $link = implode("/", $elements)."page/".$last_elem;
        return $link;
    } else {
        return untrailingslashit($string);
    }
}

add_filter('user_trailingslashit', 'fix_elementor_load_more_pagination', 70, 2);`
