### ISSUE TITLE
additional functionality of the "Posts" widget

### ISSUE THREAD

**Issue by zheleznyakov** [pojome/elementor#4740] opened 2018-06-13 07:10 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The main page of my site shows a list of posts with the "Posts"widget. I would like to see the number of views under each post. This can be achieved with third-party plugins, but they are not suitable for elementor.

**Describe the solution you'd like**
It would be nice to be able to add an icon with the number of views under each post.

**Additional context**
![2018-06-13_10-06-39](https://user-images.githubusercontent.com/10277865/41335531-c2f63d64-6ef1-11e8-8398-b1107f1f4ed1.png)

**Comment by bainternet** [comment] 2018-06-13 07:15
Duplicate of #4440

**Closed by bainternet** 2018-06-13 07:15 UTC
