### ISSUE TITLE
Form alignment

### ISSUE THREAD

**Issue by lucafagherazzi** [pojome/elementor#5659] opened 2018-09-04 10:18 UTC
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
The problem concerns the acceptance and checkbox fields. With long texts requiring multiple lines, the alignment of texts is lost.

**Describe the solution you'd like**
I would like the texts to be all aligned: everything would be more elegant and professional.

**Describe alternatives you've considered**
None

**Additional context**
![form_1](https://user-images.githubusercontent.com/40598133/45025736-9a6a8a80-b03c-11e8-8016-c3461c2b05f2.jpg)
![form_2](https://user-images.githubusercontent.com/40598133/45025737-9a6a8a80-b03c-11e8-8be5-79de10fb771e.jpg)

**Comment by bainternet** [comment] 2018-09-04 10:38
Duplicate of #4295

**Closed by bainternet** 2018-09-04 10:38 UTC
