### ISSUE TITLE
Bug with Posts Widget 

### ISSUE THREAD

**Issue by KazemirLms** [pojome/elementor#7024] opened 2019-02-09 21:04 UTC
Re-open navigation BUG.

I don't understand why you closed this ticket "Bug with Posts Widget Pagination #4703"
The problem is not solved
 
I also use the pro version. This is a very, very cruel BUG. To switch to the slider you need to reload the entire page. Please take steps to eliminate this trouble.
Currently I have to disable navigation on all news sliders.

**Comment by shilo-ey** [comment] 2019-02-11 08:25
Hi @KazemirLms 

First of, you do not follow the [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md) guidelines
As @bainternet mentioned in the previous thread, this is not a bug.

You are asking to use posts widget with AJAX method for the element to re-render exclusively, a thing we do not support currently.

I merged this issue with  #1284, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Closed by shilo-ey** 2019-02-11 08:25 UTC
