### ISSUE TITLE
Login widget : redirection after wrong password

### ISSUE THREAD

**Issue by kaketusse** [pojome/elementor#6263] opened 2018-11-25 10:56 UTC
## Prerequisites

- [ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
When I build a login page with a Login widget, if I click on the Sign In button with false login/password then I'm redirected to https://ensp.ajluxl.fr/wp-login.php

**Describe the solution you'd like**
It will be great to stay on the custom login page built with Elementor until login succeed.

**Comment by bainternet** [comment] 2018-11-25 12:12
Duplicate of #5355

**Closed by bainternet** 2018-11-25 12:12 UTC
