### ISSUE TITLE
Balloons on mouseover

### ISSUE THREAD

**Issue by JosiahCarberry** [pojome/elementor#6091] opened 2018-11-07 10:43 UTC
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x ] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
See easy to view explanatory information about words or phrases without having to open another tab or page. Typical examples of use could be definitions of technical terms; displaying images of the selected term; etc. A marketer, for example, might wish a picture of a product to be displayed when the mouse is over the name of that product in some text. 

**Describe the solution you'd like**
A balloon opens on a mouseover event for selected phrases or terms in which explanatory text, possibly images, hyperlinks are displayed. Similar to what you see in Wikipedia. One might be able to configure the size and shape of the balloon, a delay for its appearance and/or disappearance, the background color and/or image of the balloon, all typography formatting for the text in the balloon.
The balloon closes when the mouse is no longer over the phrase or term. It might be further useful to fix a format for the terms or phrases thus linked, so as to distinguish them from hyperlinks.
The content of the balloon could be determined either as static text set in the configuration of the page, or as text/images drawn from a hyperlink. In the latter case, some means for fixing the length of the text in the balloon must be settable. The fade out on the last word in the Wikipedia implementation is a very nice touch, although dots of ellipsis would be another solution, should the size of the linked text exceed the size of the balloon.

**Describe alternatives you've considered**
None

**Additional context**
See this screenshot from Wikipedia showing what is displayed during mouseover of the phrase "introduction to genetics"
![image](https://user-images.githubusercontent.com/13927067/48126010-67cd5000-e280-11e8-869f-36e2cc99a9c7.png)

**Comment by bainternet** [comment] 2018-11-08 10:08
Duplicate of #5951

**Closed by bainternet** 2018-11-08 10:08 UTC
