### ISSUE TITLE
Drag widgets directly into tabs and accordions (no shortcodes)

### ISSUE THREAD

**Issue by listentolewis** [pojome/elementor#5381] opened 2018-08-11 06:52 UTC
[ ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
[x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

I searched for this feature request and found a closed ticket from 2016 (here: https://github.com/pojome/elementor/issues/303). It was not implemented (at least not properly) and no reason was given as to why, despite clear backing from the community.

**What problem is your feature request going to solve? Please describe.**
It's going to save a TON of time and prevent dozens of unnecessary shortcodes being created, which also makes the library difficult to navigate. Not to mention having to open each shortcode in a separate editor just to make changes.

**Describe the solution you'd like**
The ability to drag widgets directly into tabs and accordions. Currently you can only do this with shortcodes which is incredibly inefficient in comparison.

**Describe alternatives you've considered**
An alternative already exists but it's slow and cumbersome.

**Comment by black-eye** [comment] 2018-08-11 09:01
+1
Also, the same problem with a deeper column nesting.

**Comment by bainternet** [comment] 2018-08-12 09:39
Duplicate of #2587

**Closed by bainternet** 2018-08-12 09:39 UTC

**Comment by nicholaszein** [comment] 2023-01-11 16:46
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was partially introduced with Elementor **v3.10**! 🥳 

You can learn more about the new **Nested Tabs** experiment [here](https://developers.elementor.com/elementor-3-10-beta/).

✔️ Feel free to check it out and update your plugin to the new version!

Stay tuned for the next versions that will introduce Nested Accordions as well. Please continue the conversation in issue #2587.

Cheers 🥂
